In [ ]:
import requests
import pandas as pd
from typing import Iterable

In [22]:
def get_article_contents(links: Iterable[str]):
    get_url_from_link = lambda link : f"https://www.ufc.com/{link}"

    link_len = len(links)

    for (i, link) in enumerate(links):
        if i % 10 == 0:
            print("Getting page", i, "/", link_len)
    
        try:
            response = requests.get(
                url=get_url_from_link(link), 
                # Pretending to request the page from a Chrome browser so it doesn't block the crawler
                headers={
                "User-Agent": "Mozilla/5.0 (Windows NT 11.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.6998.166 Safari/537.36"
            })
            yield response.text
        except Exception as e:
            print("Error getting page", link)
            print(e)

            yield None

In [ ]:
filename = "./article_links_16-09-25_12-21-53"
articles_df = pd.read_csv(f"{filename}.csv")
articles_df

,link,type,time_ago,headline
0,/video/150984,Interviews,1 hour ago,Ciryl Gane Pre-Fight Interview | UFC 321
1,/video/150983,Interviews,1 hour ago,Tom Aspinall Pre-Fight Interview | UFC 321
2,/news/week-6-preview-dana-whites-contender-ser...,Dana White's Contender Series,3 hours ago,Week 6 Preview | Dana White's Contender Series…
3,/news/updates-ufc-vancouver,Announcements,20 hours ago,Updates To UFC Vancouver
4,/video/150976,Highlights,20 hours ago,Greatest Finishes | Noche UFC: Silva vs Lopes
...,...,...,...,...
2792,/video/144850,Interviews,8 months ago,Punahele Soriano Octagon Interview | UFC Fight...
2793,/video/144847,Interviews,8 months ago,Jacobe Smith Post-Fight Interview | UFC Fight ...
2794,/video/144845,Highlights,8 months ago,Felipe Bunes Snatches First-Round Submission |...
2795,/video/144844,Highlights,8 months ago,Marco Tulio Gets A Debut KO Win | UFC Fight Ni...
2796,/video/144843,Interviews,8 months ago,Ernesta Kareckaitė Post-Fight Interview | UFC ...

In [17]:
articles_with_correct_type = articles_df[
    ((articles_df["type"] == "Results")
    | (articles_df["type"] == "Athletes")
    | (articles_df["type"] == "Fight Coverage")
    | (articles_df["type"] == "Fight Preview"))
    & (~articles_df["link"].str.contains("video"))
]
articles_with_correct_type

,link,type,time_ago,headline
5,/news/scorecard-noche-ufc-san-antonio,Fight Coverage,20 hours ago,The Scorecard | Noche UFC
6,/news/kyle-daukaus-darce-knight-returns,Athletes,21 hours ago,KYLE DAUKAUS | THE D’ARCE KNIGHT RETURNS
12,/news/live-results-official-scorecards-match-r...,Results,2 days ago,Results + Scorecards | Canelo vs Crawford
18,/news/main-card-live-results-fight-recaps-high...,Results,2 days ago,Main Card Results | Noche UFC
38,/news/prelim-live-results-fight-recaps-highlig...,Results,2 days ago,Prelim Results | Noche UFC
...,...,...,...,...
2768,/news/umar-nurmagomedov-is-ready-to-go-into-de...,Athletes,8 months ago,Umar Nurmagomedov Is Ready To Go Into Deep Waters
2770,/news/grant-dawson-very-good-year-ufc-311,Athletes,8 months ago,Grant Dawson's Very Good Year
2772,/news/islam-makhachev-wants-to-eliminate-all-d...,Athletes,8 months ago,Islam Makhachev Wants To Eliminate All Doubt
2778,/news/prelim-results-highlights-winner-intervi...,Results,8 months ago,Prelim Results | UFC Fight Night: Dern vs Ribas 2
2779,/news/main-card-results-highlights-winner-inte...,Results,8 months ago,Main Card Results | UFC Fight Night: Dern vs R...

In [28]:
articles_to_scrape = articles_with_correct_type[articles_with_correct_type["link"].str.contains("news")].copy()
articles_to_scrape

,link,type,time_ago,headline
5,/news/scorecard-noche-ufc-san-antonio,Fight Coverage,20 hours ago,The Scorecard | Noche UFC
6,/news/kyle-daukaus-darce-knight-returns,Athletes,21 hours ago,KYLE DAUKAUS | THE D’ARCE KNIGHT RETURNS
12,/news/live-results-official-scorecards-match-r...,Results,2 days ago,Results + Scorecards | Canelo vs Crawford
18,/news/main-card-live-results-fight-recaps-high...,Results,2 days ago,Main Card Results | Noche UFC
38,/news/prelim-live-results-fight-recaps-highlig...,Results,2 days ago,Prelim Results | Noche UFC
...,...,...,...,...
2768,/news/umar-nurmagomedov-is-ready-to-go-into-de...,Athletes,8 months ago,Umar Nurmagomedov Is Ready To Go Into Deep Waters
2770,/news/grant-dawson-very-good-year-ufc-311,Athletes,8 months ago,Grant Dawson's Very Good Year
2772,/news/islam-makhachev-wants-to-eliminate-all-d...,Athletes,8 months ago,Islam Makhachev Wants To Eliminate All Doubt
2778,/news/prelim-results-highlights-winner-intervi...,Results,8 months ago,Prelim Results | UFC Fight Night: Dern vs Ribas 2
2779,/news/main-card-results-highlights-winner-inte...,Results,8 months ago,Main Card Results | UFC Fight Night: Dern vs R...

In [25]:
contents = [page for page in get_article_contents(articles_to_scrape["link"])]
print("Got", len([page for page in contents if page is not None]), "page contents")

Getting page 0 / 729
Getting page 10 / 729
Getting page 20 / 729
Getting page 30 / 729
Getting page 40 / 729
Getting page 50 / 729
Getting page 60 / 729
Getting page 70 / 729
Getting page 80 / 729
Getting page 90 / 729
Getting page 100 / 729
Getting page 110 / 729
Getting page 120 / 729
Getting page 130 / 729
Getting page 140 / 729
Getting page 150 / 729
Getting page 160 / 729
Getting page 170 / 729
Getting page 180 / 729
Getting page 190 / 729
Getting page 200 / 729
Getting page 210 / 729
Getting page 220 / 729
Getting page 230 / 729
Getting page 240 / 729
Getting page 250 / 729
Getting page 260 / 729
Getting page 270 / 729
Getting page 280 / 729
Getting page 290 / 729
Getting page 300 / 729
Getting page 310 / 729
Getting page 320 / 729
Getting page 330 / 729
Getting page 340 / 729
Getting page 350 / 729
Getting page 360 / 729
Getting page 370 / 729
Getting page 380 / 729
Getting page 390 / 729
Getting page 400 / 729
Getting page 410 / 729
Getting page 420 / 729
Getting page 430 / 729
Getting page 440 / 729
Getting page 450 / 729
Getting page 460 / 729
Getting page 470 / 729
Getting page 480 / 729
Getting page 490 / 729
Getting page 500 / 729
Getting page 510 / 729
Getting page 520 / 729
Getting page 530 / 729
Getting page 540 / 729
Getting page 550 / 729
Getting page 560 / 729
Getting page 570 / 729
Getting page 580 / 729
Getting page 590 / 729
Getting page 600 / 729
Getting page 610 / 729
Getting page 620 / 729
Getting page 630 / 729
Getting page 640 / 729
Getting page 650 / 729
Getting page 660 / 729
Getting page 670 / 729
Getting page 680 / 729
Getting page 690 / 729
Getting page 700 / 729
Getting page 710 / 729
Getting page 720 / 729
Got 729 page contents

In [32]:
articles_to_scrape["content"] = contents
articles_to_scrape.set_index("link", inplace=True)
articles_to_scrape

,type,time_ago,headline,content
link,,,,
/news/scorecard-noche-ufc-san-antonio,Fight Coverage,20 hours ago,The Scorecard | Noche UFC,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
/news/kyle-daukaus-darce-knight-returns,Athletes,21 hours ago,KYLE DAUKAUS | THE D’ARCE KNIGHT RETURNS,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
/news/live-results-official-scorecards-match-recaps-interviews-canelo-vs-crawford-las-vegas,Results,2 days ago,Results + Scorecards | Canelo vs Crawford,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
/news/main-card-live-results-fight-recaps-highlights-winner-backstage-interviews-noche-ufc-lopes-vs-silva,Results,2 days ago,Main Card Results | Noche UFC,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
/news/prelim-live-results-fight-recaps-highlights-winner-backstage-interviews-noche-ufc-lopes-vs-silva,Results,2 days ago,Prelim Results | Noche UFC,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
...,...,...,...,...
/news/umar-nurmagomedov-is-ready-to-go-into-deep-waters-ufc-311,Athletes,8 months ago,Umar Nurmagomedov Is Ready To Go Into Deep Waters,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
/news/grant-dawson-very-good-year-ufc-311,Athletes,8 months ago,Grant Dawson's Very Good Year,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
/news/islam-makhachev-wants-to-eliminate-all-doubt-ufc-311,Athletes,8 months ago,Islam Makhachev Wants To Eliminate All Doubt,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
/news/prelim-results-highlights-winner-interviews-ufc-fight-night-dern-vs-ribas-2,Results,8 months ago,Prelim Results | UFC Fight Night: Dern vs Ribas 2,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
/news/main-card-results-highlights-winner-interviews-ufc-fight-night-dern-vs-ribas-2,Results,8 months ago,Main Card Results | UFC Fight Night: Dern vs R...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."

In [35]:
articles_to_scrape.to_csv(f"{filename}_with_contents.csv")