In [9]:
import os
import pandas as pd
from bs4 import BeautifulSoup
from typing import Iterable
from helpers import get_request, get_image_name, get_page_name

In [10]:
links_df = pd.read_csv("./article_links_16-09-25_12-21-53.csv")
links_df

,link,type,time_ago,headline
0,/video/150984,Interviews,1 hour ago,Ciryl Gane Pre-Fight Interview | UFC 321
1,/video/150983,Interviews,1 hour ago,Tom Aspinall Pre-Fight Interview | UFC 321
2,/news/week-6-preview-dana-whites-contender-ser...,Dana White's Contender Series,3 hours ago,Week 6 Preview | Dana White's Contender Series…
3,/news/updates-ufc-vancouver,Announcements,20 hours ago,Updates To UFC Vancouver
4,/video/150976,Highlights,20 hours ago,Greatest Finishes | Noche UFC: Silva vs Lopes
...,...,...,...,...
2792,/video/144850,Interviews,8 months ago,Punahele Soriano Octagon Interview | UFC Fight...
2793,/video/144847,Interviews,8 months ago,Jacobe Smith Post-Fight Interview | UFC Fight ...
2794,/video/144845,Highlights,8 months ago,Felipe Bunes Snatches First-Round Submission |...
2795,/video/144844,Highlights,8 months ago,Marco Tulio Gets A Debut KO Win | UFC Fight Ni...
2796,/video/144843,Interviews,8 months ago,Ernesta Kareckaitė Post-Fight Interview | UFC ...

In [11]:
gallery_links = links_df[links_df["link"].str.contains("gallery")]
gallery_links

,link,type,time_ago,headline
903,/gallery/photo-gallery-payton-talbott-prepares...,Athletes,2 months ago,Photo Gallery | Payton Talbott Prepares For UF...
932,/gallery/photo-gallery-kai-kara-france-trains-...,Athletes,2 months ago,Photo Gallery | Kai Kara-France Trains For UFC...
1290,/gallery/photo-gallery-erin-blanchfield-trains...,Athletes,3 months ago,Photo Gallery | Erin Blanchfield Trains At UFC…
1705,/gallery/photo-gallery-belal-muhammad-trains-c...,Athletes,4 months ago,Photo Gallery | Belal Muhammad Trains In Chicago…
2207,/gallery/photo-gallery-belal-muhammad-and-yair...,Athletes,6 months ago,Photo Gallery | Belal Muhammad And Yair Rodrig...
2208,/gallery/photo-gallery-ignacio-bahamondes-trai...,Athletes,6 months ago,Photo Gallery | Ignacio Bahamondes Trains For ...
2245,/gallery/photo-gallery-rafael-fiziev-trains-uf...,Athletes,6 months ago,Photo Gallery | Rafael Fiziev Trains For UFC 3...
2717,/gallery/charles-oliveira-and-tracy-cortez-hos...,Community,7 months ago,Charles Oliveira And Tracy Cortez Host Jiu-Jitsu…

In [12]:
def download_images(links: Iterable[str]):
    def download_images_on_page(page_link: str):
        try:
            page_content = get_request(f"https://ufc.com{page_link}").content

            soup = BeautifulSoup(page_content, "html.parser")
            images = soup.find_all("img")
            image_srcs = [image.get("src") for image in images]

            folder = f"images/{get_page_name(page_link)}"
            if os.path.exists(folder):
                return

            os.makedirs(folder)
            
            for src in image_srcs:
                filename = get_image_name(src)

                with open(f"{folder}/{filename}", "wb") as file:
                    image_content = get_request(src).content
                    file.write(image_content)
        except Exception as e:
            print("Error downloading image", src, "from", page_link)
            print(e)
    
    list_len = len(links)

    for (i, link) in enumerate(links):
        print("Getting images from page", i, "/", list_len)
        download_images_on_page(link)

In [13]:
download_images(gallery_links["link"])

Getting images from page 0 / 8
Getting images from page 1 / 8
Getting images from page 2 / 8
Getting images from page 3 / 8
Getting images from page 4 / 8
Getting images from page 5 / 8
Getting images from page 6 / 8
Getting images from page 7 / 8