In [1]:
import os
import re
from itertools import chain
from concurrent.futures import ThreadPoolExecutor
import pandas as pd
import spacy
from spacy.tokens.doc import Doc
from spacy.tokens.span import Span
from spacy.tokens.token import Token
import coreferee
from coreferee.data_model import ChainHolder
from helpers import get_request
from bs4 import BeautifulSoup
from bs4.element import Tag

c:\Users\Adam\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages\coreferee\manager.py:11: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [2]:
nlp = spacy.load("en_core_web_lg")
nlp.add_pipe("coreferee")

In [3]:
def get_text_from_file(path: str):
    text = ""
    
    try:
        with open(path, "r", encoding="utf8") as file:
            text = file.read()
    except Exception as e:
        print("Error reading file", path)
        print(e)
    finally:
        return text

In [4]:
articles_folder = "./articles"

In [5]:
article_files = os.listdir(articles_folder)
article_files = [file for file in article_files if file.endswith(".txt")]

In [6]:
files_subset = article_files[:5]

In [9]:
texts = [get_text_from_file(f"{articles_folder}/{file}") for file in article_files]

df = pd.DataFrame(data={
    "file": article_files,
    "text": texts
})
df

,file,text
0,news_10-june-schedule-jam-packed-goodness.txt,"Buckle up, kids, because the June schedule is ..."
1,news_10-massive-fights-schedule-may.txt,There are all kinds of different ways to look ...
2,news_10-memorable-moments-down-under.txt,"On Saturday, February 8, the UFC returns to Qu..."
3,news_10-middleweights-biggest-championship-mom...,Fourteen individuals have held the UFC middlew...
4,news_10-most-memorable-ufc-moments-canada.txt,As we continue our Canadian-focused march thro...
...,...,...
724,news_zhang-mingyang-all-gas-no-brakes-ufc-kans...,Rising Chinese star Zhang Mingyang has a stat ...
725,news_zhang-mingyang-embracing-spotlight-ufc-sh...,Zhang Mingyang has all the makings of a potent...
726,news_zhang-mingyang-journey-main-event-light-h...,Zhang Mingyang first entered the UFC ecosystem...
727,news_zhang-weili-builds-her-case-goat-status.txt,
728,news_zhang-weili-built-different-ufc-312.txt,If you ever wondered what separates the all-ti...

In [10]:
# This takes a long time, so have patience
df["doc"] = list(nlp.pipe(texts))

In [11]:
def get_people(doc: Doc):
    return [ent for ent in doc.ents if ent.label_ == "PERSON"]

In [12]:
df["people"] = df["doc"].apply(get_people)

In [13]:
all_people: list[Span] = list(chain.from_iterable(df["people"]))
all_names = set(p.text for p in all_people)
full_names = set(name for name in all_names 
                 if 
                 len(name.split()) >= 2 
                 and len(name.split()) <= 3
                 and re.search("^[a-zA-Z\s’]+$", name) is not None)

In [14]:
def is_woman_tag(tag: Tag):
    text = tag.get_text().strip().lower()
    return "woman" in text or "women" in text

def find_gender_on_ufc(name: str):
    name_query = "-".join(name.split()).replace('’', ' ')
    url = f"https://www.ufc.com/athlete/{name_query}"

    try:
        response = get_request(url)
        soup = BeautifulSoup(response.text, "html.parser")

        tags: list[Tag] = soup.find_all("p", "hero-profile__tag")
        if not tags:
            return None

        is_woman = any([is_woman_tag(tag) for tag in tags])
        if is_woman:
            return "woman"
        else:
            return "man"
    except Exception as e:
        print("Error getting gender of", name)
        print(e)

In [15]:
full_names

{'Malcolm Wellmaker',
 'Trey Ogden',
 'Rafael Cerquiera',
 'Ty Miller',
 'Javid Basharat',
 'Kevin Costner',
 'Steve Latrell',
 'Felipe Bunes',
 'Thiago Moises',
 'Lodune Sincaid',
 'Melissa Martinez',
 'Randa Markos',
 'An Tuan Ho',
 'Ryan Hall',
 'Henry Corrales',
 'Katlyn Cerminara',
 'Uncle Joe',
 'Akira Corassani',
 'Davide Scarano',
 'Gabe Green',
 'Viktoriia Dudakov',
 'Nazim Sadykhov',
 'Hyder Amil',
 'Ian Heinisch',
 'Germaine de Randamie',
 'Miguel Baeza',
 'Yanal Ashmouz',
 'Viktoriia Dudakva',
 'Czerwony Smok',
 'Timmy Cuambadef',
 'Caio Machado',
 'HanSeul Kim',
 'Justin Gaethje',
 'Bill Belichick',
 'Ricky Turcios',
 'Jason Parillo',
 'Gustavo Wurlitzer',
 'Michael Jordan',
 'Randy Brown',
 'Istela Nunes',
 'Carlos Leal',
 'Wilson Reis',
 'Eddie Wineland',
 'Sayif Saud',
 'Chael Sonnen',
 'Puro Chicali',
 'Leroy Duncan',
 'Oumar Sy',
 'Jayson Tatum',
 'Will Fiziev',
 'Magomed Gadhziyasulov',
 'nee Calderwood',
 'Salahdine Parnasse',
 'Will Chandler',
 'James Llontop',
 'Joseph Lowry',
 'Elizeu Zaleski',
 'Pablo Sucupira',
 'Eugene Jackson',
 'Aleksei Oleinik',
 'Maurice Greene',
 'Mohammed Alakel',
 'Punahele Soriano',
 'Pete Sell',
 'James Llontop later',
 'Carlson Harris',
 'Aleksandar Rakic',
 'Kevin Dornan',
 'Dorian Ramos',
 'Imanol Rodriguez',
 'SeokHyeon Ko',
 'Klidson Abreu',
 'Rubens Charles Maciel',
 'Pedro Rizzo',
 'Al Iaquinta',
 'Kamaru Usman',
 'Charlie Jo',
 'Sidney Outlaw',
 'Newcomer Elijah Smith',
 'Herkus Lukosiunas',
 'Jalen Johnson',
 'Islam Makhachev',
 'John Wood',
 'Cody Gibson',
 'Travis Crawford',
 'Eric Shelton',
 'Hamdy Abdelwahab',
 'Kris Moutinho',
 'da Silva',
 'Randall Wallace',
 'Tim Sylvia',
 'Ed Belfour',
 'Jessica Andrade',
 'Khabib Nurmagomedov',
 'Mackeznzie Dern',
 'Lerryan Douglas',
 'Jamahal Hill',
 'Ramon Dekkers',
 'Antonio Rogerio Nogueira',
 'Alexander Hernandez',
 'Roberto de Souza',
 'TJ Dillashaw',
 'David Obama',
 'Priscila Cachoeira',
 'Darren Stewart',
 'Eryk Anders',
 'Dooho Choi',
 'Elias Theodorou',
 'Jordan Leavitt',
 'Brandon Royval',
 'Darya Zheleznyakova',
 'Cory Sandhagen',
 'HyunSung Park',
 'Ray Cooper III',
 'the Alexander Hernandez',
 'Joe Lauzon',
 'Edson Barboza',
 'Arthur Lopes',
 'Cynthia Calvillo',
 'Polyana Viana',
 'Barry Sanders',
 'Nasrat Haqparast',
 'Mounir Lazzez',
 'CJ Vergara',
 'Asu Almabayev\nLocation',
 'Charles Oliveira',
 'Andreas Michailidis',
 'AJ Bryant',
 'Dominic Waters',
 'Ash Grimshaw',
 'Ray Longo',
 'Yancy Medeiros',
 'Pro Max',
 'Michal Figlak',
 'Alex Morono',
 'Francis Marshall',
 'Khamzat Chimaev',
 'Mateusz Rebecki',
 'Brendson Ribeiro',
 'Cale Sanderson',
 'Wes Schultz',
 'Andre Fili',
 'Tyron Woodley',
 'Gilbert Urbina',
 'Keith Peterson',
 'Bantamweights Brad Katona',
 'Li Jingliang',
 'Brandon Lewis',
 'Tyson Pedro',
 'Eduardo Garagorri',
 'Natalia Silva',
 'Baergeng Jieleyisi',
 'Sultan Almohammed',
 'Paul Reed',
 'Kevin\xa0Schuster',
 'Quang Le',
 'Nathaniel Wood',
 'Anthony Perosh',
 'Allen Huggins',
 'Darren Till',
 'Miranda Maverick',
 'Charles Byrd',
 'Jayson Werth',
 'Jessica Aguilar',
 'Lee Scott',
 'Luana Pineiro',
 'Mike Valle',
 'Hugo Cuhna',
 'Sal D’Amato',
 'Ben Askren',
 'Marlon Moraes',
 'Gil Castillo',
 'Trey Waters',
 'Josh Hokit',
 'Nate Quarry',
 'Michal Oleksiejczuk def',
 'Andrey Pulyaev',
 'Youssef Zalal',
 'Shoehei Nose',
 'Julien Williams',
 'Joaquim Silva',
 'Simeon Powell',
 'Chad Anheliger',
 'Clayton Carpenter',
 'Charles Oliveira’s',
 'Peter Fazekas',
 'Dione Barbosa',
 'Talita Alencar',
 'Juan Archuleta',
 'Albert Tumenov',
 'Devonte Smith',
 'Anthony Hernandez',
 'Shane Young',
 'Brazilian Kaue Fernandes',
 'Julianna Lima',
 'Benoit Saint Denis',
 'Jack Shore',
 'Joao Emilio',
 'Jonathan Martinez',
 'Azamat Murzaknov',
 'Lemony Snicket',
 'Cristian Perez',
 'Glover Teixeira',
 'Nariman Abbasov',
 'Chepe Marsical',
 'Julius Walker',
 'Clint Hester',
 'Holly Holm',
 'Charles Johnson',
 'Mike Beltran',
 'Liam Anderson',
 'Rob Wilkinson',
 'Juancamilo Ronderos',
 'Toshiomi Kazama',
 'Joel Alvarez',
 'Carlston Harris',
 'Hugh Pulley',
 'Aaron Pico',
 'Frankie Edgar',
 'Ken Shamrock',
 'Hyo Jun Choi',
 'Cody Haddon',
 'Chidi Njokuani',
 'Blake Grice',
 'De La Rosa',
 'Jack Della Maddalena',
 'Bevon Lewis',
 'Rei Tsuruya',
 'Kid Yamamoto',
 'Mitch Raposo',
 'Suloev Stretch',
 'Ozzy Diaz',
 'Zhang Mingyang\nSilva',
 'Top Kiwram',
 'Luis Villanueva',
 'Dave Menne',
 'Jacob Silva',
 'Tucker wherefans',
 'Roosevelt Roberts',
 'Nikolas\xa0Motta',
 'Yanis Ghemmouri',
 'Mauricio Ruffy',
 'Diego Brandao',
 'Roxanne Modafferi',
 'Jared Cannnoier',
 'Shavkat Rakhmonov',
 'Nick Aguirre',
 'Will Currie',
 'Johnny Eduardo',
 'Gerald Meerschaert',
 'TJ Dillashaw’s',
 'Carlos Prates',
 'Mike Davis',
 'Tyson Nam',
 'Takeya Mizuhaki',
 'Thiago Santos',
 'Ottman Azaitar',
 'Beating Silva',
 'Diego Sanchez',
 'Paulo Costa',
 'Martin Pakciarz',
 'Chris Clements',
 'Jacobe Smith',
 'Josh Emmett',
 'Jared Gordon',
 'Jack Congdon',
 'Dan Henderson',
 'Chidi Njokuanivs',
 'Cristiano Marcello',
 'Tim Welch',
 'Marnic Mann',
 'Rafa Garcia',
 'Pat Pytlik',
 'Ryan Spann',
 'Sara McMann',
 'Brendan Allen’s',
 'Johny Hendricks',
 'Andreas Michael',
 'Pat Healy',
 'Tresean Gore',
 'Trevin Jones',
 'Zubaira Tukhugov',
 'Lucas Almeida',
 'Chad Hanekom',
 'Daniel Marcos',
 'Kyle Noke',
 'Cameron Saaiman',
 'Justin Tafa',
 'Billy Quarantillo',
 'Ross Pearson',
 'Ramazan Emeev',
 'Rolando Bedoya',
 'Lukasz Brzeski',
 'Buddy Guy',
 'Ignacio Baamonde',
 'Carlos Candelario',
 'Jose Aldo',
 'Chase Boutwell',
 'Kiefer Crosbie',
 'Ariane Carnelossi',
 'Tabatha Ricci',
 'Bo Nickal',
 'du Plessis',
 'Valter Walker',
 'Norma Dumont',
 'Johnny Eblen',
 'Pawel Pawlak',
 'Daniel Roberts',
 'Kron Gracie',
 'Magomed Magomedov',
 'Christian Leroy Duncan',
 'Joshua Van',
 'Alexander Gustafsson',
 'Randy Couture',
 'Tony Hawk',
 'Dustin Poirer',
 'Magomed Ankalaev',
 'John Castaneda',
 'Yura Kaito',
 'Marcos DaMatta',
 'Mick Maynard',
 'Maki Pitolo',
 'Will Weili',
 'Zach Reese',
 'Raquel Welch',
 'Fighting Nerds',
 'Antonio Monteiro',
 'Azamat Murzakanov',
 'Cro Cop',
 'Andre Barriault',
 'Ricardo Lamas',
 'Aaron Phillips',
 'Samuel Sanches',
 'Thiago Tavares',
 'Colby Covington',
 'Leon Edwards',
 'Cody Stamann',
 'Mike Brown',
 'Axel Sola',
 'Luana Carolina',
 'Ian Machado Garry',
 'Alistair Overeem',
 'Kevin Schuster',
 'Raquel Pennington',
 'Henry Cejudo',
 'Aljamain Sterling',
 'Evan Elder',
 'Mark Choinski',
 'Charles’ jiu jitsu',
 'Strawweight Namajunas',
 'Doc Holliday',
 'Ketlen Viera',
 'Lucas Alexander',
 'Billy Elekana',
 'Ariane da Silva',
 'Denise Gomes',
 'Shinsuke Nakamura',
 'Eric Pena',
 'Din Thomas',
 'Melsik Baghdasaryan',
 'Igor Severino',
 'Eric Nicksick',
 'Dan Hooker',
 'Seth Baczynski',
 'Jairzinho Rozenstruik',
 'Daniel Straus',
 'Damon Jackson',
 'Scott Jorgensen',
 'Tatiana Padilla',
 'Jas Jas',
 'Calvin Katter',
 'Giga Chikadze',
 'Diego Lopes’ UFC',
 'Amir Albazi',
 'Aiemann Zahabi',
 'Rayanne dos Santos',
 'Carli Judice',
 'Liam Neeson',
 'Featherweights Tommy McMillen',
 'Danny Castillo',
 'Tessa Sinatro',
 'Silva pantomimed',
 'Justin Sumter',
 'Brandon Holmes',
 'Alexia Thainara',
 'Aaron Tau',
 'Montse Rendon',
 'Dusko Todorovic',
 'Joe Doerksen',
 'Jamie Pickett',
 'Kris McCray',
 'Andre Petroski',
 'Dante Rivera',
 'DooHo Choi',
 'Abdul Rakhman Yakhyaev',
 'Sergio Pettis',
 'Angela Hill',
 'Ion Cutelaba',
 'Daniel Zellhuber',
 'Guram Kutateladze',
 'Gabriel Santos',
 'Viviane Pereira',
 'Jose Medina',
 'Hector Ramirez',
 'Nikolas Motta',
 'Claudia Gadelha',
 'Jordan Vucenic',
 'Marcio Barbosa',
 'Billy Ray Goff',
 'Shonie Carter',
 'Melissa Mullins',
 'Matthew Semelsberger',
 'Middleweight DWCS',
 'Jim Miller',
 'Diego Lopes\nLocation',
 'Belal\xa0Muhammad',
 'Clarence Darrow',
 'Mikheil Sazhiniani',
 'Trevor Wittman',
 'Ateba Gautier',
 'Niko Price',
 'Joe Rogan',
 'Angela Lee',
 'Yadier Del Valle',
 'Ilia Topuria',
 'John Dodson',
 'Donovan Beard',
 'Bryan Caraway',
 'Dominick Reyes',
 'Chris Padilla',
 'Nick Piccininni',
 'Tom Aspinall',
 'Rana Singh',
 'Chris Gutierrez',
 'Bekzat Almakhan',
 'Tim Credeur',
 'Leone Murphy',
 'Gillian Robertson',
 'Victor Hugo',
 'Julio Cesar Chavez',
 'Shawn Michaels',
 'Stephan Bonnar',
 'Will Blaydes',
 'Jon Jones',
 'Miesha Tate',
 'Dan Argueta',
 'Rafael Natal',
 'Michel Pereira',
 'Zac Pauga',
 'Dos Anjos',
 'Sean Stickland',
 'Machado Garry',
 'Sam Hughes',
 'Khabib Nurmagomedov’s',
 'Yoel Romero',
 'Jackson McVey',
 'AJ Erosa',
 'Kyung Ho Kang',
 'Michael Aswell',
 'Des Green',
 'Mike Breeden',
 'Gilbert Melendez',
 'Gervonta Davis',
 'Kyung Ho Hang',
 'Carl Prince',
 'Jack Cartwright',
 'Drako Rodriguez',
 'Ange Loosa',
 'Andrew Glenn',
 'Karolina Kowalkiewicz',
 'Benson Henderson',
 'Dennis Brown',
 'Santiago Ponzinibbio',
 'Jamey Lyn Horth',
 'Carlos Condit',
 'Vince Morales',
 'Kameula Kirk',
 'Marvin Vettori',
 'Icaro Brito',
 'Marc Diakiese',
 'Kenny Florian',
 'Taila Santos',
 'Gordon Ryan',
 'Rose Namajunas',
 'Chris Duncan',
 'Michael Oleksiejczuk',
 'Diego Ferreira',
 'John Gooden',
 'Mason Jones',
 'Dan Kelly',
 'Matthieu Duclos',
 'Tony Ferguson',
 'Robert Whiteford',
 'Patricio Pitbull',
 'Montserrat Rendon',
 'Klaudia Sygula',
 'Kyle Nelson',
 'Kyle Daukaus',
 'Urijah Faber',
 'Radley Da Silva',
 'Serghei Spivac',
 'Alice Pereira',
 'Steve Garcia',
 'Jessica Penne',
 'Isaac Dulgarian',
 'Jeremiah Wells',
 'Cody Durden',
 'Dos Santos',
 'Los Chupacabras',
 'Askar Askarov',
 'Chepe Mariscal',
 'SeungGuk Choi',
 'Sean Sharaf',
 'Denis Tiuliulin',
 'Rizin FF',
 'Anthony Smith',
 'Miami Dolphins',
 'Cris Cyborg',
 'Bartosz Szewczyk',
 'Chase Hooper’s',
 'Chris Cutis',
 'Jazmin Jauregui',
 'Jacky Bryant',
 'Junyong Park',
 'David Onama',
 'Jasmine Jasudavicius',
 'Deiveson Figueiredo\nLocation',
 'Stipe Miocic',
 'La Banquise',
 'Barack Obama',
 'Mohammed Usman',
 'Conor McGregor',
 'Michael Dufort',
 'Ian Freeman',
 'Kobe Bryant',
 'Nikita Krylov',
 'Yazmin Jauregui',
 'Yi Zha',
 'Artem Kosminov',
 'Bruce Buffer',
 'Matheus Nicolau',
 'Takanori Gomi',
 'Ode’ Osbourne',
 'Acosta square',
 'Nathan Fletcher',
 'Macy Chiasson',
 'Flyweights Alden Coria',
 'Valentina Shevchenko Moneyline',
 'blitzed Perez',
 'Viacheslav Borshchev',
 'Quemuel Ottoni',
 'Kate Jackson',
 'Sean Shelby',
 'Raufeon Stots',
 'Matt Sayles',
 'Alan Jouban',
 'Christos Giagos',
 'Saint Denis',
 'Alessandro Costa',
 'Loma Lookboonmee',
 'Mario Pinto',
 'Jack Della Madallena',
 'Cezary Oleksiejczuk',
 'Jean\xa0Silva',
 'Bantamweights Davey Grant',
 'Brian Bowles',
 'Rafael Dos Anjos',
 'Paul Felder',
 'Vinicius Cenci',
 'Manuel Torres',
 'Tecia Torres',
 'Robert Bryczek',
 'Bruno Silva',
 'Tim Means',
 'Belal Muhammad',
 'Joe Doerkson',
 'Rodrigo Vargas',
 'Mandel Nallo',
 'Jamais mort',
 'Petr Yan',
 'Vada Rae',
 'Adrian Yanez',
 'Gregory Rodrigues\n',
 'Sodiq Yusuff',
 'Montel Jackson',
 'Furkatbek Yokubov',
 'Matt Serra',
 'Adam Fugitt',
 'Jimmy Crute',
 'Mandell Nallo',
 'Drew Dober',
 'Anderson Silva’s',
 'Nathan Diaz',
 'Mark Chiesa',
 'Brad Riddell',
 'Brian Ortega',
 'Kay Hansen',
 'Francisco Grasso',
 'Alex Pereira’s',
 'Beating Allen',
 'Joshua\xa0Van',
 'Joanna Jedrzejczyk',
 'Herbert Burns',
 'Rodolfo Vieira',
 'Dustin Ortiz',
 'Dominick Cruz',
 'Will Barber',
 'George Mangos',
 'Myron Dennis',
 'John Crouch',
 'Steve Erceg',
 'Erson Yamamoto',
 'Edwin Flack Avenue',
 'Sam Alvey',
 'Loik Radzhabov',
 'Ramazan Temirov',
 'Antonio Carlos Junior',
 'Derek Cleary',
 'Mark Coleman',
 'Edmen Shahbazyan',
 'Viviane Araujo',
 'Brett Okamoto',
 'Jarno Errens',
 'Jacare Souza',
 'Alex Perez',
 'Luis Gurule',
 'Matt Schnell',
 'Luke Rockhold',
 'Alexandre Pantoja',
 'Marcin Prachnio',
 'Donte Johnson',
 'Ibo Aslan',
 'Chasen Blair',
 'Shawn da Silva',
 'Robert Hoyle',
 'Zhang Weili',
 'Sona Akale',
 'Orion Cosce',
 'Cristian Quinonez',
 'Amanda Nunes',
 'bantamweights Cory Sandhagen',
 'Daniel Barez',
 'Danny Barlow',
 'Tom Nolan',
 'Alex Reyes',
 'Joselyne Edwards',
 'Khaos Williams chuckles',
 'Sheldon Westcott',
 'Forrest Griffin',
 'Kevin McDonald',
 'Bishop Auckland',
 'Shane Burgos',
 'Makhmud Muradov',
 'Shannon Clark',
 'Jose Johnson',
 'Sarah Kaufman',
 'Cesar Almeida',
 'Charles Jourdain',
 'Diego\xa0Lopes',
 'Vinny Diaz',
 'Karine Silva',
 'Zaleski dos Santos',
 'Jon Anik',
 'Anderson Silva',
 'Bruno Mukulu',
 'Marina Rodriguez',
 'Steve Austin',
 'Josh Parisian',
 'Xavier Franklin',
 'Omari Akhmedov',
 'Gregory Rodrigues',
 'Hearing Fili',
 'Don Shainis',
 'Jessica Eye',
 'AJ Dobson',
 'Neil Magny',
 'Topnoi Kiwram',
 'Julianna Pena',
 'Jussier Formiga',
 'Tracy Cortez',
 'Nina Nunes',
 'Zhang Mingyang',
 'Will Suarez',
 'Augusto Sakai',
 'Taiyilake Nueraji',
 'Mirko Cro Cop',
 'Marion Reneau',
 'Muin Gafarov',
 'Charles Oliveira\n',
 'Georgi Karakhanyan',
 'the Gracie Barra',
 'TJ Brown',
 'Tainara Lisboa',
 'Kyoji Horiguchi',
 'Luigi Vendramin',
 'Brandon Adams',
 'Alex Oliveira',
 'Bobby Green',
 'Hail Mary',
 'Gillian Robertson’s',
 'Mark Kerr',
 'Nicolas Dalby',
 'Laura Sanko',
 'du Plessis’',
 'Azat Maksum',
 'Vitor Belfort',
 'Jeff Meyer',
 'Ernesta Kareckaite',
 'Ivan Dychko',
 'Eric Nolan',
 'Jimmie Rivera',
 'Timmy Cuamba',
 'Cody Brundage',
 'Casey O’Neill',
 'Oban Elliott',
 'Frank Ocean',
 'Eddy Reynoso',
 'Fabiano Buskei',
 'Kody Steele',
 'Dan Hardy',
 'Yasmim Santos',
 'Vicente Luque',
 'John Yannis',
 'JunYong Park',
 'El Tanke',
 'Carlos Newton',
 'Claudio Silva',
 'Robbie Lawler',
 'Tim Elliott',
 'Alice Ardelean',
 'Mike Guymon',
 'Darren Elkins',
 'Chris Birchler',
 'Joanderson Brito',
 'Phil de Fries',
 'Guillermo Torres',
 'Taylor Swift’s',
 'Colby Thicknesse',
 'Roedie Roets',
 'Ciryl Gane',
 'Ian Machado',
 'Johnny Walker',
 'Warlley Alves',
 'Chihiro Suzuki',
 'Daniel Cormier',
 'Robert Ruchala',
 'Ante Delija',
 'Chase Hooper',
 'Yana Santos',
 'Harvey Dock',
 'Marc Goddard',
 'Mackenzie Dern',
 'UFC Shanghai',
 'Rory MacDonald',
 'Beating Pereira',
 'Benardo Sopaj',
 'Saladhine Parnasse',
 'Ray Sefo',
 'Bobby Knuckles',
 'Said Jones',
 'Lupe Fiasco',
 'Pedro Munhoz',
 'Felipe Franco',
 'Kevon Looney',
 'Mateus Mendonca',
 'Terrance McKinney',
 'Alvin Hines',
 'Phil Hawes',
 'Rodrigo Nascimento',
 'Vitoria da Conquista',
 'Marc Fiore',
 'Lyoto Machida',
 'Ricky Simon',
 'Jailton Almeida',
 'Kyler Phillips',
 'Stuart Austin',
 'Aaron McKenzie',
 'Tatsuro Taira',
 'Caio Borralho\n',
 'Payton Talbott',
 'Mark Weir',
 'Jan Blachowicz',
 'Nyamjargal Tumendemberel',
 'Will Sandhagen',
 'Torrez Finney',
 'Shauna Bannon',
 'Michael Crichton',
 'Leo XIV',
 'Zach Makovsky',
 'Will Pavlovich',
 'Keith Jardine',
 'Du Plessis',
 'ChangHo Lee',
 'Brad Katona',
 'Andre Lima',
 'Jalin Turner',
 'Kevin Jouset',
 'Tito Ortiz',
 'jiu jitsu',
 'Devin Powell',
 'Jose Miguel Delgado',
 'Vanilto Antunes',
 'Steven Nguyen',
 'Nik Lentz',
 'Taylor Moore',
 'Lukasz Bosacki',
 'Zabit Magomedsharipov',
 'Shavkat Rakhmanov',
 'Dequan Townsend',
 'Devin Clark',
 'Jeremy Stephens',
 'Arman Tsarukyan',
 'Hitomi Akano',
 'Natan Levy',
 'Sean Woodson',
 'Julian Erosa',
 'Victor Henry',
 'Alexa Grasso',
 'Maycee Barber',
 'Jamall Emmers',
 'Mike Malott',
 'Miles Johns',
 'Cory McKenna',
 'Daron Cruickshank',
 'Kennedy Nzechukwu',
 'jiu jitsu pedigree',
 'Rani Yahya',
 'Simon Head',
 'Kolton England',
 'Manoel Sousa',
 'Cameron Smotherman',
 'Kanako Murata',
 'Vladimir Matyushenko',
 'Alexander Volkov',
 'Ricardo Arona',
 'Diego Nunes',
 'Tommy Cuozzi',
 'Joanna Violence',
 'Claressa Shields',
 'Ryan Loder',
 'Ronda Rousey',
 'Brandon Davis',
 'Sam Calavitta',
 'Daniel Rodriguez',
 'Robert Valentin',
 'Luana Pinheiro',
 'Trevor Peek',
 'Johnavan Vistante',
 'Kru Bob Perez',
 'Javier Martinez',
 'Luigi Vendramini',
 'Yashuhiro Urushitani',
 'Ronald Paradeiser',
 'Jailton Malhadinho',
 'Mohammad Usman',
 'Jacqueline Cavalcanti',
 'Dalcha Lungiambula',
 'Dana Whtie’s',
 'Firas Zahabi',
 'Jake Shields',
 'John Phillips',
 'Joseph Morales',
 'Matt Bessette',
 'Ian McCall',
 'Eduardo Chapolin',
 'Conejo Ruiz',
 'Marcin Tybura',
 'JooSang Woo',
 'Issa Isakov',
 'Jaqueline Amorim',
 'Nick Diaz',
 'bantamweights Victor Henry',
 'Elise Reed',
 'Evan Dunham',
 'Khamzat Chimaev\nLocation',
 'Stephanie Egger',
 'Josefine Knutsson',
 'Loopy Godinez',
 'Brandon Carlo',
 'Samuel Silva',
 'Michal Oleksiejczuk’s',
 'Spencer Fisher',
 'Roger Huerta',
 'Daniel Strausand',
 'Shohei Nose',
 'David Dvorak',
 'Luis Saldana',
 'Amanda Cooper',
 'Brazilian Warlley Alves',
 'James Gallagher',
 'Charles Olivera',
 'Claudio Puelles',
 'Garry Tonon',
 'Landon Quinones',
 'Jason Brilz',
 'Herb Dean',
 'Jamie Varner',
 'Khabib Numragomedov',
 'Movsar Evloev',
 'Brendan Fitzgerald',
 'Lucas Martins',
 'Julio Arce',
 'Hunter Azure',
 'Pat Sabatini',
 'Darion Abbey',
 'Patricio Freire',
 'Julija Stoliarenko',
 'Rafael Fiziev',
 'JeongYeong Lee',
 'Jason House',
 'Valentina Shevchenko',
 'Nazim Sadykov',
 'the Dana White’s',
 'Kanye West',
 'Emily Ducote',
 'Bryce Mitchell',
 'Steven Asplund',
 'Kazushi Sakuraba',
 'Bangtao Muay Thai',
 'Zak Cummings',
 'Mitch Ramirez',
 'Denys Bondar',
 'Jonathan Micallef',
 'Redd Foxx',
 'Vanilton Antunes',
 'Makwan Amirkhani',
 'Trent Miller',
 'Alan Patrick',
 'Myktbek Orolbai',
 'Calvin Kattar',
 'Nate Landwehr',
 'Grant Dawson',
 'Nazim\xa0Sadykhov',
 'Jose Ochoa',
 'Drakkar Klose',
 'Will Green',
 'Azamat Bekoev',
 'Enriko Kehl',
 'Jesus Aguilar',
 'Vinicius Oliveira',
 'Victoria Leonardo',
 'Jose Daniel',
 'Kaan Olfi',
 'Rizvan Kuniev',
 'Beating Max',
 'Steven Nelson',
 'Terence Crawford',
 'Ernie Juarez',
 'Brad Pickett',
 'Edivan Santos',
 'Alex Caceres',
 'Rafael Cerqueira',
 'Islam Dulatov',
 'Taylor Swift',
 'Paul Rimmer',
 'Kyle Crutchmer',
 'Manon Fiorot',
 'Manny Gamburyan',
 'Israel Adensanya',
 'Shamil Gazievto',
 'Kamuela Kirk',
 'UFC X',
 'Jack\xa0Della Maddalena',
 'John Mulaney',
 'Craig Jones',
 'Gabriel Benitez',
 'Tony Gravely',
 'Daffy Duck',
 'Lone’er Kavanagh',
 'Cain Velasquez',
 'Jeong Yeong Lee',
 'Diego Lopes',
 'Julia Avila',
 'Marvin Egan',
 'Stephanie Luciano',
 'dos Santos',
 'Muin Gafurov',
 'Muhammad Ali',
 'Moon Knight',
 'Kurt Holobaugh',
 'Sadykhov cutting Motta',
 'Anton Turkalj',
 'Nate Diaz',
 'Mike Lullo',
 'Armen Petrosyan',
 'Dricus du Plessis',
 'Mark Currier',
 'Karol Rosa',
 'Rodrigo Cavaca',
 'Chris Prickett',
 'Kevin Randleman',
 'Abdul Razak Alhassan',
 'Kevin Holland',
 'Chito Vera',
 'Andrew Kochel',
 'Frank Mir',
 'Valerie Letourneau',
 'John Philips',
 'Nicolas Ott',
 'Billy Goff',
 ...}

In [16]:
# Set this to False if you want to fetch the genders from the UFC website
use_saved_gender_map = False
genders_map_file = "./genders_map.csv"

if use_saved_gender_map and os.path.exists(genders_map_file):
    name_gender_pairs_df = pd.read_csv(genders_map_file)
    genders_map: dict[str, str] = dict(zip(name_gender_pairs_df["name"], name_gender_pairs_df["gender"]))
else:
    def get_name_gender_pair_on_ufc(name: str):
        return (name, find_gender_on_ufc(name))

    with ThreadPoolExecutor() as executor:
        name_gender_pairs = [
            (n, g)
            for n, g in executor.map(get_name_gender_pair_on_ufc, full_names)
            if g is not None
        ]

    genders_map = dict(name_gender_pairs)

    for name, gender in name_gender_pairs:
        for name_component in name.split():
            genders_map[name_component] = gender

    pd.DataFrame(data={
        "name": genders_map.keys(),
        "gender": genders_map.values(),
    })\
        .set_index("name")\
        .to_csv(genders_map_file)

genders_map

{'Malcolm Wellmaker': 'man',
 'Trey Ogden': 'man',
 'Ty Miller': 'man',
 'Javid Basharat': 'man',
 'Felipe Bunes': 'man',
 'Thiago Moises': 'man',
 'Lodune Sincaid': 'man',
 'Melissa Martinez': 'woman',
 'Randa Markos': 'woman',
 'Ryan Hall': 'man',
 'Katlyn Cerminara': 'woman',
 'Akira Corassani': 'man',
 'Gabe Green': 'man',
 'Nazim Sadykhov': 'man',
 'Hyder Amil': 'man',
 'Ian Heinisch': 'man',
 'Germaine de Randamie': 'woman',
 'Miguel Baeza': 'man',
 'Yanal Ashmouz': 'man',
 'Caio Machado': 'man',
 'HanSeul Kim': 'man',
 'Justin Gaethje': 'man',
 'Ricky Turcios': 'man',
 'Randy Brown': 'man',
 'Istela Nunes': 'woman',
 'Carlos Leal': 'man',
 'Wilson Reis': 'man',
 'Eddie Wineland': 'man',
 'Oumar Sy': 'man',
 'James Llontop': 'man',
 'Joseph Lowry': 'man',
 'Eugene Jackson': 'man',
 'Aleksei Oleinik': 'man',
 'Maurice Greene': 'man',
 'Punahele Soriano': 'man',
 'Pete Sell': 'man',
 'Aleksandar Rakic': 'man',
 'Imanol Rodriguez': 'man',
 'SeokHyeon Ko': 'man',
 'Klidson Abreu': 'man',
 'Pedro Rizzo': 'man',
 'Al Iaquinta': 'man',
 'Kamaru Usman': 'man',
 'Sidney Outlaw': 'man',
 'Islam Makhachev': 'man',
 'Cody Gibson': 'man',
 'Eric Shelton': 'man',
 'Hamdy Abdelwahab': 'man',
 'Kris Moutinho': 'man',
 'Randall Wallace': 'man',
 'Tim Sylvia': 'man',
 'Jessica Andrade': 'woman',
 'Khabib Nurmagomedov': 'man',
 'Lerryan Douglas': 'man',
 'Jamahal Hill': 'man',
 'Antonio Rogerio Nogueira': 'man',
 'Alexander Hernandez': 'man',
 'TJ Dillashaw': 'man',
 'Priscila Cachoeira': 'woman',
 'Darren Stewart': 'man',
 'Eryk Anders': 'man',
 'Dooho Choi': 'man',
 'Elias Theodorou': 'man',
 'Jordan Leavitt': 'man',
 'Brandon Royval': 'man',
 'Cory Sandhagen': 'man',
 'HyunSung Park': 'man',
 'Joe Lauzon': 'man',
 'Edson Barboza': 'man',
 'Cynthia Calvillo': 'woman',
 'Polyana Viana': 'woman',
 'Nasrat Haqparast': 'man',
 'Mounir Lazzez': 'man',
 'CJ Vergara': 'man',
 'Charles Oliveira': 'man',
 'Andreas Michailidis': 'man',
 'Dominic Waters': 'man',
 'Yancy Medeiros': 'man',
 'Michal Figlak': 'man',
 'Alex Morono': 'man',
 'Francis Marshall': 'man',
 'Khamzat Chimaev': 'man',
 'Mateusz Rebecki': 'man',
 'Brendson Ribeiro': 'man',
 'Andre Fili': 'man',
 'Tyron Woodley': 'man',
 'Gilbert Urbina': 'man',
 'Li Jingliang': 'man',
 'Brandon Lewis': 'man',
 'Tyson Pedro': 'man',
 'Eduardo Garagorri': 'man',
 'Natalia Silva': 'woman',
 'Baergeng Jieleyisi': 'man',
 'Quang Le': 'man',
 'Nathaniel Wood': 'man',
 'Anthony Perosh': 'man',
 'Darren Till': 'man',
 'Miranda Maverick': 'woman',
 'Charles Byrd': 'man',
 'Jessica Aguilar': 'woman',
 'Ben Askren': 'man',
 'Marlon Moraes': 'man',
 'Gil Castillo': 'man',
 'Trey Waters': 'man',
 'Josh Hokit': 'man',
 'Nate Quarry': 'man',
 'Andrey Pulyaev': 'man',
 'Youssef Zalal': 'man',
 'Joaquim Silva': 'man',
 'Chad Anheliger': 'man',
 'Clayton Carpenter': 'man',
 'Dione Barbosa': 'woman',
 'Talita Alencar': 'woman',
 'Albert Tumenov': 'man',
 'Devonte Smith': 'man',
 'Anthony Hernandez': 'man',
 'Shane Young': 'man',
 'Benoit Saint Denis': 'man',
 'Jack Shore': 'man',
 'Jonathan Martinez': 'man',
 'Glover Teixeira': 'man',
 'Nariman Abbasov': 'man',
 'Julius Walker': 'man',
 'Clint Hester': 'man',
 'Holly Holm': 'woman',
 'Charles Johnson': 'man',
 'Rob Wilkinson': 'man',
 'Juancamilo Ronderos': 'man',
 'Toshiomi Kazama': 'man',
 'Joel Alvarez': 'man',
 'Carlston Harris': 'man',
 'Aaron Pico': 'man',
 'Frankie Edgar': 'man',
 'Ken Shamrock': 'man',
 'Cody Haddon': 'man',
 'Chidi Njokuani': 'man',
 'Jack Della Maddalena': 'man',
 'Bevon Lewis': 'man',
 'Rei Tsuruya': 'man',
 'Mitch Raposo': 'man',
 'Ozzy Diaz': 'man',
 'Top Kiwram': 'man',
 'Dave Menne': 'man',
 'Jacob Silva': 'man',
 'Roosevelt Roberts': 'man',
 'Nikolas\xa0Motta': 'man',
 'Yanis Ghemmouri': 'man',
 'Mauricio Ruffy': 'man',
 'Diego Brandao': 'man',
 'Roxanne Modafferi': 'woman',
 'Shavkat Rakhmonov': 'man',
 'Nick Aguirre': 'man',
 'Johnny Eduardo': 'man',
 'Gerald Meerschaert': 'man',
 'Carlos Prates': 'man',
 'Mike Davis': 'man',
 'Tyson Nam': 'man',
 'Thiago Santos': 'man',
 'Ottman Azaitar': 'man',
 'Diego Sanchez': 'man',
 'Paulo Costa': 'man',
 'Chris Clements': 'man',
 'Jacobe Smith': 'man',
 'Josh Emmett': 'man',
 'Jared Gordon': 'man',
 'Dan Henderson': 'man',
 'Cristiano Marcello': 'man',
 'Marnic Mann': 'woman',
 'Rafa Garcia': 'man',
 'Ryan Spann': 'man',
 'Sara McMann': 'woman',
 'Johny Hendricks': 'man',
 'Pat Healy': 'man',
 'Tresean Gore': 'man',
 'Trevin Jones': 'man',
 'Zubaira Tukhugov': 'man',
 'Lucas Almeida': 'man',
 'Chad Hanekom': 'man',
 'Daniel Marcos': 'man',
 'Kyle Noke': 'man',
 'Cameron Saaiman': 'man',
 'Justin Tafa': 'man',
 'Billy Quarantillo': 'man',
 'Ross Pearson': 'man',
 'Ramazan Emeev': 'man',
 'Rolando Bedoya': 'man',
 'Lukasz Brzeski': 'man',
 'Carlos Candelario': 'man',
 'Jose Aldo': 'man',
 'Kiefer Crosbie': 'man',
 'Ariane Carnelossi': 'woman',
 'Tabatha Ricci': 'woman',
 'Bo Nickal': 'man',
 'Valter Walker': 'man',
 'Norma Dumont': 'woman',
 'Pawel Pawlak': 'man',
 'Daniel Roberts': 'man',
 'Kron Gracie': 'man',
 'Christian Leroy Duncan': 'man',
 'Joshua Van': 'man',
 'Alexander Gustafsson': 'man',
 'Randy Couture': 'man',
 'Magomed Ankalaev': 'man',
 'John Castaneda': 'man',
 'Maki Pitolo': 'man',
 'Zach Reese': 'man',
 'Azamat Murzakanov': 'man',
 'Ricardo Lamas': 'man',
 'Aaron Phillips': 'man',
 'Samuel Sanches': 'man',
 'Thiago Tavares': 'man',
 'Colby Covington': 'man',
 'Leon Edwards': 'man',
 'Cody Stamann': 'man',
 'Mike Brown': 'man',
 'Axel Sola': 'man',
 'Luana Carolina': 'woman',
 'Alistair Overeem': 'man',
 'Raquel Pennington': 'woman',
 'Henry Cejudo': 'man',
 'Aljamain Sterling': 'man',
 'Evan Elder': 'man',
 'Mark Choinski': 'man',
 'Lucas Alexander': 'man',
 'Billy Elekana': 'man',
 'Ariane da Silva': 'woman',
 'Denise Gomes': 'woman',
 'Din Thomas': 'man',
 'Melsik Baghdasaryan': 'man',
 'Igor Severino': 'man',
 'Dan Hooker': 'man',
 'Seth Baczynski': 'man',
 'Jairzinho Rozenstruik': 'man',
 'Damon Jackson': 'man',
 'Scott Jorgensen': 'man',
 'Giga Chikadze': 'man',
 'Amir Albazi': 'man',
 'Aiemann Zahabi': 'man',
 'Rayanne dos Santos': 'woman',
 'Carli Judice': 'woman',
 'Danny Castillo': 'man',
 'Justin Sumter': 'man',
 'Alexia Thainara': 'woman',
 'Dusko Todorovic': 'man',
 'Joe Doerksen': 'man',
 'Jamie Pickett': 'man',
 'Kris McCray': 'man',
 'Andre Petroski': 'man',
 'Dante Rivera': 'man',
 'DooHo Choi': 'man',
 'Sergio Pettis': 'man',
 'Angela Hill': 'woman',
 'Ion Cutelaba': 'man',
 'Daniel Zellhuber': 'man',
 'Guram Kutateladze': 'man',
 'Gabriel Santos': 'man',
 'Viviane Pereira': 'woman',
 'Hector Ramirez': 'man',
 'Nikolas Motta': 'man',
 'Claudia Gadelha': 'woman',
 'Jordan Vucenic': 'man',
 'Marcio Barbosa': 'man',
 'Shonie Carter': 'man',
 'Melissa Mullins': 'woman',
 'Matthew Semelsberger': 'man',
 'Jim Miller': 'man',
 'Belal\xa0Muhammad': 'man',
 'Ateba Gautier': 'man',
 'Niko Price': 'man',
 'Yadier Del Valle': 'man',
 'Ilia Topuria': 'man',
 'John Dodson': 'man',
 'Donovan Beard': 'man',
 'Bryan Caraway': 'man',
 'Dominick Reyes': 'man',
 'Chris Padilla': 'man',
 'Tom Aspinall': 'man',
 'Chris Gutierrez': 'man',
 'Bekzat Almakhan': 'man',
 'Tim Credeur': 'man',
 'Gillian Robertson': 'woman',
 'Victor Hugo': 'man',
 'Stephan Bonnar': 'man',
 'Jon Jones': 'man',
 'Miesha Tate': 'woman',
 'Rafael Natal': 'man',
 'Michel Pereira': 'man',
 'Zac Pauga': 'man',
 'Sam Hughes': 'woman',
 'Yoel Romero': 'man',
 'Jackson McVey': 'man',
 'Kyung Ho Kang': 'man',
 'Michael Aswell': 'man',
 'Mike Breeden': 'man',
 'Gilbert Melendez': 'man',
 'Jack Cartwright': 'man',
 'Drako Rodriguez': 'man',
 'Ange Loosa': 'man',
 'Karolina Kowalkiewicz': 'woman',
 'Benson Henderson': 'man',
 'Santiago Ponzinibbio': 'man',
 'Jamey Lyn Horth': 'woman',
 'Carlos Condit': 'man',
 'Vince Morales': 'man',
 'Marvin Vettori': 'man',
 'Marc Diakiese': 'man',
 'Kenny Florian': 'man',
 'Taila Santos': 'woman',
 'Rose Namajunas': 'woman',
 'Chris Duncan': 'man',
 'Diego Ferreira': 'man',
 'Mason Jones': 'man',
 'Tony Ferguson': 'man',
 'Montserrat Rendon': 'woman',
 'Klaudia Sygula': 'woman',
 'Kyle Nelson': 'man',
 'Kyle Daukaus': 'man',
 'Urijah Faber': 'man',
 'Serghei Spivac': 'man',
 'Alice Pereira': 'woman',
 'Steve Garcia': 'man',
 'Jessica Penne': 'woman',
 'Isaac Dulgarian': 'man',
 'Jeremiah Wells': 'man',
 'Cody Durden': 'man',
 'Askar Askarov': 'man',
 'Chepe Mariscal': 'man',
 'SeungGuk Choi': 'man',
 'Sean Sharaf': 'man',
 'Denis Tiuliulin': 'man',
 'Anthony Smith': 'man',
 'Cris Cyborg': 'woman',
 'Junyong Park': 'man',
 'David Onama': 'man',
 'Jasmine Jasudavicius': 'woman',
 'Stipe Miocic': 'man',
 'Mohammed Usman': 'man',
 'Conor McGregor': 'man',
 'Ian Freeman': 'man',
 'Nikita Krylov': 'man',
 'Yazmin Jauregui': 'woman',
 'Yi Zha': 'man',
 'Matheus Nicolau': 'man',
 'Takanori Gomi': 'man',
 'Nathan Fletcher': 'man',
 'Macy Chiasson': 'woman',
 'Viacheslav Borshchev': 'man',
 'Kate Jackson': 'woman',
 'Matt Sayles': 'man',
 'Alan Jouban': 'man',
 'Christos Giagos': 'man',
 'Alessandro Costa': 'man',
 'Loma Lookboonmee': 'woman',
 'Mario Pinto': 'man',
 'Cezary Oleksiejczuk': 'man',
 'Jean\xa0Silva': 'man',
 'Brian Bowles': 'man',
 'Rafael Dos Anjos': 'man',
 'Paul Felder': 'man',
 'Vinicius Cenci': 'man',
 'Manuel Torres': 'man',
 'Tecia Torres': 'woman',
 'Robert Bryczek': 'man',
 'Bruno Silva': 'man',
 'Tim Means': 'man',
 'Belal Muhammad': 'man',
 'Mandel Nallo': 'man',
 'Petr Yan': 'man',
 'Adrian Yanez': 'man',
 'Gregory Rodrigues\n': 'man',
 'Sodiq Yusuff': 'man',
 'Montel Jackson': 'man',
 'Matt Serra': 'man',
 'Adam Fugitt': 'man',
 'Jimmy Crute': 'man',
 'Drew Dober': 'man',
 'Brad Riddell': 'man',
 'Brian Ortega': 'man',
 'Kay Hansen': 'woman',
 'Joshua\xa0Van': 'man',
 'Joanna Jedrzejczyk': 'woman',
 'Herbert Burns': 'man',
 'Rodolfo Vieira': 'man',
 'Dustin Ortiz': 'man',
 'Dominick Cruz': 'man',
 'Myron Dennis': 'man',
 'Steve Erceg': 'man',
 'Sam Alvey': 'man',
 'Loik Radzhabov': 'man',
 'Ramazan Temirov': 'man',
 'Antonio Carlos Junior': 'man',
 'Mark Coleman': 'man',
 'Edmen Shahbazyan': 'man',
 'Viviane Araujo': 'woman',
 'Jarno Errens': 'man',
 'Jacare Souza': 'man',
 'Alex Perez': 'man',
 'Luis Gurule': 'man',
 'Matt Schnell': 'man',
 'Luke Rockhold': 'man',
 'Alexandre Pantoja': 'man',
 'Marcin Prachnio': 'man',
 'Donte Johnson': 'man',
 'Ibo Aslan': 'man',
 'Zhang Weili': 'woman',
 'Orion Cosce': 'man',
 'Cristian Quinonez': 'man',
 'Amanda Nunes': 'woman',
 'Daniel Barez': 'man',
 'Danny Barlow': 'man',
 'Tom Nolan': 'man',
 'Alex Reyes': 'man',
 'Joselyne Edwards': 'woman',
 'Sheldon Westcott': 'man',
 'Forrest Griffin': 'man',
 'Shane Burgos': 'man',
 'Makhmud Muradov': 'man',
 'Jose Johnson': 'man',
 'Sarah Kaufman': 'woman',
 'Cesar Almeida': 'man',
 'Charles Jourdain': 'man',
 'Diego\xa0Lopes': 'man',
 'Karine Silva': 'woman',
 'Anderson Silva': 'man',
 'Marina Rodriguez': 'woman',
 'Josh Parisian': 'man',
 'Omari Akhmedov': 'man',
 'Gregory Rodrigues': 'man',
 'Don Shainis': 'man',
 'Jessica Eye': 'woman',
 'AJ Dobson': 'man',
 'Neil Magny': 'man',
 'Julianna Pena': 'woman',
 'Jussier Formiga': 'man',
 'Tracy Cortez': 'woman',
 'Nina Nunes': 'woman',
 'Zhang Mingyang': 'man',
 'Augusto Sakai': 'man',
 'Taiyilake Nueraji': 'man',
 'Mirko Cro Cop': 'man',
 'Marion Reneau': 'woman',
 'Charles Oliveira\n': 'man',
 'TJ Brown': 'man',
 'Tainara Lisboa': 'woman',
 'Kyoji Horiguchi': 'man',
 'Alex Oliveira': 'man',
 'Bobby Green': 'man',
 'Mark Kerr': 'man',
 'Nicolas Dalby': 'man',
 'Azat Maksum': 'man',
 'Vitor Belfort': 'man',
 'Ernesta Kareckaite': 'woman',
 'Eric Nolan': 'man',
 'Jimmie Rivera': 'man',
 'Cody Brundage': 'man',
 'Oban Elliott': 'man',
 'Kody Steele': 'man',
 'Dan Hardy': 'man',
 'Vicente Luque': 'man',
 'JunYong Park': 'man',
 'Carlos Newton': 'man',
 'Claudio Silva': 'man',
 'Robbie Lawler': 'man',
 'Tim Elliott': 'man',
 'Alice Ardelean': 'woman',
 'Mike Guymon': 'man',
 'Darren Elkins': 'man',
 'Chris Birchler': 'man',
 'Joanderson Brito': 'man',
 'Phil de Fries': 'man',
 'Colby Thicknesse': 'man',
 'Ciryl Gane': 'man',
 'Johnny Walker': 'man',
 'Warlley Alves': 'man',
 'Daniel Cormier': 'man',
 'Robert Ruchala': 'man',
 'Ante Delija': 'man',
 'Chase Hooper': 'man',
 'Yana Santos': 'woman',
 'Mackenzie Dern': 'woman',
 'Rory MacDonald': 'man',
 'Benardo Sopaj': 'man',
 'Ray Sefo': 'man',
 'Pedro Munhoz': 'man',
 'Mateus Mendonca': 'man',
 'Terrance McKinney': 'man',
 'Alvin Hines': 'man',
 'Phil Hawes': 'man',
 'Rodrigo Nascimento': 'man',
 'Lyoto Machida': 'man',
 'Ricky Simon': 'man',
 'Jailton Almeida': 'man',
 'Kyler Phillips': 'man',
 'Tatsuro Taira': 'man',
 'Caio Borralho\n': 'man',
 'Payton Talbott': 'man',
 'Mark Weir': 'man',
 'Jan Blachowicz': 'man',
 'Nyamjargal Tumendemberel': 'man',
 'Torrez Finney': 'man',
 'Shauna Bannon': 'woman',
 'Zach Makovsky': 'man',
 'Keith Jardine': 'man',
 'Brad Katona': 'man',
 'Andre Lima': 'man',
 'Jalin Turner': 'man',
 'Tito Ortiz': 'man',
 'Devin Powell': 'man',
 'Steven Nguyen': 'man',
 'Nik Lentz': 'man',
 'Taylor Moore': 'man',
 'Zabit Magomedsharipov': 'man',
 'Dequan Townsend': 'man',
 'Devin Clark': 'man',
 'Jeremy Stephens': 'man',
 'Arman Tsarukyan': 'man',
 'Hitomi Akano': 'man',
 'Natan Levy': 'man',
 'Sean Woodson': 'man',
 'Julian Erosa': 'man',
 'Victor Henry': 'man',
 'Alexa Grasso': 'woman',
 'Maycee Barber': 'woman',
 'Jamall Emmers': 'man',
 'Mike Malott': 'man',
 'Miles Johns': 'man',
 'Cory McKenna': 'woman',
 'Daron Cruickshank': 'man',
 'Kennedy Nzechukwu': 'man',
 'Rani Yahya': 'man',
 'Manoel Sousa': 'man',
 'Cameron Smotherman': 'man',
 'Kanako Murata': 'woman',
 'Vladimir Matyushenko': 'man',
 'Alexander Volkov': 'man',
 'Ricardo Arona': 'man',
 'Diego Nunes': 'man',
 'Ryan Loder': 'man',
 'Ronda Rousey': 'woman',
 'Brandon Davis': 'man',
 'Daniel Rodriguez': 'man',
 'Luana Pinheiro': 'woman',
 'Trevor Peek': 'man',
 'Luigi Vendramini': 'man',
 'Jacqueline Cavalcanti': 'woman',
 'Dalcha Lungiambula': 'man',
 'Jake Shields': 'man',
 'John Phillips': 'man',
 'Joseph Morales': 'man',
 'Matt Bessette': 'man',
 'Ian McCall': 'man',
 'Marcin Tybura': 'man',
 'Issa Isakov': 'man',
 'Jaqueline Amorim': 'woman',
 'Nick Diaz': 'man',
 'Elise Reed': 'woman',
 'Evan Dunham': 'man',
 'Stephanie Egger': 'woman',
 'Josefine Knutsson': 'woman',
 'Loopy Godinez': 'woman',
 'Spencer Fisher': 'man',
 'Roger Huerta': 'man',
 'Shohei Nose': 'man',
 'David Dvorak': 'man',
 'Luis Saldana': 'man',
 'Amanda Cooper': 'woman',
 'Claudio Puelles': 'man',
 'Landon Quinones': 'man',
 'Jason Brilz': 'man',
 'Jamie Varner': 'man',
 'Movsar Evloev': 'man',
 'Lucas Martins': 'man',
 'Julio Arce': 'man',
 'Hunter Azure': 'man',
 'Pat Sabatini': 'man',
 'Patricio Freire': 'man',
 'Julija Stoliarenko': 'woman',
 'Rafael Fiziev': 'man',
 'JeongYeong Lee': 'man',
 'Valentina Shevchenko': 'woman',
 'Emily Ducote': 'woman',
 'Bryce Mitchell': 'man',
 'Steven Asplund': 'man',
 'Kazushi Sakuraba': 'man',
 'Zak Cummings': 'man',
 'Mitch Ramirez': 'man',
 'Denys Bondar': 'man',
 'Jonathan Micallef': 'man',
 'Makwan Amirkhani': 'man',
 'Alan Patrick': 'man',
 'Calvin Kattar': 'man',
 'Nate Landwehr': 'man',
 'Grant Dawson': 'man',
 'Nazim\xa0Sadykhov': 'man',
 'Jose Ochoa': 'man',
 'Drakkar Klose': 'man',
 'Azamat Bekoev': 'man',
 'Jesus Aguilar': 'man',
 'Vinicius Oliveira': 'man',
 'Victoria Leonardo': 'woman',
 'Rizvan Kuniev': 'man',
 'Brad Pickett': 'man',
 'Edivan Santos': 'man',
 'Alex Caceres': 'man',
 'Rafael Cerqueira': 'man',
 'Islam Dulatov': 'man',
 'Manon Fiorot': 'woman',
 'Manny Gamburyan': 'man',
 'Kamuela Kirk': 'man',
 'Jack\xa0Della Maddalena': 'man',
 'Craig Jones': 'man',
 'Gabriel Benitez': 'man',
 'Tony Gravely': 'man',
 'Cain Velasquez': 'man',
 'Jeong Yeong Lee': 'man',
 'Diego Lopes': 'man',
 'Julia Avila': 'woman',
 'Muin Gafurov': 'man',
 'Kurt Holobaugh': 'man',
 'Anton Turkalj': 'man',
 'Nate Diaz': 'man',
 'Mike Lullo': 'man',
 'Armen Petrosyan': 'man',
 'Dricus du Plessis': 'man',
 'Karol Rosa': 'woman',
 'Kevin Randleman': 'man',
 'Abdul Razak Alhassan': 'man',
 'Kevin Holland': 'man',
 'Frank Mir': 'man',
 'Valerie Letourneau': 'woman',
 'Billy Goff': 'man',
 'Bogdan Guskov': 'man',
 'Lerone Murphy': 'man',
 'Glaico Franca': 'man',
 'Jimmy Flick': 'man',
 'Gaston Bolanos': 'man',
 'Josiah Harrell': 'man',
 'Ahmad Hassanzada': 'man',
 'Journey Newson': 'man',
 'Charles Radtke': 'man',
 'Marcus McGhee': 'man',
 'Tallison Teixeira': 'man',
 'Jason Knight': 'man',
 'Austin Hubbard': 'man',
 'Nasrudin Nasrudinov': 'man',
 'Steven Peterson': 'man',
 'Sergei Pavlovich': 'man',
 'Alex Pereira': 'man',
 'Renato Moicano': 'man',
 'Demian Maia': 'man',
 'Rodolfo Bellato': 'man',
 'Erick Silva': 'man',
 'Santiago Luna': 'man',
 'Dakota Bush': 'man',
 'Bec Rawlings': 'woman',
 'Kaue Fernandes': 'man',
 'Danny Roberts': 'man',
 'Murtaza Talha': 'man',
 'Ismail Naurdiev': 'man',
 'Vanessa Demopoulos': 'woman',
 'Luis Pena': 'man',
 'Geoff Neal': 'man',
 'Markus Perez': 'man',
 'Brad Tavares': 'man',
 'Bruno Lopes': 'man',
 'Ismael Bonfim': 'man',
 'Marcelo Rojo': 'man',
 'Tofiq Musayev': 'man',
 'Soa Palelei': 'man',
 'Andreas Gustafsson': 'man',
 'Joe Pyfer': 'man',
 'Sean Soriano': 'man',
 'Ryan Gandra': 'man',
 'Caio Borralho': 'man',
 'Shamil Gaziev': 'man',
 'Shane Campbell': 'man',
 'Jennifer Maia': 'woman',
 'Preston Parsons': 'man',
 'Daniil Donchenko': 'man',
 'Andre Ewell': 'man',
 'Will Santiago': 'man',
 'Merab Dvalishvili': 'man',
 'Felice Herrig': 'woman',
 'Shunichi Shimizu': 'man',
 'Neil Seery': 'man',
 'Lina Lansberg': 'woman',
 'Ivana Petrovic': 'woman',
 'Bruna Brasil': 'woman',
 'Michael Chiesa': 'man',
 'Fernando Padilla': 'man',
 'Eric McConico': 'man',
 'Jorge Masvidal': 'man',
 'Kaan Ofli': 'man',
 'Will Chope': 'man',
 'Kaynan Kruschewsky': 'man',
 'Dylan Budka': 'man',
 'Saimon Oliveira': 'man',
 'Dricus Du Plessis': 'man',
 'Jean Silva': 'man',
 'BJ Penn': 'man',
 'Andre Muniz': 'man',
 'Song Yadong': 'man',
 'Impa Kasanganay': 'man',
 'Juan Espino': 'man',
 'Raulian Paiva': 'man',
 'Michael Morales\n': 'man',
 'Stephen Thompson': 'man',
 'Mateusz Gamrot': 'man',
 'Matheus Camilo': 'man',
 'Felipe Lima': 'man',
 'Emiliano Sordi': 'man',
 'Zachary Borrego': 'man',
 'Alex Chambers': 'woman',
 'Ailin Perez': 'woman',
 'Matt Hughes': 'man',
 'Brian Kelleher': 'man',
 'Francisco Trinaldo': 'man',
 'Rich Franklin': 'man',
 'Manolo Zecchini': 'man',
 'Jack Jenkins': 'man',
 'Hugo Cunha': 'man',
 'Cameron Rowston': 'man',
 'Paul Craig': 'man',
 'Eduardo Neves': 'man',
 'Jhonata Diniz': 'man',
 'Austin Bashi': 'man',
 'Pete Rodriguez': 'man',
 'Shayilan Nuerdanbieke': 'man',
 'Jose Daniel Medina': 'man',
 'Farid Basharat': 'man',
 'Victor Martinez': 'man',
 'Shannon Ross': 'man',
 'JJ Aldrich': 'woman',
 'Johnny Case': 'man',
 'Dustin Poirier': 'man',
 'Will Brooks': 'man',
 'Val Woodburn': 'man',
 'John Moraga': 'man',
 'Shayna Baszler': 'woman',
 'Paige VanZant': 'woman',
 'Chelsea Chandler': 'woman',
 'Jorge Rivera': 'man',
 'Donald Cerrone': 'man',
 'Jeka Saragih': 'man',
 'Daniel Pineda': 'man',
 'Anthony Njokuani': 'man',
 'Chris Curtis': 'man',
 'Antonio Trocoli': 'man',
 'Shauna\xa0Bannon': 'woman',
 'Michael Bisping': 'man',
 'Taylor Lapilus': 'man',
 'Bubba McDaniel': 'man',
 'Yushin Okami': 'man',
 'Ketlen Souza': 'woman',
 'Mashrabjon Ruzibaev': 'man',
 'Andrea Lee': 'woman',
 'Irene Aldana': 'woman',
 'Alexander Volkanovski': 'man',
 'Fernie Garcia': 'man',
 'Pablo Garza': 'man',
 'Josh Fremd': 'man',
 'AJ Cunningham': 'man',
 'Felipe Dos Santos': 'man',
 'Muhammad Naimov': 'man',
 'Sedriques Dumas': 'man',
 'Liang Na': 'woman',
 'Kaik Brito': 'man',
 'Demetrious Johnson': 'man',
 'Yair Rodriguez': 'man',
 'Ian Loveland': 'man',
 'Nick Klein': 'man',
 'Max Griffin': 'man',
 'Da Woon Jung': 'man',
 'Raphael Assuncao': 'man',
 'Luana Santos': 'woman',
 'Song Kenan': 'man',
 'Ryan Jensen': 'man',
 'Michael Morales': 'man',
 'Teruto Ishihara': 'man',
 'Clay Guida': 'man',
 'Joe Solecki': 'man',
 'Timur Valiev': 'man',

In [17]:
def get_coreference_genders(row: pd.Series):
    doc: Doc = row["doc"]

    chains: ChainHolder = doc._.coref_chains
    
    def loop():
        for chain in chains:
            main_item_mention = chain[chain.most_specific_mention_index]
            main_item = doc[main_item_mention.root_index]
            
            if main_item.text in genders_map:
                for mention in chain:
                    token = doc[mention.root_index]
                    yield (token, genders_map[main_item.text])
    
    return list(loop())

In [18]:
df["coreference_genders"] = df.apply(get_coreference_genders, axis="columns")

In [19]:
def get_people_with_gender(row: pd.Series, gender: str):
    doc: Doc = row["doc"]
    people: list[Span] = row["people"]
    coreference_genders: list[tuple[Token, str]] = row["coreference_genders"]

    people_with_gender = [p for p in people if genders_map.get(p.text) == gender]
    coreferences_with_gender = [p for p, g in coreference_genders if g == gender]
    coreferences_with_gender = [Span(doc, p.i, p.i + 1) for p in coreferences_with_gender]
    
    return set(people_with_gender + coreferences_with_gender)

In [20]:
df["men"] = df.apply(get_people_with_gender, args=("man",), axis="columns")
df["women"] = df.apply(get_people_with_gender, args=("woman",), axis="columns")

In [21]:
def get_paragraph_boundaries(doc: Doc):
    line_breaks = [token for token in doc if token.text == "\n"]
    line_break_indexes = [lb.i for lb in line_breaks]
    paragraph_boundaries = list(zip([0] + line_break_indexes, line_break_indexes + [len(doc)]))
    return paragraph_boundaries

In [22]:
df["paragraph_boundaries"] = df["doc"].apply(get_paragraph_boundaries)

In [23]:
def count_genders_in_paragraphs(row: pd.Series, gender: str):
    people_with_gender: set[Span] = row[gender]
    paragraph_boundaries: list[tuple[int, int]] = row["paragraph_boundaries"]

    def count_gender_in_paragraph(boundary: tuple[int, int]):
        start, end = boundary
        count = 0

        for person in people_with_gender:
            if person.end >= end:
                continue
            elif person.start < start:
                continue
            
            count += 1

        return count

    return [count_gender_in_paragraph(boundary) for boundary in paragraph_boundaries]

In [24]:
df["men_per_paragraph"] = df.apply(count_genders_in_paragraphs, args=("men",), axis="columns")
df["women_per_paragraph"] = df.apply(count_genders_in_paragraphs, args=("women",), axis="columns")

In [25]:
def assign_gender_to_paragraphs(row: pd.Series):
    men_per_paragraph: list[int] = row["men_per_paragraph"]
    women_per_paragraph: list[int] = row["women_per_paragraph"]

    def choose_gender(m: int, f: int):
        if m == 0 and f == 0:
            return None
        elif m > f:
            return "man"
        elif f > m:
            return "woman"
        else: 
            return "equal"

    return [choose_gender(m, f) for m, f in zip(men_per_paragraph, women_per_paragraph)]

In [26]:
df["paragraph_genders"] = df.apply(assign_gender_to_paragraphs, axis="columns")

In [27]:
def get_paragraphs_with_gender(row: pd.Series, gender: str):
    doc: Doc = row["doc"]
    paragraph_boundaries: list[tuple[int, int]] = row["paragraph_boundaries"]
    paragraph_genders: list[str | None] = row["paragraph_genders"]

    paragraphs_indexes_with_gender = [i for i, g in enumerate(paragraph_genders) if g == gender]
    paragraphs_boundaries_with_gender = [paragraph_boundaries[i] for i in paragraphs_indexes_with_gender]
    paragraphs_with_gender = [doc[start:end] for start, end in paragraphs_boundaries_with_gender]

    return paragraphs_with_gender

In [28]:
df["man_paragraphs"] = df.apply(get_paragraphs_with_gender, args=("man",), axis="columns")
df["woman_paragraphs"] = df.apply(get_paragraphs_with_gender, args=("woman",), axis="columns")
df["equal_paragraphs"] = df.apply(get_paragraphs_with_gender, args=("equal",), axis="columns")
df["genderless_paragraphs"] = df.apply(get_paragraphs_with_gender, args=(None,), axis="columns")

In [29]:
df

,file,text,doc,people,coreference_genders,men,women,paragraph_boundaries,men_per_paragraph,women_per_paragraph,paragraph_genders,man_paragraphs,woman_paragraphs,equal_paragraphs,genderless_paragraphs
0,news_10-june-schedule-jam-packed-goodness.txt,"Buckle up, kids, because the June schedule is ...","(Buckle, up, ,, kids, ,, because, the, June, s...","[(Mario, Bautista), (Bautista), (Ricky, Simon)...","[(Bautista, man), (Bautista, man), (him, man),...","{(Kyoji, Horiguchi), (his), (Dvalishvili), (hi...","{(Erin, Blanchfield), (her), (Vieira), (Kayla,...","[(0, 14), (14, 94), (94, 164), (164, 174), (17...","[0, 0, 0, 0, 0, 2, 8, 3, 3, 0, 0, 6, 0, 1, 2, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 9, 3, 0, ...","[None, None, None, None, None, man, man, man, ...","[(\n, A, couple, fights, before, the, bantamwe...","[(\n, Julianna, Peña, seeks, to, successfully,...",[],"[(Buckle, up, ,, kids, ,, because, the, June, ..."
1,news_10-massive-fights-schedule-may.txt,There are all kinds of different ways to look ...,"(There, are, all, kinds, of, different, ways, ...","[(Bo, Nickal), (Gerald, Meerschaert), (Kevin, ...","[(Holland, man), (his, man), (he, man), (Nicka...","{(Sean, Brady), (He), (Zahabi), (his), (Michae...","{(Yan), (She), (Andrade), (his), (Shevchenko),...","[(0, 41), (41, 78), (78, 133), (133, 172), (17...","[0, 0, 0, 0, 0, 0, 1, 5, 2, 1, 4, 12, 9, 4, 0,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 4, ...","[None, None, None, None, None, None, man, man,...","[(\n, While, both, Reinier, de, Ridder, and, B...","[(\n, Jessica, Andrade, and, Jasmine, Jasudavi...",[],"[(There, are, all, kinds, of, different, ways,..."
2,news_10-memorable-moments-down-under.txt,"On Saturday, February 8, the UFC returns to Qu...","(On, Saturday, ,, February, 8, ,, the, UFC, re...","[(Alexander, Volkanovski), (Adesanya), (Dan, H...","[(Weili, woman), (her, woman), (Velasquez, man...","{(Johnson), (Hunt), (Chris, Clements), (Noguei...","{(Marion, Reneau), (Tatiana, Suarez), (she), (...","[(0, 30), (30, 67), (67, 159), (159, 220), (22...","[0, 0, 4, 2, 4, 7, 5, 7, 13, 9, 5, 0, 4, 4, 2,...","[0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, ...","[None, None, man, woman, man, man, man, man, m...","[(\n, Over, the, years, ,, the, stops, in, Syd...","[(\n, As, we, ready, to, see, Zhang, Weili, de...",[],"[(On, Saturday, ,, February, 8, ,, the, UFC, r..."
3,news_10-middleweights-biggest-championship-mom...,Fourteen individuals have held the UFC middlew...,"(Fourteen, individuals, have, held, the, UFC, ...","[(Dave, Menne), (Gil, Castillo), (Dricus, Du, ...","[(Franklin, man), (Franklin, man), (Quarry, ma...","{(Adesanya), (Quarry), (Adesanya), (Anderson, ...","{(Silva), (Silva), (Silva), (his), (he), (Silv...","[(0, 67), (67, 118), (118, 166), (166, 181), (...","[4, 0, 0, 3, 0, 4, 7, 2, 7, 3, 0, 3, 1, 7, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 3, 2, ...","[man, None, None, man, None, man, man, man, ma...","[(Fourteen, individuals, have, held, the, UFC,...","[(\n, It, ’s, weird, to, try, to, think, back,...","[(\n, Anderson, Silva, defeats, Chael, Sonnen,...","[(\n, While, it, never, profiled, as, the, gla..."
4,news_10-most-memorable-ufc-moments-canada.txt,As we continue our Canadian-focused march thro...,"(As, we, continue, our, Canadian, -, focused, ...","[(Matt, Serra), (Serra), (Liddell), (Tito, Ort...","[(Serra, man), (Serra, man), (his, man), (He, ...","{(Liddell), (Franklin), (men), (Liddell), (Fra...","{(her), (Irene, Aldana), (Nina), (she), (Nunes...","[(0, 47), (47, 67), (67, 115), (115, 144), (14...","[0, 0, 0, 0, 0, 2, 0, 4, 7, 10, 5, 6, 2, 0, 0,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, None, None, None, None, man, None, man,...","[(\n, UFC, 83, marked, the, promotion, ’s, fir...","[(\n, When, I, spoke, with, Nunes, a, couple, ...",[],"[(As, we, continue, our, Canadian, -, focused,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,news_zhang-mingyang-all-gas-no-brakes-ufc-kans...,Rising Chinese star Zhang Mingyang has a stat ...,"(Rising, Chinese, star, Zhang, Mingyang, has, ...","[(Zhang, Mingyang), (Zhang), (Zhang), (Dana, W...","[(Mingyang, man), (he, man), (he, man), (his, ...","{(Anthony, Smith), (Smith), (Anthony, Smith), ...","{(he), (Zhang), (Zhang), (Zhang), (his), (Zhan...","[(0, 25), (25, 55), (55, 107), (107, 167), (16...","[2, 1, 0, 1, 2, 0, 0, 4, 0, 5, 1, 4, 0]","[0, 0, 1, 0, 5, 2, 0, 2, 0, 10, 2, 2, 4]","[man, man, woman, man, woman, woman, None, man...","[(Rising, Chinese, star, Zhang, Mingyang, has,...","[(\n, Zhang, has, competed, in, the, Octagon, ...",[],"[(\n, “, Two, wins, in, the, UFC, ,, two, Perf..."
725,news_zhang-mingyang-embracing-spotlight-ufc-sh...,Zhang Mingyang has all the makings of a potent...,"(Zhang, Mingyang, has, all, the, makings, of, ...","[(Zhang, Mingyang), (Brendson, Ribeiro), (Ozzy...","[(his, woman), (Zhang, woman), (himself, woman...","{(Smith), (Walker), (Brendson, Ribeiro), (Walk...","{(Zhang), (Zhang), (himself), (his), (he), (Zh...","[(0, 11), (11, 110), (110, 129), (129, 133), (...","[1, 3, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0]","[0, 0, 0, 0, 1, 6, 3, 1, 3, 6, 5, 0, 0]","[man, man, None, None, woman, woman, woman, wo...","[(Zhang, Mingyang, has, all, the, makings, of,...","[(\n, “, I, ’m, very, happy, to, see, myself, ...",[],"[(\n, And, yes, ,, that, means, all, of, his, ..."
726,news_zhang-mingyang-journey-main-event-light-h...,Zhang Mingyang first entered the UFC ecosystem...,"(Zhang, Mingyang, first, entered, the, UFC, ec...","[(Zhang, Mingyang), (Tuko, Tokkos), (Zhang), (...","[(Mingyang, man), (he, man), (Tokkos, man), (T...","{(Tokkos), (his), (Diaz), (Johnny, Walker), (W...","{(Zhang), (Zhang), (Zhang), (his), (Zhang), (h...","[(0, 65), (65, 180), (180, 301), (301, 404), (...","[5, 1, 1, 4, 4, 8, 5, 2]","[2, 9, 9, 5, 8, 5, 6, 3]","[man, woman, woman, woman, woman, man, woman, ...","[(Zhang, Mingyang, first, entered, the, UFC, e...","[(\n, Following, that, fight, ,, Zhang, worked...",[],[]
727,news_zhang-weili-builds-her-case-goat-status.txt,,(),[],[],{},{},"[(0, 0)]",[0],[0],[None],[],[],[],[()]
728,news_zhang-weili-built-different-ufc-312.txt,If you ever wondered what separates the all-ti...,"(If, you, ever, wondered, what, separates, the...","[(Zhang, Weili), (Tatiana, Suarez), (Zhang), (...","[(Weili, woman), (her, woman), (her, woman), (...",{},"{(her), (her), (Zhang, Weili), (she), (Zhang),...","[(0, 39), (39, 97), (97, 161), (161, 224), (22...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 5, 2, 3, 1, 10, 6, 2, 5, 4, 17, 4, 7, 9...","[None, None, woman, woman, woman, woman, woman...",[],"[(\n, That, ’s, the, way, strawweight, champio...",[],"[(If, you, ever, wondered, what, separates, th..."

In [ ]:
def save_separate_paragraphs(row: pd.Series):
    original_file: str = row["file"]
    new_folder = original_file.replace(".txt", "")

    os.makedirs(f"./articles/{new_folder}", exist_ok=True)

    man_paragraphs: list[Span] = row["man_paragraphs"]
    man_text = "\n".join([p.text for p in man_paragraphs])

    with open(f"./articles/{new_folder}/man.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(man_text)

    woman_paragraphs: list[Span] = row["woman_paragraphs"]
    woman_text = "\n".join([p.text for p in woman_paragraphs])

    with open(f"./articles/{new_folder}/woman.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(woman_text)

    equal_paragraphs: list[Span] = row["equal_paragraphs"]
    equal_text = "\n".join([p.text for p in equal_paragraphs])

    with open(f"./articles/{new_folder}/equal.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(equal_text)

    genderless_paragraphs: list[Span] = row["genderless_paragraphs"]
    genderless_text = "\n".join([p.text for p in genderless_paragraphs])

    with open(f"./articles/{new_folder}/genderless.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(genderless_text)

In [31]:
df.apply(save_separate_paragraphs, axis="columns")

0      None
1      None
2      None
3      None
4      None
       ...
724    None
725    None
726    None
727    None
728    None
Length: 729, dtype: object