In [26]:
import os
import re
from datetime import datetime
from itertools import chain
from concurrent.futures import ThreadPoolExecutor
import pandas as pd
import spacy
from spacy.tokens.doc import Doc
from spacy.tokens.span import Span
from spacy.tokens.token import Token
import coreferee
from coreferee.data_model import ChainHolder, Chain
from helpers import get_request
from bs4 import BeautifulSoup
from bs4.element import Tag

In [2]:
nlp = spacy.load("en_core_web_lg")
nlp.add_pipe("coreferee")

c:\Users\Adam\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages\spacy\util.py:969: UserWarning: [W095] Model 'en_core_web_lg' (3.5.0) was trained with spaCy v3.5.0 and may not be 100% compatible with the current version (3.8.8). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

In [3]:
def get_text_from_file(path: str):
    text = ""
    
    try:
        with open(path, "r", encoding="utf8") as file:
            text = file.read()
    except Exception as e:
        print("Error reading file", path)
        print(e)
    finally:
        return text

In [4]:
articles_folder = "./articles"

In [5]:
article_files = os.listdir(articles_folder)
article_files = [file for file in article_files if file.endswith(".txt")]

In [6]:
texts = [get_text_from_file(f"{articles_folder}/{file}") for file in article_files]

df = pd.DataFrame(data={
    "file": article_files,
    "text": texts
})
df

,file,text
0,news_10-get-ready-for-a-november-to-remember-i...,"November is stacked. Normally, I would look to..."
1,news_10-june-schedule-jam-packed-goodness.txt,"Buckle up, kids, because the June schedule is ..."
2,news_10-massive-fights-schedule-may.txt,There are all kinds of different ways to look ...
3,news_10-memorable-moments-down-under.txt,"On Saturday, February 8, the UFC returns to Qu..."
4,news_10-middleweights-biggest-championship-mom...,Fourteen individuals have held the UFC middlew...
...,...,...
876,news_zhang-mingyang-embracing-spotlight-ufc-sh...,Zhang Mingyang has all the makings of a potent...
877,news_zhang-mingyang-journey-main-event-light-h...,Zhang Mingyang first entered the UFC ecosystem...
878,news_zhang-weili-big-challenge-apple-vechain-u...,Zhang Weili knows all bout fighting in UFC tit...
879,news_zhang-weili-builds-her-case-goat-status.txt,
880,news_zhang-weili-built-different-ufc-312.txt,If you ever wondered what separates the all-ti...

In [7]:
def already_split_gender_paragraphs(article_file: str):
    gender_paragraphs_folder = f"{articles_folder}/{article_file.replace('.txt', '')}"
    return os.path.exists(gender_paragraphs_folder)

In [ ]:
# Since this part of the pipeline is very resource intensive, 
# we only want to run it on articles that haven't already been split on gender.
# However, you can set this variable to True if you still want to run on everything.
run_on_all_files = False

if run_on_all_files:
    df_to_separate = df
else:
    df_to_separate = df[~df["file"].apply(already_split_gender_paragraphs)].copy()

df_to_separate

,file,text
0,news_10-get-ready-for-a-november-to-remember-i...,"November is stacked. Normally, I would look to..."
1,news_10-june-schedule-jam-packed-goodness.txt,"Buckle up, kids, because the June schedule is ..."
2,news_10-massive-fights-schedule-may.txt,There are all kinds of different ways to look ...
3,news_10-memorable-moments-down-under.txt,"On Saturday, February 8, the UFC returns to Qu..."
4,news_10-middleweights-biggest-championship-mom...,Fourteen individuals have held the UFC middlew...
...,...,...
876,news_zhang-mingyang-embracing-spotlight-ufc-sh...,Zhang Mingyang has all the makings of a potent...
877,news_zhang-mingyang-journey-main-event-light-h...,Zhang Mingyang first entered the UFC ecosystem...
878,news_zhang-weili-big-challenge-apple-vechain-u...,Zhang Weili knows all bout fighting in UFC tit...
879,news_zhang-weili-builds-her-case-goat-status.txt,
880,news_zhang-weili-built-different-ufc-312.txt,If you ever wondered what separates the all-ti...

In [9]:
# This takes a long time, so have patience
df_to_separate["doc"] = list(nlp.pipe(df_to_separate["text"]))

In [10]:
def get_people(doc: Doc):
    return [ent for ent in doc.ents if ent.label_ == "PERSON"]

In [11]:
df_to_separate["people"] = df_to_separate["doc"].apply(get_people)

In [12]:
all_people: list[Span] = list(chain.from_iterable(df_to_separate["people"]))
all_names = set(p.text for p in all_people)
full_names = set(name for name in all_names 
                 if 
                 len(name.split()) >= 2 
                 and len(name.split()) <= 3
                 and re.search("^[a-zA-Z\u00C0-\u017F\s’]+$", name) is not None)

full_names

{'Matt Frevola',
 'Jose Aldo',
 'Maurice Greene',
 'Curtis Millender',
 'Antonio Rogerio Nogueira',
 'Arman Tsarukyan',
 'Nathan Diaz',
 'Sam Greco',
 'Luis Pena',
 'Oban Elliott',
 'Chihiro Suzuki',
 'Edson Barboza',
 'Will Santiago',
 'Antonio Carlos Junior',
 'Bubba McDaniel',
 'Deiveson Figueiredo',
 'Ryan Hall',
 'Brazilian Ketlen Vieira',
 'Valter Walker’s',
 'Paul Craig',
 'Court McGee',
 'Alden Coria',
 'Irene Aldana',
 'Chris Duncan',
 'Kaik Brito',
 'Pat Healy',
 'Ken MacKenzie',
 'Hamdy Abdelwahab',
 'Montel Jackson',
 'Alex Caceres',
 'Jon Jones',
 'Claressa Shields',
 'Kevin\xa0Schuster',
 'Weston Wilson',
 'Adam Borics',
 'Shara Magomedov',
 'Logan Storley',
 'Charles Olivera',
 'Beating Allen',
 'Bartosz Szewczyk',
 'Marvin Vettori',
 'John Philips',
 'Soren Bak',
 'Askar Askarov',
 'Robbie Lawler',
 'Aljamain Sterling',
 'Kid Yamamoto',
 'Cory McKenna',
 'Andrew Thompson',
 'Jessica Andrade',
 'Randy Brown\n',
 'Aspen Ladd',
 'Victoria Leonardo',
 'Damon Wilson',
 'Alberto Montes',
 'Albert Tadevosyan',
 'Alex Volkanovski',
 'Michael Crichton',
 'Brad Tavares',
 'Mohamed Ado',
 'Bobby Taylor',
 'Shamil Gaziev',
 'Tracy Cortez',
 'Jimmy Crute',
 'Aaron Pico',
 'Hunter Azure',
 'Ahmad Hassanzada',
 'Karine Silva',
 'Yuri Panferov',
 'Kody Steele',
 'Losene Keita',
 'Will Brady',
 'Roxanne Modafferi',
 'Vai Morrer',
 'Kru Alin',
 'Andy Varela',
 'Dana Whtie’s',
 'Kru Bob Perez',
 'Eric Nolan',
 'Bella Mir',
 'Merab Dvalishvili',
 'Jozef Chen',
 'Manny Gamburyan',
 'Jason Knight',
 'Josh Parisian',
 'Eliot Marshall',
 'Jonas Mågård',
 'Yaroslav Amosov',
 'outstriking Fiziev',
 'de Ridder',
 'Cezary Oleksiejczuk',
 'Uncle Johnny',
 'Andrei Arlovksi',
 'Spencer Fisher',
 'Garret Armfield',
 'Joe Solecki',
 'Tuko Tokkos',
 'Fernie Garcia',
 'Jason Jackson',
 'Mairon Santos',
 'Shauna\xa0Bannon',
 'Tagir Ulabekov',
 'mi gente',
 'Mark Choinski',
 'Rafael Natal',
 'Liam Anderson',
 'Edmen Shahbazyan',
 'Robert Whiteford',
 'Taiyilake Nueraji',
 'Zhang Lipeng',
 'Ricky Simón',
 'Stephanie Luciano',
 'Gunnar Nelson',
 'Julio Cesar Chavez',
 'Herkus Lukosiunas',
 'Movsar Evloev',
 'Carlos Candelario',
 'Felipe Dos Santos',
 'Gabe Green',
 'Jessica Aguilar',
 'Jake Collier',
 'Steve Latrell',
 'Gilbert Burns',
 'Bruce Bowen',
 'Austin Bashi',
 'Nicolas Ott',
 'Jeong Yeong Lee',
 'Shavkat Rakhmanov',
 'David Martínez',
 'Craig Jones',
 'Jiri Procházka',
 'Cesar Almeida',
 'Sergei Pavlovich',
 'Duško Todorović',
 'Beating Pereira',
 'Chris Birchler',
 'Raphael Assuncao',
 'Ricardo Ramos',
 'Mario Pinto',
 'Bogdan Guskov',
 'Joaquim Silva',
 'Benson Henderson',
 'Dan Henderson',
 'Magno Dias',
 'Nate Landwehr',
 'Antonio Trocoli',
 'Paul Levesque',
 'Zac Pauga',
 'Waldo Cortes Acosta',
 'Cam Teague',
 'Uroš Medić',
 'Duane Ludwig',
 'Chan Sung Jung',
 'Iasmin Lucindo',
 'Conor McGregor',
 'AJ Bryant',
 'Beating Walker',
 'Benardo Sopaj',
 'Drakkar Klose',
 'Mighty Mouse',
 'Douglas Lima',
 'Josh Fremd',
 'Rafael Fiziev',
 'Carlos Vera',
 'Julianna Pena',
 'Journey Newson',
 'Boonmee Sit',
 'Garry def',
 'Ihor Potieria',
 'Daniel Strausand',
 'Kris McCray',
 'Brian Ortega',
 'Mayssa Bastos',
 'Daniel Zellhuber',
 'Kung Fu Kid',
 'Marina Rodriguez',
 'Herbert Burns',
 'Eduardo Neves',
 'Kevin McDonald',
 'Fighting Nerds',
 'JeongYeong Lee',
 'Uran Satybaldiev',
 'Brian Butler',
 'Gervonta Davis',
 'Tecia Torres',
 'Eduardo Chapolin',
 'Morgan Charrier',
 'Alik Lorenz',
 'Lee Hammond',
 'Taylor Moore',
 'Serhii Bohachuk',
 'Pete Sell',
 'Andreas Michael',
 'Timmy Cuamba',
 'Vince Morales',
 'Pedro Falcao',
 'Chase Hooper',
 'Zaleski dos Santos',
 'Renzo Gracie',
 'Eddie Alvarez',
 'the Alexander Hernandez',
 'Jiri Prochazka',
 'Mauricio Ruffy\nActivate',
 'Loik Radzhabov',
 'Aleksandar Rakić',
 'Saimon Oliveira',
 'Daniel Rodriguez',
 'Kiefer Crosbie',
 'Gilbert Smith',
 'AJ McKee',
 'Joe Rogan',
 'Francisco Grasso',
 'Mitch Raposo square',
 'Alice Pereira',
 'Robin Hood',
 'Alexander Hernandez',
 'Ramazan Temirov',
 'Valentine Shevchenko',
 'Impa Kasanganay',
 'Nariman Abbasov',
 'Charles’ jiu jitsu',
 'Jack Hermansson',
 'Dricus du Plessis',
 'Khadzimurat Bestaev',
 'Chris Gutieirrez',
 'Patricky Pitbull',
 'Terence Crawford',
 'Bryce Mitichell',
 'Demetrius Johnson',
 'Raulian Paiva',
 'Jacqueline Cavalcanti',
 'bantamweights Ricky Simon',
 'Iwo Baranieski',
 'Felipe Bunes',
 'Niklas Motta',
 'Daniel Roberts',
 'Ryan Jimmo',
 'Josh Hill',
 'Darren Stewart',
 'Ottman Azaitar',
 'Jack Shore',
 'Rolando Perez',
 'Rana Willink',
 'Herb Dean',
 'Ralph Lauren',
 'Uriah Hall',
 'Tecia Pennington',
 'Marshawn Lynch',
 'Shara Bullet',
 'Anthony Smith',
 'jiu jitsu',
 'Robert Hoyle',
 'Dominick Reyes',
 'Murtaza Talha',
 'outstriking Pichel',
 'Montse Rendon',
 'Gabriel Sayeg',
 'Dashawn Boatright',
 'Nikita Krylov',
 'Ricky Simon',
 'Hugh Pulley',
 'Will Ankalaev',
 'Jarno Errens',
 'Flyweights Alden Coria',
 'Yanal Ashmouz',
 'Elizeu Zaleski',
 'David Loiseau',
 'Jéssica Andrade',
 'Takahiro Araki',
 'Francis Marshall',
 'Viviane Araújo',
 'Benjamin Button',
 'Rashad Evans',
 'Loopy Godinez',
 'Merab Dvalishvili’s',
 'SeungWoo Choi',
 'Austin Lingo',
 'Khaos Williams',
 'Frank Ocean',
 'Weili Zhang',
 'Alexander Poppeck',
 'Josiah Harrell',
 'Julian Marquez',
 'Robert Whittaker',
 'Danny Castillo',
 'Yohan Lainesse',
 'Joao Emilio',
 'Denys Bondar',
 'Shunichi Shimizu',
 'Jaqueline Cavalcanti',
 'Joseph Lowry',
 'Azamat Bekoev',
 'DaWoon Jung',
 'Pedro Munhoz',
 'Cain Velasquez',
 'Sadibou Sy',
 'Ben Askren',
 'Edgar Chairez',
 'Marcio Barbosa',
 'Josh Hokit',
 'Charalampos Grigoriou',
 'Sam Hughes',
 'Tatsuro Taira',
 'Brandon Holmes',
 'Quillan Salkilld',
 'Louis Smolka',
 'Walt Harris',
 'Ian Machado',
 'Kolton England',
 'Julia Polastri',
 'Talita Alencar',
 'Saladhine Parnasse',
 'Matt Bessette',
 'Frankie Edgar',
 'Damir Hadzovic',
 'Phillip Latu',
 'Chris Padilla',
 'Ciryl Gane',
 'An Tuan Ho',
 'Trevor Peek',
 'Barack Obama',
 'Dricus Du Plessis',
 'Jason Manly',
 'Hernandez complimented Allen',
 'Caio Borralho',
 'Carli Judice',
 'Nassourdine Imavov',
 'Charles Byrd',
 'Yadier Del Valle',
 'Julius Walker',
 'Maki Pitolo',
 'Lucas Alexander',
 'Furkatbek Yokubov',
 'Minnie Ripperton',
 'Kennedy Maciel',
 'Casey O’Neill',
 'Brian Bowles',
 'Magomed Gadzhiyasulov',
 'Matt Wiman',
 'Clarence Darrow',
 'Farid Basharat',
 'Lerryan Douglas',
 'Chelsea Chandler',
 'Rich Franklin',
 'Alex Oliveira',
 'Christian Rodriguez',
 'Demian Maia',
 'Shane Burgos',
 'Farmer Vinc',
 'Djorden Santos',
 'Hiroyuki Takaya’s',
 'Issa Isakov',
 'Lucie Pudilová',
 'Andrea Lee',
 'Matheus Nicolau',
 'Daron Cruickshank',
 'Khamzat Chimaev\nLocation',
 'Brit Lerone Murphy',
 'Asu Almabayev\nLocation',
 'Jamal Pogues',
 'Robert Follis',
 'Francisco Trinaldo',
 'Brendson Ribeiro',
 'Jan Blachowicz',
 'Gabriel Benitez',
 'Gabriella Fernandes',
 'Jairzinho Rozenstruik',
 'Joanne Wood',
 'Alexandre Franca Nogueira',
 'Maycee Barber',
 'Francisco Prado',
 'Mohammad Usman',
 'Tim Welch',
 'Bernardo Sopaj',
 'Craig White',
 'Mikheil Sazhiniani',
 'Puro Chicali',
 'Charles Radtke',
 'Marcos DaMatta',
 'Eric Pena',
 'John Makdessi',
 'Nicolle Caliari',
 'Ramon Dekkers',
 'Kurt Holobaugh',
 'Paddy Pimblett',
 'Kyle Prepoloec',
 'Lucas Almeida',
 'James Nakashima',
 'David Obama',
 'Hyun Sung Park',
 'Brendan Marotte',
 'Luana Pineiro',
 'Megan Olivi',
 'Myron Dennis',
 'Angela Lee',
 'Elias Garcia',
 'Thiago Tavares',
 'Guido Cannetti',
 'Viviane Pereira',
 'Chad Hanekom',
 'Yancy Medeiros',
 'Donte Johnson',
 'Hector Ramirez',
 'Dennis Buzukja',
 'Jaqueline Amorim',
 'Ty Gwerder',
 'Jose Medina',
 'Stipe Miocic',
 'Diego Ferreira',
 'Jake Ellenberger',
 'Ryan Gandra',
 'TJ Dillashaw',
 'da Silva',
 'Chris Barnett',
 'Charles Jourdain',
 'Jean Silva',
 'Jureall Simmons',
 'Gaston Bolanos',
 'Kevin Borjas',
 'Ismail Naurdiev',
 'Curtis Blaydes',
 'Christian Knowles',
 'Jared Gordon',
 'Javid Basharat',
 'Daffy Duck',
 'Bantamweights Davey Grant',
 'Dilano Taylor',
 'Ilia Topuria',
 'Yasuhiro Urushitani',
 'Mark Hominick',
 'Danilo Suzart',
 'Robert Valentin',
 'Isaac Dulgarian',
 'Colby Thicknesse',
 'Los Chupacabras',
 'Bud Light',
 'Brendan Allen',
 'Giannis Antetokounmpo',
 'Mike Tyson',
 'Tresean Gore',
 'Christos Giagos',
 'Rose Conceição',
 'Clay Matza',
 'Charlie Campbell',
 'Kai Asakara',
 'Paul Sass',
 'Charlie Jo',
 'Cynthia Calvillo',
 'McKenzie Pavacich',
 'Jean\xa0Silva',
 'Bernado Sopaj',
 'Joanna Champion',
 'Takashi Sato',
 'Raúl Macías',
 'Serhiy Sidey’s',
 'Jeremy Stephens',
 'Joanna Jędrzejczyk',
 'Volkan Oezdemir',
 'Rodolfo Bellatowelcomes',
 'Chuck Liddell',
 'Della Maddalena’s',
 'Grandpa Simpson',
 'Eugene Jackson',
 'Zhang Weili',
 'Muhammad Naimov',
 'Bryan Battle',
 'Yadier del Valle',
 'Justin Sumter',
 'Felice Herrig',
 'Glover Teixeira',
 'Rinat Fakhretdinov square',
 'Luis Saldana',
 'Landon Elmore',
 'Ronaldo Rodríguez',
 'Andre Fili',
 'Renan Barao',
 'Song Kenan',
 'Carlos Hernandez',
 'Jose Daniel',
 'Daniel Frunza',
 'Renato Canuto',
 'Jonathan Brookins',
 'Tuco Tokkos',
 'Patrick Cote',
 'Matthew Semelsberger',
 'Myktybek Orolbai',
 'Anthony Njokuani',
 'Battering Aldana',
 'Billy Ray Goff',
 'Ricky Turcios',
 'Malcolm Gordon',
 'Nate Maness',
 'Kyle Crutchmer',
 'Carl Prince',
 'John Mulaney',
 'Scott Jorgensen',
 'Vinny Diaz',
 'Ethyn Ewing',
 'Joselyne Edwards',
 'Finishing Wells',
 'Slovakian Ľudovit Klein',
 'Jacob Silva',
 'Nathaniel Wood',
 'Adam Fugitt',
 'Tim Elliott',
 'Ode’ Osbourne',
 'Shanelle Dyer',
 'Brett Okamoto',
 'Guilherme Faria',
 'Arthur Lopes',
 'Shane Young',
 'Dominick Cruz',
 'Charles Oliveira’s',
 'Paulo Costa',
 'Marlon Moraes',
 'Eduarda Moura',
 'Omari Akhmedov',
 'Max Gimenis',
 'a Cheshire Cat',
 'Tha Killa Gorilla',
 'Juan Archuleta',
 'Raquel Pennington',
 'Felipe Lima',
 'Jazmin Jauregui',
 'Will Mitchell',
 'Laura Sanko',
 'Luigi Vendramini',
 'Jamall Emmers',
 'Blake Grice',
 'Mike Breeden',
 'Phil Hawes',
 'Jake Buracker',
 'Daria Zhelezniakova',
 'Damon Jackson',
 'Derrick Lewis',
 'Shogun Rua',
 'Cody Durden',
 'Evan Dunham',
 'Kevin Dornan',
 'Hunter Campbell',
 'Carlos Leal',
 'Luke Riley',
 'Xavier Franklin',
 'Donovan Beard',
 'Takanori Gomi',
 'James Gallagher',
 'Kaue Fernandes',
 'Alexander Volkanovski',
 'JJ Aldrich',
 'L’udovit Klein',
 'Tubby Alequin',
 'Mark Hunt',
 'Sam Patterson',
 'Aaron Phillips',
 'Tatiana Padilla',
 'Melsik Baghdasarayan',
 'Jeremy Kennedy',
 'Roger Huerta',
 'Ailín Pérez',
 'Alexander\xa0Volkanovski',
 'Andre Lima',
 'Diego Lopes’ UFC',
 'Pedro Rizzo',
 'Shannon Clark',
 'Sergey Nagorny',
 'Julija Stoliarenko',
 'Victor Henry',
 'Sheldon Westcott',
 'Derek Cleary',
 'SeungGuk Choi',
 'Jake Shields',
 'Charles Oliveira\n',
 'Ricardo Lamas',
 'Tim Boetsch',
 'Guilherme Pat',
 'Nate Hernandez',
 'Marco Verde',
 'Thomas Peterson',
 'Marion Reneau',
 'Daniel Barez',
 'Thiago Alves',
 'Mike Roach',
 'Kazushi Sakuraba',
 'Shawn Michaels',
 'Pablo Sucupira',
 'Bharat Khandare',
 'Joshua\xa0Van',
 'Dom Mar Fan',
 'Ali Abdelaziz',
 'Punahele Soriano',
 'Kevin Vallejos’',
 'Will Grasso',
 'Oumar Sy',
 'Hearing Fili',
 'Ariane da Silva',
 'Ignacio Bahamondes',
 'Vanessa Demopoulos',
 'Lucas Pinheiro',
 'Josiane Nunes',
 'Viktoriia Dudakva',
 'Felicia Spencer',
 'Rafael Assunção',
 'Steve Austin',
 'Fatima Kline',
 'Brunno Ferreira',
 'Jimi Manuwa',
 'Cody Haddon',
 'Sergey Morozov',
 'Jordan Leavitt',
 'Sidney Outlaw',
 'Katlyn Cerminara',
 'Li Jingliang',
 'Alexander Rakic',
 'Jasmin Jasudavicius',
 'Kyle Nelson',
 'Garrett Armfield',
 'Dariya Zheleznyakova',
 'Sultan Almohammed',
 'Alan Sanchez',
 'Mateus Mendonca',
 'Kron Gracie',
 'Jason Herzog',
 'Augusto Sakai',
 'Chris Curtis',
 'Alan Patrick',
 'Yi Zha',
 'Daniel Zellhuberat UFC',
 'Nicholas Ott',
 'Joseph Benavidez',
 'Darrion Caldwell',
 'Clayton Carpenter',
 'Tom Aspinall',
 'Moon Knight',
 'Andrew Glenn',
 'Islam Dulatov',
 'Will Sandhagen',
 'Valentina Shevchenko Moneyline',
 'Georgi Karakhanyan',
 'Terrance McKinney',
 'Leo XIV',
 'Brendan Fitzgerald',
 'Henry Cejudo',
 'Pat Schilling',
 'Yura Naito',
 'Khaos Williams chuckles',
 'Vinicius Oliveira',
 'Matthieu Duclos',
 'Roberto Sanchez',
 'Cameron Smotherman',
 'Nazim Sadykov',
 'Petr Yan',
 'Shinya Aoki',
 'Israel Adesanya',
 'Kaan Olfi',
 'Ozzy Diaz',
 'Lina Lansberg',
 'Kerry Hatley',
 'Adrian Yanez',
 'Kai Kara',
 'James Llontop',
 'HyunSung Park',
 'Elise Reed',
 'Allen Huggins',
 'Azat Maksum',
 'Ernesta Kareckaite',
 'Cheyanne Vlismas',
 'Lukasz Bosacki',
 'Taylor Swift',
 'Mark Nelson',
 'Justin Tafa',
 'Ian McCall',
 'Alex Chambers',
 'Brazilian Warlley Alves',
 'Abdulmanap Nurmagomedov',
 'John Kavanagh',
 'Bruno Mukulu',
 'Addison Barger’s',
 'Morgan Charrière',
 'John Moraga',
 'Xtreme Couture',
 'Magomed Magomedov',
 'Bolaji Oki',
 'Alexsandre Topuria',
 'Quemuel Ottoni',
 'Cale Sanderson',
 'Priscila Cachoeira',
 'Jack\xa0Della Maddalena',
 'Nora Cornolle',
 'Joel Álvarez',
 'TJ Dillashaw’s',
 'Louis Lee Scott',
 'James Llontop later',
 'Mackenzie Dern',
 'Chasen Blair',
 'Valesca Machado',
 'Ramiz Brahimaj',
 'Roy Jones',
 'Seokhyeon Ko',
 'Neemias Santana',
 'Kevin Randleman',
 'Yana Santos',
 'Ismael Bonfim',
 'Rei Tsuray',
 'Sam Calavitta',
 'Ketlen Vieiera',
 'Matheus Camilo',
 'Lee Scott',
 'Salahdine Parnasse',
 'Jesse Ronson',
 'Collin Anglin',
 'Lightweights Viacheslav Borshchev',
 'Phil de Fries',
 'Mateus Camilo',
 'CJ Vergara',
 'Aleksei Oleinik',
 'Valerie Letourneau',
 'Bo Nickal',
 'Jeka Saragih',
 'Adam Bramhald',
 'Alan Jouban',
 'Daermisi Zhawupasi',
 'Denis Tiuliulin',
 'Antonio Monteiro',
 'Erick Silva',
 'Da Silva’s',
 'Kenichi Yamamoto',
 'Irina Alekseeva',
 'Manel Kape',
 'Quang Le',
 'Keith Peterson',
 'tagged Sadykhov',
 'Allan Nascimento’s',
 'Benoit Saint Denis',
 'Jimmy Flick',
 'Chuck Palahniuk',
 'Tyler Durden',
 'Anthony Guarascio',
 'Kazakh Shavkat Rakhmonov',
 'Darrius Flowers',
 'Tony Soprano',
 'Hiromasa Ougikubo',
 'Vinicius Cenci',
 'Mohammed Alakel',
 'Max Holloway',
 'Ketlen Vieira',
 'Gordon Ryan',
 'Tuan Williams',
 'Lester Martinez',
 'Chris Clements',
 'Matt Sayles',
 'Dave Lovell',
 'Viacheslav Borshchev',
 'Julien Williams',
 'Colin Oyama',
 'Carlos Henrique',
 'Jailton Almeida',
 'Jayson Tatum',
 'Will Suarez',
 'Zarah Fairn',
 'Carlos Lozoya',
 'Gabriel Bonfim',
 'Bassil Hafez',
 'Andrew Tackett',
 'Rafa García',
 'Dalcha Lungiambula',
 'Santiago Luna',
 'Markus Perez',
 'Rafael Cerquiera',
 'Diyar Nurgozhay',
 'Dustin Stoltzfus',
 'Bruno Lopes',
 'Saint Preux',
 'Brandon Gibson',
 'Kauê Fernandes',
 'Ali Bagautinov',
 'Martin Buday',
 'Daniel Carey',
 'Ronaldo Rodriguez',
 'Edivan Santos',
 'Cody Garbrandt',
 'Vitor Belfort',
 'Juan Espino',
 'Tom Brady',
 'Samuel Nagai',
 'Radley Da Silva',
 'Beating Gaethje',
 'Shane Campbell',
 'Marc Montoya',
 'Ivan Dychko',
 'Manuel Exposito',
 'Will Lemos',
 'Tyson Nam',
 'Carlton Lieu',
 'Mateusz Rebecki',
 'Zubaira Tukhugov',
 'VeChain UFC',
 'Azamat Murzaknov',
 'Beneil Darisuh',
 'du Plessis',
 'Jack Congdon',
 'Eric Shelton',
 'Keith Jardine',
 'Edson Gomez',
 'Ed Herman',
 'Nordine Taleb',
 'Mateusz Gamrot',
 'Amanda Nunes',
 'Mick Maynard',
 'Rafael Cerqueira',
 'Elijah Dorsey',
 'Brandon Carlo',
 'Jonathan Pearce',
 'Trevin Jones',
 'Glaico Franca',
 'BJ Penn',
 'Manoel Sousa',
 'Kyle Noke',
 'Jessica Eye',
 'Mario Bautista',
 'Renan Barão',
 'Jan Błachowicz',
 'Taila Santos',
 'Jonathan Martinez',
 'Victor Hugo',
 'Johny Hendricks',
 'Brandon Davis',
 'Kevin Schuster',
 'Joe Lauzon',
 'Hannah Goldy',
 'Manon Fiorot’s',
 'Top Kiwram',
 'Santiago Ponzinibbio',
 'Mohammad Yahya',
 'Javier Martinez',
 'Zach Scroggin',
 'Sal D’Amato',
 'Kevin Vallejos',
 'Ray Bradbury',
 'Aaron Tau',
 'Zabit Magomedsharipov',
 'Sadykhov cutting Motta',
 'Marnic Mann',
 'Carlos Newton',
 'Darren Elkins',
 'Zak Cummings',
 'Tom Breese',
 'Angel Pacheco',
 'Ray Cooper III',
 'Matt Schnell',
 'Jared Cannonier',
 'Jacobe Smith',
 'Acosta square',
 'Imanol Rodriguez',
 'Josh Emmet',
 'Loma Lookboonmee',
 'Kay Hansen',
 'Bishop Auckland',
 'Gabriel Green',
 'Mark Smith',
 'Vitor Ribeiro',
 'Chris Mickle',
 'Ketlen Souza',
 'Jas Jas',
 'David Onama',
 'Austin Vanderford',
 'Ante Delija',
 'Trey Waters',
 'Toshiomi Kazama',
 'Brazilian Kaue Fernandes',
 'Roosevelt Roberts',
 'Jamahal Hill',
 'Rafaello Oliveira',
 'Michael Trizano',
 'Michael Bisping',
 'Adrian Yanez’ UFC',
 'Paul Rimmer',
 'Michal Figlak',
 'Conejo Ruiz',
 'Charlie Brenneman',
 'Muhammad Mokaev',
 'ChangHo Lee',
 'Val Woodburn',
 'Marvin Egan',
 'Fabricio Werdum',
 'Giga Chikadze',
 'Bantamweights Brad Katona',
 'Mashrabjon Ruzibaev',
 'Darya Zheleznyakova',
 'Jafel Filho',
 'Michael Chiesa',
 'Patricio Pitbull',
 'Scotty Morton',
 'Luana Carolina',
 'Bill Belichick',
 'Ian Freeman',
 'Ronda Rousey',
 'Dustin Jacoby',
 'Carlos Condit',
 'Fernando Padilla',
 'Lukasz Bosakci',
 'Dana White’s',
 'Michael Dufort',
 'Aleksandar Rakic',
 'Marc Diakiese',
 'Sean Shelby',
 'tokui waza',
 'Daniel Pineda',
 'Alice Ardelean',
 'Alex Perez',
 'Mickey Gall',
 'Mateusz Rębecki',
 'Bruno Silva',
 'Michael Morales',
 'Flyweight Namajunas',
 'Trevor Wittman',
 'De Ridder',
 'Lucas Camacho',
 'Tony Ferguson',
 'Miesha Tate',
 'Magomed Gadhziyasulov',
 'Hyo Jun Choi',
 'Jean Matsumoto',
 'Eric Nicksick',
 'Aaron Lewis',
 'Michal Oleksiejczuk',
 'Bate Estaca',
 'Kaan Ofli',
 'Vitor Petrino',
 'end Poirier',
 'Gadzhi Omargadzhiev',
 'SeokHyeon Ko',
 'Angela Hill',
 'Zhang Mingyanhg',
 'Jiří Procházka',
 'Alexander Volkanovskisquaring',
 'Lyoto Machida',
 'Chidi Njokuani',
 'Reito Tsutsumi',
 'Jorge Rivera',
 'Harrison Ford',
 'blitzed Perez',
 'Ricky Glenn',
 'John Wood',
 'Dyson Daniels',
 'Serghei Pavlovich',
 'Jessica Penne',
 'Tommy McMillen',
 'Giannis Bachar',
 'Jose Miguel Delgado',
 'Marc Tulio',
 'Daniel Weichel',
 'Dan Ige',
 'Ismail Bonfim',
 'Niko Price',
 'Melissa Mullins',
 'Kung Fu',
 'Aussies Robert Whittaker',
 'Payton Talbott',
 'Diego Sanchez',
 'Calvin Kattar',
 'Yuki Kondo',
 'Martin Pakciarz',
 'Matt Hughes',
 'Kai Asakura',
 'Jason Witt',
 'Pat Miletich',
 'Sam Alvey',
 'Dos Santos',
 'Daniil Donchenko',
 'Tony Gravely',
 'Louie Sutherland',
 'Taylor Swift’s',
 'Joanna Violence',
 'Will Volkanovski',
 'Vinicius Oliviera',
 'Dorian Olivarez',
 'Daniel Straus',
 'Flyweights Diana Belbita',
 'Ray Longo',
 'Artem Levin',
 'Frank Mir',
 'Juliana Miller',
 'José Aldo',
 'Middleweight DWCS',
 'Rolando Bedoya',
 'Tom Nolan',
 'Carlos Prates',
 'Cristiano Marcello',
 'AJ Cunningham',
 'Noche UFC',
 'Julian Williams',
 'Rana Singh',
 'Eddie Vedder',
 'Mo Ado',
 'Vicente Luque',
 'Mike Malott',
 'Lupe Fiasco',
 'Julio Arce',
 'Raiko Santana',
 'Wang Cong',
 ...}

In [13]:
def is_woman_tag(tag: Tag):
    text = tag.get_text().strip().lower()
    return "woman" in text or "women" in text

def find_gender_on_ufc(name: str):
    name_query = "-".join(name.split()).replace('’', ' ')
    url = f"https://www.ufc.com/athlete/{name_query}"

    try:
        response = get_request(url)
        soup = BeautifulSoup(response.text, "html.parser")

        tags: list[Tag] = soup.find_all("p", "hero-profile__tag")
        if not tags:
            return None

        is_woman = any([is_woman_tag(tag) for tag in tags])
        if is_woman:
            return "woman"
        else:
            return "man"
    except Exception as e:
        print("Error getting gender of", name)
        print(e)

In [ ]:
# Set this to False if you want to fetch the genders from the UFC website
use_saved_gender_map = True
genders_map_file = "./genders_map_13-01-26_19-50-58.csv"

if use_saved_gender_map and os.path.exists(genders_map_file):
    name_gender_pairs_df = pd.read_csv(genders_map_file)
    genders_map: dict[str, str] = dict(zip(name_gender_pairs_df["name"], name_gender_pairs_df["gender"]))
else:
    def get_name_gender_pair_on_ufc(name: str):
        return (name, find_gender_on_ufc(name))

    with ThreadPoolExecutor() as executor:
        name_gender_pairs = [
            (n, g)
            for n, g in executor.map(get_name_gender_pair_on_ufc, full_names)
            if g is not None
        ]

    genders_map = dict(name_gender_pairs)

    pd.DataFrame(data={
        "name": genders_map.keys(),
        "gender": genders_map.values(),
    })\
        .set_index("name")\
        .to_csv(f"./genders_map_{datetime.now().strftime('%d-%m-%y_%H-%M-%S')}.csv")

genders_map

{'Matt Frevola': 'man',
 'Jose Aldo': 'man',
 'Maurice Greene': 'man',
 'Curtis Millender': 'man',
 'Antonio Rogerio Nogueira': 'man',
 'Arman Tsarukyan': 'man',
 'Luis Pena': 'man',
 'Oban Elliott': 'man',
 'Edson Barboza': 'man',
 'Will Santiago': 'man',
 'Antonio Carlos Junior': 'man',
 'Bubba McDaniel': 'man',
 'Deiveson Figueiredo': 'man',
 'Ryan Hall': 'man',
 'Paul Craig': 'man',
 'Court McGee': 'man',
 'Alden Coria': 'man',
 'Irene Aldana': 'woman',
 'Chris Duncan': 'man',
 'Kaik Brito': 'man',
 'Pat Healy': 'man',
 'Hamdy Abdelwahab': 'man',
 'Montel Jackson': 'man',
 'Alex Caceres': 'man',
 'Jon Jones': 'man',
 'Shara Magomedov': 'man',
 'Marvin Vettori': 'man',
 'Askar Askarov': 'man',
 'Robbie Lawler': 'man',
 'Aljamain Sterling': 'man',
 'Cory McKenna': 'woman',
 'Jessica Andrade': 'woman',
 'Randy Brown\n': 'man',
 'Aspen Ladd': 'woman',
 'Victoria Leonardo': 'woman',
 'Alberto Montes': 'man',
 'Albert Tadevosyan': 'man',
 'Brad Tavares': 'man',
 'Shamil Gaziev': 'man',
 'Tracy Cortez': 'woman',
 'Jimmy Crute': 'man',
 'Aaron Pico': 'man',
 'Hunter Azure': 'man',
 'Ahmad Hassanzada': 'man',
 'Karine Silva': 'woman',
 'Kody Steele': 'man',
 'Roxanne Modafferi': 'woman',
 'Eric Nolan': 'man',
 'Merab Dvalishvili': 'man',
 'Manny Gamburyan': 'man',
 'Jason Knight': 'man',
 'Josh Parisian': 'man',
 'Eliot Marshall': 'man',
 'Yaroslav Amosov': 'man',
 'Cezary Oleksiejczuk': 'man',
 'Spencer Fisher': 'man',
 'Joe Solecki': 'man',
 'Fernie Garcia': 'man',
 'Jason Jackson': 'man',
 'Shauna\xa0Bannon': 'woman',
 'Mark Choinski': 'man',
 'Rafael Natal': 'man',
 'Edmen Shahbazyan': 'man',
 'Taiyilake Nueraji': 'man',
 'Zhang Lipeng': 'man',
 'Ricky Simón': 'man',
 'Gunnar Nelson': 'man',
 'Movsar Evloev': 'man',
 'Carlos Candelario': 'man',
 'Felipe Dos Santos': 'man',
 'Gabe Green': 'man',
 'Jessica Aguilar': 'woman',
 'Jake Collier': 'man',
 'Gilbert Burns': 'man',
 'Austin Bashi': 'man',
 'Jeong Yeong Lee': 'man',
 'David Martínez': 'man',
 'Craig Jones': 'man',
 'Jiri Procházka': 'man',
 'Cesar Almeida': 'man',
 'Sergei Pavlovich': 'man',
 'Duško Todorović': 'man',
 'Chris Birchler': 'man',
 'Raphael Assuncao': 'man',
 'Ricardo Ramos': 'man',
 'Mario Pinto': 'man',
 'Bogdan Guskov': 'man',
 'Joaquim Silva': 'man',
 'Benson Henderson': 'man',
 'Dan Henderson': 'man',
 'Nate Landwehr': 'man',
 'Antonio Trocoli': 'man',
 'Zac Pauga': 'man',
 'Waldo Cortes Acosta': 'man',
 'Uroš Medić': 'man',
 'Duane Ludwig': 'man',
 'Chan Sung Jung': 'man',
 'Iasmin Lucindo': 'woman',
 'Conor McGregor': 'man',
 'Benardo Sopaj': 'man',
 'Drakkar Klose': 'man',
 'Josh Fremd': 'man',
 'Rafael Fiziev': 'man',
 'Carlos Vera': 'man',
 'Julianna Pena': 'woman',
 'Journey Newson': 'man',
 'Ihor Potieria': 'man',
 'Kris McCray': 'man',
 'Brian Ortega': 'man',
 'Daniel Zellhuber': 'man',
 'Marina Rodriguez': 'woman',
 'Herbert Burns': 'man',
 'Eduardo Neves': 'man',
 'JeongYeong Lee': 'man',
 'Uran Satybaldiev': 'man',
 'Tecia Torres': 'woman',
 'Taylor Moore': 'man',
 'Pete Sell': 'man',
 'Vince Morales': 'man',
 'Pedro Falcao': 'man',
 'Chase Hooper': 'man',
 'Renzo Gracie': 'man',
 'Eddie Alvarez': 'man',
 'Jiri Prochazka': 'man',
 'Loik Radzhabov': 'man',
 'Aleksandar Rakić': 'man',
 'Saimon Oliveira': 'man',
 'Daniel Rodriguez': 'man',
 'Kiefer Crosbie': 'man',
 'Gilbert Smith': 'man',
 'Alice Pereira': 'woman',
 'Alexander Hernandez': 'man',
 'Ramazan Temirov': 'man',
 'Impa Kasanganay': 'man',
 'Nariman Abbasov': 'man',
 'Jack Hermansson': 'man',
 'Dricus du Plessis': 'man',
 'Raulian Paiva': 'man',
 'Jacqueline Cavalcanti': 'woman',
 'Felipe Bunes': 'man',
 'Daniel Roberts': 'man',
 'Ryan Jimmo': 'man',
 'Josh Hill': 'man',
 'Darren Stewart': 'man',
 'Ottman Azaitar': 'man',
 'Jack Shore': 'man',
 'Rolando Perez': 'man',
 'Uriah Hall': 'man',
 'Tecia Pennington': 'woman',
 'Anthony Smith': 'man',
 'Dominick Reyes': 'man',
 'Murtaza Talha': 'man',
 'Nikita Krylov': 'man',
 'Ricky Simon': 'man',
 'Jarno Errens': 'man',
 'Yanal Ashmouz': 'man',
 'David Loiseau': 'man',
 'Jéssica Andrade': 'woman',
 'Francis Marshall': 'man',
 'Viviane Araújo': 'woman',
 'Rashad Evans': 'man',
 'Loopy Godinez': 'woman',
 'SeungWoo Choi': 'man',
 'Austin Lingo': 'man',
 'Khaos Williams': 'man',
 'Weili Zhang': 'woman',
 'Alexander Poppeck': 'man',
 'Josiah Harrell': 'man',
 'Julian Marquez': 'man',
 'Robert Whittaker': 'man',
 'Danny Castillo': 'man',
 'Yohan Lainesse': 'man',
 'Denys Bondar': 'man',
 'Shunichi Shimizu': 'man',
 'Joseph Lowry': 'man',
 'Azamat Bekoev': 'man',
 'Pedro Munhoz': 'man',
 'Cain Velasquez': 'man',
 'Ben Askren': 'man',
 'Edgar Chairez': 'man',
 'Marcio Barbosa': 'man',
 'Josh Hokit': 'man',
 'Charalampos Grigoriou': 'man',
 'Sam Hughes': 'woman',
 'Tatsuro Taira': 'man',
 'Quillan Salkilld': 'man',
 'Louis Smolka': 'man',
 'Walt Harris': 'man',
 'Julia Polastri': 'woman',
 'Talita Alencar': 'woman',
 'Matt Bessette': 'man',
 'Frankie Edgar': 'man',
 'Damir Hadzovic': 'man',
 'Chris Padilla': 'man',
 'Ciryl Gane': 'man',
 'Trevor Peek': 'man',
 'Dricus Du Plessis': 'man',
 'Caio Borralho': 'man',
 'Carli Judice': 'woman',
 'Nassourdine Imavov': 'man',
 'Charles Byrd': 'man',
 'Yadier Del Valle': 'man',
 'Julius Walker': 'man',
 'Maki Pitolo': 'man',
 'Lucas Alexander': 'man',
 'Brian Bowles': 'man',
 'Magomed Gadzhiyasulov': 'man',
 'Matt Wiman': 'man',
 'Farid Basharat': 'man',
 'Lerryan Douglas': 'man',
 'Chelsea Chandler': 'woman',
 'Rich Franklin': 'man',
 'Alex Oliveira': 'man',
 'Christian Rodriguez': 'man',
 'Demian Maia': 'man',
 'Shane Burgos': 'man',
 'Djorden Santos': 'man',
 'Issa Isakov': 'man',
 'Lucie Pudilová': 'woman',
 'Andrea Lee': 'woman',
 'Matheus Nicolau': 'man',
 'Daron Cruickshank': 'man',
 'Jamal Pogues': 'man',
 'Francisco Trinaldo': 'man',
 'Brendson Ribeiro': 'man',
 'Jan Blachowicz': 'man',
 'Gabriel Benitez': 'man',
 'Gabriella Fernandes': 'woman',
 'Jairzinho Rozenstruik': 'man',
 'Joanne Wood': 'woman',
 'Maycee Barber': 'woman',
 'Francisco Prado': 'man',
 'Bernardo Sopaj': 'man',
 'Craig White': 'man',
 'Charles Radtke': 'man',
 'John Makdessi': 'man',
 'Nicolle Caliari': 'woman',
 'Kurt Holobaugh': 'man',
 'Paddy Pimblett': 'man',
 'Lucas Almeida': 'man',
 'Brendan Marotte': 'man',
 'Myron Dennis': 'man',
 'Elias Garcia': 'man',
 'Thiago Tavares': 'man',
 'Guido Cannetti': 'man',
 'Viviane Pereira': 'woman',
 'Chad Hanekom': 'man',
 'Yancy Medeiros': 'man',
 'Donte Johnson': 'man',
 'Hector Ramirez': 'man',
 'Dennis Buzukja': 'man',
 'Jaqueline Amorim': 'woman',
 'Stipe Miocic': 'man',
 'Diego Ferreira': 'man',
 'Jake Ellenberger': 'man',
 'Ryan Gandra': 'man',
 'TJ Dillashaw': 'man',
 'Chris Barnett': 'man',
 'Charles Jourdain': 'man',
 'Jean Silva': 'man',
 'Gaston Bolanos': 'man',
 'Kevin Borjas': 'man',
 'Ismail Naurdiev': 'man',
 'Curtis Blaydes': 'man',
 'Jared Gordon': 'man',
 'Javid Basharat': 'man',
 'Ilia Topuria': 'man',
 'Yasuhiro Urushitani': 'man',
 'Mark Hominick': 'man',
 'Danilo Suzart': 'man',
 'Isaac Dulgarian': 'man',
 'Colby Thicknesse': 'man',
 'Brendan Allen': 'man',
 'Tresean Gore': 'man',
 'Christos Giagos': 'man',
 'Charlie Campbell': 'man',
 'Paul Sass': 'man',
 'Cynthia Calvillo': 'woman',
 'Jean\xa0Silva': 'man',
 'Takashi Sato': 'man',
 'Jeremy Stephens': 'man',
 'Joanna Jędrzejczyk': 'woman',
 'Volkan Oezdemir': 'man',
 'Chuck Liddell': 'man',
 'Eugene Jackson': 'man',
 'Zhang Weili': 'woman',
 'Muhammad Naimov': 'man',
 'Bryan Battle': 'man',
 'Yadier del Valle': 'man',
 'Justin Sumter': 'man',
 'Felice Herrig': 'woman',
 'Glover Teixeira': 'man',
 'Luis Saldana': 'man',
 'Andre Fili': 'man',
 'Renan Barao': 'man',
 'Song Kenan': 'man',
 'Carlos Hernandez': 'man',
 'Daniel Frunza': 'man',
 'Jonathan Brookins': 'man',
 'Tuco Tokkos': 'man',
 'Patrick Cote': 'man',
 'Matthew Semelsberger': 'man',
 'Myktybek Orolbai': 'man',
 'Anthony Njokuani': 'man',
 'Ricky Turcios': 'man',
 'Malcolm Gordon': 'man',
 'Nate Maness': 'man',
 'Scott Jorgensen': 'man',
 'Ethyn Ewing': 'man',
 'Joselyne Edwards': 'woman',
 'Jacob Silva': 'man',
 'Nathaniel Wood': 'man',
 'Adam Fugitt': 'man',
 'Tim Elliott': 'man',
 'Shanelle Dyer': 'woman',
 'Shane Young': 'man',
 'Dominick Cruz': 'man',
 'Paulo Costa': 'man',
 'Marlon Moraes': 'man',
 'Eduarda Moura': 'woman',
 'Omari Akhmedov': 'man',
 'Max Gimenis': 'man',
 'Raquel Pennington': 'woman',
 'Felipe Lima': 'man',
 'Luigi Vendramini': 'man',
 'Jamall Emmers': 'man',
 'Mike Breeden': 'man',
 'Phil Hawes': 'man',
 'Daria Zhelezniakova': 'woman',
 'Damon Jackson': 'man',
 'Derrick Lewis': 'man',
 'Cody Durden': 'man',
 'Evan Dunham': 'man',
 'Carlos Leal': 'man',
 'Luke Riley': 'man',
 'Donovan Beard': 'man',
 'Takanori Gomi': 'man',
 'Kaue Fernandes': 'man',
 'Alexander Volkanovski': 'man',
 'JJ Aldrich': 'woman',
 'Mark Hunt': 'man',
 'Sam Patterson': 'man',
 'Aaron Phillips': 'man',
 'Jeremy Kennedy': 'man',
 'Roger Huerta': 'man',
 'Ailín Pérez': 'woman',
 'Alexander\xa0Volkanovski': 'man',
 'Andre Lima': 'man',
 'Pedro Rizzo': 'man',
 'Julija Stoliarenko': 'woman',
 'Victor Henry': 'man',
 'Sheldon Westcott': 'man',
 'SeungGuk Choi': 'man',
 'Jake Shields': 'man',
 'Charles Oliveira\n': 'man',
 'Ricardo Lamas': 'man',
 'Tim Boetsch': 'man',
 'Guilherme Pat': 'man',
 'Marion Reneau': 'woman',
 'Daniel Barez': 'man',
 'Thiago Alves': 'man',
 'Kazushi Sakuraba': 'man',
 'Joshua\xa0Van': 'man',
 'Dom Mar Fan': 'man',
 'Punahele Soriano': 'man',
 'Oumar Sy': 'man',
 'Ariane da Silva': 'woman',
 'Ignacio Bahamondes': 'man',
 'Vanessa Demopoulos': 'woman',
 'Josiane Nunes': 'woman',
 'Felicia Spencer': 'woman',
 'Fatima Kline': 'woman',
 'Brunno Ferreira': 'man',
 'Jimi Manuwa': 'man',
 'Cody Haddon': 'man',
 'Sergey Morozov': 'man',
 'Jordan Leavitt': 'man',
 'Sidney Outlaw': 'man',
 'Katlyn Cerminara': 'woman',
 'Li Jingliang': 'man',
 'Kyle Nelson': 'man',
 'Garrett Armfield': 'man',
 'Dariya Zheleznyakova': 'woman',
 'Mateus Mendonca': 'man',
 'Kron Gracie': 'man',
 'Augusto Sakai': 'man',
 'Chris Curtis': 'man',
 'Alan Patrick': 'man',
 'Yi Zha': 'man',
 'Joseph Benavidez': 'man',
 'Clayton Carpenter': 'man',
 'Tom Aspinall': 'man',
 'Islam Dulatov': 'man',
 'Terrance McKinney': 'man',
 'Henry Cejudo': 'man',
 'Pat Schilling': 'man',
 'Vinicius Oliveira': 'man',
 'Roberto Sanchez': 'man',
 'Cameron Smotherman': 'man',
 'Petr Yan': 'man',
 'Shinya Aoki': 'man',
 'Israel Adesanya': 'man',
 'Ozzy Diaz': 'man',
 'Lina Lansberg': 'woman',
 'Adrian Yanez': 'man',
 'James Llontop': 'man',
 'HyunSung Park': 'man',
 'Elise Reed': 'woman',
 'Azat Maksum': 'man',
 'Ernesta Kareckaite': 'woman',
 'Cheyanne Vlismas': 'woman',
 'Justin Tafa': 'man',
 'Ian McCall': 'man',
 'Alex Chambers': 'woman',
 'Morgan Charrière': 'man',
 'John Moraga': 'man',
 'Bolaji Oki': 'man',
 'Priscila Cachoeira': 'woman',
 'Jack\xa0Della Maddalena': 'man',
 'Nora Cornolle': 'woman',
 'Joel Álvarez': 'man',
 'Louis Lee Scott': 'man',
 'Mackenzie Dern': 'woman',
 'Valesca Machado': 'woman',
 'Ramiz Brahimaj': 'man',
 'Roy Jones': 'man',
 'Seokhyeon Ko': 'man',
 'Kevin Randleman': 'man',
 'Yana Santos': 'woman',
 'Ismael Bonfim': 'man',
 'Matheus Camilo': 'man',
 'Jesse Ronson': 'man',
 'Collin Anglin': 'man',
 'Phil de Fries': 'man',
 'CJ Vergara': 'man',
 'Aleksei Oleinik': 'man',
 'Valerie Letourneau': 'woman',
 'Bo Nickal': 'man',
 'Jeka Saragih': 'man',
 'Alan Jouban': 'man',
 'Daermisi Zhawupasi': 'man',
 'Denis Tiuliulin': 'man',
 'Erick Silva': 'man',
 'Kenichi Yamamoto': 'man',
 'Irina Alekseeva': 'woman',
 'Manel Kape': 'man',
 'Quang Le': 'man',
 'Benoit Saint Denis': 'man',
 'Jimmy Flick': 'man',
 'Darrius Flowers': 'man',
 'Vinicius Cenci': 'man',
 'Max Holloway': 'man',
 'Ketlen Vieira': 'woman',
 'Chris Clements': 'man',
 'Matt Sayles': 'man',
 'Viacheslav Borshchev': 'man',
 'Jailton Almeida': 'man',
 'Zarah Fairn': 'woman',
 'Gabriel Bonfim': 'man',
 'Bassil Hafez': 'man',
 'Rafa García': 'man',
 'Dalcha Lungiambula': 'man',
 'Santiago Luna': 'man',
 'Markus Perez': 'man',
 'Diyar Nurgozhay': 'man',
 'Dustin Stoltzfus': 'man',
 'Bruno Lopes': 'man',
 'Kauê Fernandes': 'man',
 'Ali Bagautinov': 'man',
 'Martin Buday': 'man',
 'Edivan Santos': 'man',
 'Cody Garbrandt': 'man',
 'Vitor Belfort': 'man',
 'Juan Espino': 'man',
 'Shane Campbell': 'man',
 'Tyson Nam': 'man',
 'Mateusz Rebecki': 'man',
 'Zubaira Tukhugov': 'man',
 'Eric Shelton': 'man',
 'Keith Jardine': 'man',
 'Edson Gomez': 'man',
 'Ed Herman': 'man',
 'Nordine Taleb': 'man',
 'Mateusz Gamrot': 'man',
 'Amanda Nunes': 'woman',
 'Rafael Cerqueira': 'man',
 'Jonathan Pearce': 'man',
 'Trevin Jones': 'man',
 'Glaico Franca': 'man',
 'BJ Penn': 'man',
 'Manoel Sousa': 'man',
 'Kyle Noke': 'man',
 'Jessica Eye': 'woman',
 'Mario Bautista': 'man',
 'Renan Barão': 'man',
 'Taila Santos': 'woman',
 'Jonathan Martinez': 'man',
 'Victor Hugo': 'man',
 'Johny Hendricks': 'man',
 'Brandon Davis': 'man',
 'Joe Lauzon': 'man',
 'Hannah Goldy': 'woman',
 'Top Kiwram': 'man',
 'Santiago Ponzinibbio': 'man',
 'Mohammad Yahya': 'man',
 'Kevin Vallejos': 'man',
 'Zabit Magomedsharipov': 'man',
 'Marnic Mann': 'woman',
 'Carlos Newton': 'man',
 'Darren Elkins': 'man',
 'Zak Cummings': 'man',
 'Tom Breese': 'man',
 'Angel Pacheco': 'man',
 'Matt Schnell': 'man',
 'Jared Cannonier': 'man',
 'Jacobe Smith': 'man',
 'Imanol Rodriguez': 'man',
 'Loma Lookboonmee': 'woman',
 'Kay Hansen': 'woman',
 'Gabriel Green': 'man',
 'Vitor Ribeiro': 'man',
 'Chris Mickle': 'man',
 'Ketlen Souza': 'woman',
 'David Onama': 'man',
 'Austin Vanderford': 'man',
 'Ante Delija': 'man',
 'Trey Waters': 'man',
 'Toshiomi Kazama': 'man',
 'Roosevelt Roberts': 'man',
 'Jamahal Hill': 'man',
 'Rafaello Oliveira': 'man',
 'Michael Trizano': 'man',
 'Michael Bisping': 'man',
 'Michal Figlak': 'man',
 'Charlie Brenneman': 'man',
 'Muhammad Mokaev': 'man',
 'Val Woodburn': 'man',
 'Fabricio Werdum': 'man',
 'Giga Chikadze': 'man',
 'Mashrabjon Ruzibaev': 'man',
 'Jafel Filho': 'man',
 'Michael Chiesa': 'man',
 'Luana Carolina': 'woman',
 'Ian Freeman': 'man',
 'Ronda Rousey': 'woman',
 'Dustin Jacoby': 'man',
 'Carlos Condit': 'man',
 'Fernando Padilla': 'man',
 'Aleksandar Rakic': 'man',
 'Marc Diakiese': 'man',
 'Daniel Pineda': 'man',
 'Alice Ardelean': 'woman',
 'Alex Perez': 'man',
 'Mickey Gall': 'man',
 'Mateusz Rębecki': 'man',
 'Bruno Silva': 'man',
 'Michael Morales': 'man',
 'Tony Ferguson': 'man',
 'Miesha Tate': 'woman',
 'Jean Matsumoto': 'man',
 'Michal Oleksiejczuk': 'man',
 'Kaan Ofli': 'man',
 'Vitor Petrino': 'man',
 'Gadzhi Omargadzhiev': 'man',
 'SeokHyeon Ko': 'man',
 'Angela Hill': 'woman',
 'Jiří Procházka': 'man',
 'Lyoto Machida': 'man',
 'Chidi Njokuani': 'man',
 'Jorge Rivera': 'man',
 'Ricky Glenn': 'man',
 'Jessica Penne': 'woman',
 'Tommy McMillen': 'man',
 'Dan Ige': 'man',
 'Niko Price': 'man',
 'Melissa Mullins': 'woman',
 'Payton Talbott': 'man',
 'Diego Sanchez': 'man',
 'Calvin Kattar': 'man',
 'Yuki Kondo': 'man',
 'Matt Hughes': 'man',
 'Kai Asakura': 'man',
 'Jason Witt': 'man',
 'Pat Miletich': 'man',
 'Sam Alvey': 'man',
 'Daniil Donchenko': 'man',
 'Tony Gravely': 'man',
 'Louie Sutherland': 'man',
 'Frank Mir': 'man',
 'Juliana Miller': 'woman',
 'José Aldo': 'man',
 'Rolando Bedoya': 'man',
 'Tom Nolan': 'man',
 'Carlos Prates': 'man',
 'Cristiano Marcello': 'man',
 'AJ Cunningham': 'man',
 'Vicente Luque': 'man',
 'Mike Malott': 'man',
 'Julio Arce': 'man',
 'Wang Cong': 'woman',
 'Hailey Cowan': 'woman',
 'Miranda Maverick': 'woman',
 'Dante Rivera': 'man',
 'Ramazan Emeev': 'man',
 'Nazim Sadykhov': 'man',
 'Kamuela Kirk': 'man',
 'Ailin Perez': 'woman',
 'Kris Moutinho': 'man',
 'JunYong Park': 'man',
 'Zachary Borrego': 'man',
 'Luana Pinheiro': 'woman',
 'Alfred Khashakyan': 'man',
 'Brad Katona': 'man',
 'Will Brooks': 'man',
 'Alexandre Pantoja': 'man',
 'Gerald Meerschaert': 'man',
 'Youssef Zalal': 'man',
 'Abdul Razak Alhassan': 'man',
 'Yair Rodriguez': 'man',
 'Trevin Giles': 'man',
 'Diego Brandão': 'man',
 'Alexander Volkov': 'man',
 'Miguel Baeza': 'man',
 'Sedriques Dumas': 'man',
 'Jared Gooden': 'man',
 'Anthony Hamilton': 'man',
 'Leon Edwards': 'man',
 'Denzel Freeman': 'man',
 'Drew Dober': 'man',
 'Chris Weidman': 'man',
 'Tim Means': 'man',
 'Polyana Viana': 'woman',
 'Shauna Bannon': 'woman',
 'Al Iaquinta': 'man',
 'Karl Williams': 'man',
 'Steven Nguyen': 'man',
 'Rodolfo Bellato': 'man',
 'André Fialho': 'man',
 'Din Thomas': 'man',
 'Darren Till': 'man',
 'Joanne Calderwood': 'woman',
 'Gil Castillo': 'man',
 'Joanderson Brito': 'man',
 'Liz Carmouche': 'woman',
 'Julianna Peña': 'woman',
 'Alexandr Romanov': 'man',
 'Tabatha Ricci': 'woman',
 'Sean Sharaf': 'man',
 'Emrah Sonmez': 'man',
 'Terry Etim': 'man',
 'Tereza Bleda': 'woman',
 'Cub Swanson': 'man',
 'Michael Page': 'man',
 'Michael McDonald': 'man',
 'Dominic Waters': 'man',
 'Nazim\xa0Sadykhov': 'man',
 'Diana Belbita': 'woman',
 'Carol Foro': 'woman',
 'Islam Makhachev': 'man',
 'Beneil Dariush': 'man',
 'Michael Aswell': 'man',
 'Kaynan Kruschewsky': 'man',
 'Brett Johns': 'man',
 'Brendon Marotte': 'man',
 'Michael Morales\n': 'man',
 'Rei Tsuruya': 'man',
 'John Phillips': 'man',
 'Mason Jones': 'man',
 'Kamaru Usman': 'man',
 'Cris Cyborg': 'woman',
 'Khabib Nurmagomedov': 'man',
 'Rodrigo Sezinando': 'man',
 'Xiaonan Yan': 'woman',
 'Gillian Robertson': 'woman',
 'Nik Lentz': 'man',
 'Brandon Royval': 'man',
 'Ryan Jensen': 'man',
 'Paige VanZant': 'woman',
 'Bogdan Grad': 'man',
 'Brad Riddell': 'man',
 'Mateus Mendonça': 'man',
 'Jeremiah Wells': 'man',
 'Joanna Jedrzejczyk': 'woman',
 'Mark Kerr': 'man',
 'Andrei Arlovski': 'man',
 'Arnold Allen': 'man',
 'Misha Cirkunov': 'man',
 'Tallison Teixeira': 'man',
 'Nate Diaz': 'man',
 'Kevin Lee': 'man',
 'Randa Markos': 'woman',
 'Michael Johnson': 'man',
 'Michael Chandler': 'man',
 'Diego Nunes': 'man',
 'Ty Miller': 'man',
 'Connor Matthews': 'man',
 'Manon Fiorot': 'woman',
 'Max Griffin': 'man',
 'Marlon Vera': 'man',
 'Cody Stamann': 'man',
 'Germaine de Randamie': 'woman',
 'Patricio Freire': 'man',
 'Demetrious Johnson': 'man',
 'Kyle Daukaus': 'man',
 'Kevin Natividad': 'man',
 'Rani Yahya': 'man',
 'Alex Pereira': 'man',
 'Pat Barry': 'man',
 'Rayanne dos Santos': 'woman',
 'Thomas Almeida': 'man',
 'Landon Quinones': 'man',
 'AJ Dobson': 'man',
 'Nick Fiore': 'man',
 'Jamie Varner': 'man',
 'Ramon Taveras': 'man',
 'Piera Rodriguez': 'woman',
 'Roman Kopylov': 'man',
 'Alonzo Menifield': 'man',
 'Brad Pickett': 'man',
 'Ivana Petrovic': 'woman',
 'Tereza Bledá': 'woman',
 'Cameron Rowston': 'man',
 'Davey Grant': 'man',
 'Junyong Park': 'man',
 'Jacare Souza': 'man',
 'Elias Theodorou': 'man',
 'Joaquin Buckley': 'man',
 'DooHo Choi': 'man',
 'James Vick': 'man',
 'Mark Madsen': 'man',
 'Thiago Moisés': 'man',
 'Alvin Hines': 'man',
 'Bryce\xa0Mitchell': 'man',
 'Robelis Despaigne': 'man',
 'Malcolm Wellmaker': 'man',
 'Emily Ducote': 'woman',
 'Tai Tuivasa': 'man',
 'Kelvin Gastelum': 'man',
 'Daniel Santos': 'man',
 'Claudio Puelles': 'man',
 'Forrest Griffin': 'man',
 'Liang Na': 'woman',
 'Steve Erceg': 'man',
 'Sarah Kaufman': 'woman',
 'Bryce Mitchell': 'man',
 'Joe Pyfer': 'man',
 'Daniel Lacerda': 'man',
 'Geoff Neal': 'man',
 'Johnny Case': 'man',
 'Gabriel Miranda': 'man',
 'Yushin Okami': 'man',
 'Bill Algeo': 'man',
 'Marcin Prachnio': 'man',
 'Muin Gafurov': 'man',
 'Macy Chiasson': 'woman',
 'Randall Wallace': 'man',
 'Neil Seery': 'man',
 'Karolina Kowalkiewicz': 'woman',
 'Ramiro Jimenez': 'man',
 'Joe Doerksen': 'man',
 'Josefine Knutsson': 'woman',
 'Shohei Nose': 'man',
 'Marek Bujlo': 'man',
 'Diego Lopes': 'man',
 'Mick Parkin': 'man',
 'Sean Brady': 'man',
 'Chepe Mariscal': 'man',
 'Danny Silva': 'man',
 'Daniel Marcos': 'man',
 'Tyron Woodley': 'man',
 'Nyamjargal Tumendemberel': 'man',
 'Ken Shamrock': 'man',
 'Carla Esparza': 'woman',
 'Akira Corassani': 'man',
 'Austen Lane': 'man',
 'Thiago Santos': 'man',
 'Mauricio Ruffy': 'man',
 'Yuneisy Duben': 'woman',
 'Soa Palelei': 'man',
 'Dakota Bush': 'man',

In [15]:
df_test = df_to_separate[df_to_separate["file"] == "news_bonus-coverage-2025-performance-fight-of-the-night.txt"]
df_test

,file,text,doc,people
90,news_bonus-coverage-2025-performance-fight-of-...,What a way to close out 2025. In a year define...,"(What, a, way, to, close, out, 2025, ., In, a,...","[(Jamey, -, Lyn, Horth), (Tereza, Bledá), (Ste..."

In [27]:
def get_chain_gender_from_pronouns(chain: Chain, doc: Doc):
    for mention in chain:
        token = doc[mention.root_index]

        if token.lemma_ == "he" or token.lemma_ == "his":
            return "man"
        elif token.lemma_ == "she" or token.lemma_ == "her" or token.lemma_ == "hers":
            return "woman"

    return None

In [ ]:
def get_coreference_genders(row: pd.Series):
    doc: Doc = row["doc"]

    people: set[str] = set([person.text for person in row["people"]])

    doc_genders_map: dict[str, str] = {}

    for person in people:
        if person in genders_map.keys():
            doc_genders_map[person] = genders_map[person]

            name_components = person.split()
            
            if len(name_components) >= 2:
                for component in name_components:
                    doc_genders_map[component] = genders_map[person]

    chains: ChainHolder = doc._.coref_chains
    
    def loop():
        for chain in chains:
            chain_pronouns_gender = get_chain_gender_from_pronouns(chain, doc)

            # If the chain explicitly has gendered pronouns,
            # then we can mark the entire chain with that gender.
            # Otherwise, we need to look it up in the map
            if chain_pronouns_gender == "man":
                for mention in chain:
                    token = doc[mention.root_index]
                    yield (token, "man")
            elif chain_pronouns_gender == "woman":
                for mention in chain:
                    token = doc[mention.root_index]
                    yield (token, "woman")
            else:
                main_item_mention = chain[chain.most_specific_mention_index]
                main_item = doc[main_item_mention.root_index]
                
                if main_item.text in doc_genders_map:
                    for mention in chain:
                        token = doc[mention.root_index]
                        yield (token, doc_genders_map[main_item.text])
    
    return list(loop())

In [30]:
df_to_separate["coreference_genders"] = df_to_separate.apply(get_coreference_genders, axis="columns")

In [31]:
def get_people_with_gender(row: pd.Series, gender: str):
    doc: Doc = row["doc"]
    people: list[Span] = row["people"]
    coreference_genders: list[tuple[Token, str]] = row["coreference_genders"]

    people_with_gender = [p for p in people if genders_map.get(p.text) == gender]
    coreferences_with_gender = [p for p, g in coreference_genders if g == gender]
    coreferences_with_gender = [Span(doc, p.i, p.i + 1) for p in coreferences_with_gender]
    
    return set(people_with_gender + coreferences_with_gender)

In [32]:
df_to_separate["men"] = df_to_separate.apply(get_people_with_gender, args=("man",), axis="columns")
df_to_separate["women"] = df_to_separate.apply(get_people_with_gender, args=("woman",), axis="columns")

In [33]:
def get_paragraph_boundaries(doc: Doc):
    line_breaks = [token for token in doc if token.text == "\n"]
    line_break_indexes = [lb.i for lb in line_breaks]
    paragraph_boundaries = list(zip([0] + line_break_indexes, line_break_indexes + [len(doc)]))
    return paragraph_boundaries

In [34]:
df_to_separate["paragraph_boundaries"] = df_to_separate["doc"].apply(get_paragraph_boundaries)

In [35]:
def count_genders_in_paragraphs(row: pd.Series, gender: str):
    people_with_gender: set[Span] = row[gender]
    paragraph_boundaries: list[tuple[int, int]] = row["paragraph_boundaries"]

    def count_gender_in_paragraph(boundary: tuple[int, int]):
        start, end = boundary
        count = 0

        for person in people_with_gender:
            if person.end >= end:
                continue
            elif person.start < start:
                continue
            
            count += 1

        return count

    return [count_gender_in_paragraph(boundary) for boundary in paragraph_boundaries]

In [36]:
df_to_separate["men_per_paragraph"] = df_to_separate.apply(count_genders_in_paragraphs, args=("men",), axis="columns")
df_to_separate["women_per_paragraph"] = df_to_separate.apply(count_genders_in_paragraphs, args=("women",), axis="columns")

In [37]:
def assign_gender_to_paragraphs(row: pd.Series):
    men_per_paragraph: list[int] = row["men_per_paragraph"]
    women_per_paragraph: list[int] = row["women_per_paragraph"]

    def choose_gender(m: int, f: int):
        if m == 0 and f == 0:
            return None
        elif m > f:
            return "man"
        elif f > m:
            return "woman"
        else: 
            return "equal"

    return [choose_gender(m, f) for m, f in zip(men_per_paragraph, women_per_paragraph)]

In [38]:
df_to_separate["paragraph_genders"] = df_to_separate.apply(assign_gender_to_paragraphs, axis="columns")

In [39]:
def get_paragraphs_with_gender(row: pd.Series, gender: str):
    doc: Doc = row["doc"]
    paragraph_boundaries: list[tuple[int, int]] = row["paragraph_boundaries"]
    paragraph_genders: list[str | None] = row["paragraph_genders"]

    paragraphs_indexes_with_gender = [i for i, g in enumerate(paragraph_genders) if g == gender]
    paragraphs_boundaries_with_gender = [paragraph_boundaries[i] for i in paragraphs_indexes_with_gender]
    paragraphs_with_gender = [doc[start:end] for start, end in paragraphs_boundaries_with_gender]

    return paragraphs_with_gender

In [40]:
df_to_separate["man_paragraphs"] = df_to_separate.apply(get_paragraphs_with_gender, args=("man",), axis="columns")
df_to_separate["woman_paragraphs"] = df_to_separate.apply(get_paragraphs_with_gender, args=("woman",), axis="columns")
df_to_separate["equal_paragraphs"] = df_to_separate.apply(get_paragraphs_with_gender, args=("equal",), axis="columns")
df_to_separate["genderless_paragraphs"] = df_to_separate.apply(get_paragraphs_with_gender, args=(None,), axis="columns")
df_to_separate

,file,text,doc,people,coreference_genders,men,women,paragraph_boundaries,men_per_paragraph,women_per_paragraph,paragraph_genders,man_paragraphs,woman_paragraphs,equal_paragraphs,genderless_paragraphs
0,news_10-get-ready-for-a-november-to-remember-i...,"November is stacked. Normally, I would look to...","(November, is, stacked, ., Normally, ,, I, wou...","[(Ketlen, Vieira), (Norma, Dumont), (Vieira), ...","[(Vieira, woman), (Vieira, woman), (her, woman...","{(Shavkat, Rakhmonov), (Garcia), (Morales), (h...","{(Erin, Blanchfield), (Pennington), (her), (Du...","[(0, 67), (67, 103), (103, 112), (112, 153), (...","[0, 0, 0, 0, 0, 0, 0, 5, 7, 9, 0, 3, 6, 7, 0, ...","[0, 0, 0, 4, 10, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0,...","[None, None, None, woman, woman, woman, woman,...","[(\n, Steve, Garcia, and, David, Onama, clash,...","[(\n, You, know, it, ’s, a, loaded, month, whe...",[],"[(November, is, stacked, ., Normally, ,, I, wo..."
1,news_10-june-schedule-jam-packed-goodness.txt,"Buckle up, kids, because the June schedule is ...","(Buckle, up, ,, kids, ,, because, the, June, s...","[(Mario, Bautista), (Bautista), (Ricky, Simon)...","[(Bautista, man), (Bautista, man), (him, man),...","{(his), (Nurmagomedov), (Brandon, Royval), (Mo...","{(Harrison), (she), (Namajunas), (Pena), (Ketl...","[(0, 14), (14, 94), (94, 164), (164, 174), (17...","[0, 0, 0, 0, 0, 2, 7, 3, 1, 0, 0, 0, 0, 0, 2, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 7, 8, 1, 0, ...","[None, None, None, None, None, man, man, man, ...","[(\n, A, couple, fights, before, the, bantamwe...","[(\n, Julianna, Peña, seeks, to, successfully,...",[],"[(Buckle, up, ,, kids, ,, because, the, June, ..."
2,news_10-massive-fights-schedule-may.txt,There are all kinds of different ways to look ...,"(There, are, all, kinds, of, different, ways, ...","[(Bo, Nickal), (Gerald, Meerschaert), (Kevin, ...","[(Holland, man), (his, man), (he, man), (conte...","{(his), (his), (Sandhagen), (Gilbert, Burns), ...","{(Jasudavicius), (Shevchenko), (She), (Manon, ...","[(0, 41), (41, 78), (78, 133), (133, 172), (17...","[0, 0, 0, 0, 0, 0, 1, 7, 7, 2, 4, 12, 7, 3, 0,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, ...","[None, None, None, None, None, None, man, man,...","[(\n, While, both, Reinier, de, Ridder, and, B...","[(\n, Jessica, Andrade, and, Jasmine, Jasudavi...",[],"[(There, are, all, kinds, of, different, ways,..."
3,news_10-memorable-moments-down-under.txt,"On Saturday, February 8, the UFC returns to Qu...","(On, Saturday, ,, February, 8, ,, the, UFC, re...","[(Alexander, Volkanovski), (Adesanya), (Dan, H...","[(Weili, woman), (her, woman), (Velasquez, man...","{(his), (Whittaker), (his), (Whittaker), (Whit...","{(Holm), (Reneau), (person), (Ronda, Rousey), ...","[(0, 30), (30, 67), (67, 159), (159, 220), (22...","[0, 0, 3, 2, 4, 5, 3, 5, 9, 5, 3, 0, 0, 0, 0, ...","[0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, None, man, woman, man, man, man, man, m...","[(\n, Over, the, years, ,, the, stops, in, Syd...","[(\n, As, we, ready, to, see, Zhang, Weili, de...",[],"[(On, Saturday, ,, February, 8, ,, the, UFC, r..."
4,news_10-middleweights-biggest-championship-mom...,Fourteen individuals have held the UFC middlew...,"(Fourteen, individuals, have, held, the, UFC, ...","[(Dave, Menne), (Gil, Castillo), (Dricus, Du, ...","[(Franklin, man), (Franklin, man), (ambassador...","{(He), (Chris, Leben), (he), (he), (Rich, Fran...",{},"[(0, 67), (67, 118), (118, 166), (166, 181), (...","[4, 0, 0, 3, 0, 7, 7, 6, 6, 3, 0, 4, 4, 10, 1,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[man, None, None, man, None, man, man, man, ma...","[(Fourteen, individuals, have, held, the, UFC,...",[],[],"[(\n, While, it, never, profiled, as, the, gla..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
876,news_zhang-mingyang-embracing-spotlight-ufc-sh...,Zhang Mingyang has all the makings of a potent...,"(Zhang, Mingyang, has, all, the, makings, of, ...","[(Zhang, Mingyang), (Brendson, Ribeiro), (Ozzy...","[(man, man), (he, man), (him, man), (he, man),...","{(he), (his), (he), (man), (himself), (him), (...","{(Zhang, Weili), (Jéssica, Andrade)}","[(0, 11), (11, 110), (110, 129), (129, 133), (...","[1, 9, 1, 0, 0, 5, 2, 1, 2, 4, 2, 0, 5]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0]","[man, man, man, None, None, man, man, man, man...","[(Zhang, Mingyang, has, all, the, makings, of,...",[],"[(\n, Beating, Walker, opens, myriad, doors, f...","[(\n, Star, power, .), (\n, “, I, ’m, very, ha..."
877,news_zhang-mingyang-journey-main-event-light-h...,Zhang Mingyang first entered the UFC ecosystem...,"(Zhang, Mingyang, first, entered, the, UFC, ec...","[(Zhang, Mingyang), (Tuko, Tokkos), (Zhang), (...","[(Mingyang, man), (he, man), (Zhang, man), (Zh...","{(Zhang), (Zhang), (his), (he), (Walker), (him...",{},"[(0, 65), (65, 180), (180, 301), (301, 404), (...","[4, 9, 6, 10, 9, 9, 8, 3]","[0, 0, 0, 0, 0, 0, 0, 0]","[man, man, man, man, man, man, man, man]","[(Zhang, Mingyang, first, entered, the, UFC, e...",[],[],[]
878,news_zhang-weili-big-challenge-apple-vechain-u...,Zhang Weili knows all bout fighting in UFC tit...,"(Zhang, Weili, knows, all, bout, fighting, in,...","[(Zhang, Weili), (Zhang), (Valentine, Shevchen...","[(Weili, woman), (her, woman), (her, woman), (...",{},"{(Rose, Namajunas), (Weili), (she), (women), (...","[(0, 31), (31, 63), (63, 114), (114, 161), (16...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[4, 2, 0, 7, 1, 1, 0, 0, 2, 3, 4, 3, 2, 7, 5, ...","[woman, woman, None, woman, woman, woman, None...",[],"[(Zhang, Weili, knows, all, bout, fighting, in...",[],"[(\n, Their, co, -, main, event, title, fight,..."
879,news_zhang-weili-builds-her-case-goat-status.txt,,(),[],[],{},{},"[(0, 0)]",[0],[0],[None],[],[],[],[()]
880,news_zhang-weili-built-different-ufc-312.txt,If you ever wondered what separates the all-ti...,"(If, you, ever, wondered, what, separates, the...","[(Zhang, Weili), (Tatiana, Suarez), (Zhang), (...","[(Weili, woman), (her, woman), (her, woman), (...",{},"{(she), (Yan, Xiaonan), (she), (Alexa, Grasso)...","[(0, 39), (39, 97), (97, 161), (161, 224), (22...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 5, 1, 2, 1, 9, 4, 2, 4, 3, 15, 4, 5, 7,...","[None, None, woman, woman, woman, woman, woman...",[],"[(\n, That, ’s, the, way, strawweight, champio...",[],"[(If, you, ever, wondered, what, separates, th..."

In [41]:
def save_separate_paragraphs(row: pd.Series):
    original_file: str = row["file"]
    new_folder = original_file.replace(".txt", "")

    os.makedirs(f"./articles/{new_folder}", exist_ok=True)

    man_paragraphs: list[Span] = row["man_paragraphs"]
    man_text = "\n".join([p.text for p in man_paragraphs])

    with open(f"./articles/{new_folder}/man.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(man_text)

    woman_paragraphs: list[Span] = row["woman_paragraphs"]
    woman_text = "\n".join([p.text for p in woman_paragraphs])

    with open(f"./articles/{new_folder}/woman.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(woman_text)

    equal_paragraphs: list[Span] = row["equal_paragraphs"]
    equal_text = "\n".join([p.text for p in equal_paragraphs])

    with open(f"./articles/{new_folder}/equal.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(equal_text)

    genderless_paragraphs: list[Span] = row["genderless_paragraphs"]
    genderless_text = "\n".join([p.text for p in genderless_paragraphs])

    with open(f"./articles/{new_folder}/genderless.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(genderless_text)

In [42]:
df_to_separate.apply(save_separate_paragraphs, axis="columns")

0      None
1      None
2      None
3      None
4      None
       ...
876    None
877    None
878    None
879    None
880    None
Length: 881, dtype: object