In [30]:
import os
import re
from datetime import datetime
from itertools import chain
from concurrent.futures import ThreadPoolExecutor
import pandas as pd
import spacy
from spacy.tokens.doc import Doc
from spacy.tokens.span import Span
from spacy.tokens.token import Token
import coreferee
from coreferee.data_model import ChainHolder
from helpers import get_request
from bs4 import BeautifulSoup
from bs4.element import Tag

In [2]:
nlp = spacy.load("en_core_web_lg")
nlp.add_pipe("coreferee")

In [3]:
def get_text_from_file(path: str):
    text = ""
    
    try:
        with open(path, "r", encoding="utf8") as file:
            text = file.read()
    except Exception as e:
        print("Error reading file", path)
        print(e)
    finally:
        return text

In [4]:
articles_folder = "./articles"

In [5]:
article_files = os.listdir(articles_folder)
article_files = [file for file in article_files if file.endswith(".txt")]

In [6]:
texts = [get_text_from_file(f"{articles_folder}/{file}") for file in article_files]

df = pd.DataFrame(data={
    "file": article_files,
    "text": texts
})
df

,file,text
0,news_10-get-ready-for-a-november-to-remember-i...,"November is stacked. Normally, I would look to..."
1,news_10-june-schedule-jam-packed-goodness.txt,"Buckle up, kids, because the June schedule is ..."
2,news_10-massive-fights-schedule-may.txt,There are all kinds of different ways to look ...
3,news_10-memorable-moments-down-under.txt,"On Saturday, February 8, the UFC returns to Qu..."
4,news_10-middleweights-biggest-championship-mom...,Fourteen individuals have held the UFC middlew...
...,...,...
761,news_zhang-mingyang-all-gas-no-brakes-ufc-kans...,Rising Chinese star Zhang Mingyang has a stat ...
762,news_zhang-mingyang-embracing-spotlight-ufc-sh...,Zhang Mingyang has all the makings of a potent...
763,news_zhang-mingyang-journey-main-event-light-h...,Zhang Mingyang first entered the UFC ecosystem...
764,news_zhang-weili-builds-her-case-goat-status.txt,
765,news_zhang-weili-built-different-ufc-312.txt,If you ever wondered what separates the all-ti...

In [7]:
def already_split_gender_paragraphs(article_file: str):
    gender_paragraphs_folder = f"{articles_folder}/{article_file.replace('.txt', '')}"
    return os.path.exists(gender_paragraphs_folder)

In [8]:
# Since this step is very resource intensive, we only want to
# run it on articles that haven't already been split on gender
df_to_separate = df[~df["file"].apply(already_split_gender_paragraphs)].copy()
df_to_separate

,file,text
0,news_10-get-ready-for-a-november-to-remember-i...,"November is stacked. Normally, I would look to..."
14,news_adrian-yanez-reloaded-ufc-vegas-111.txt,The first two years of Adrian Yanez’ UFC caree...
30,news_alice-ardelean-is-planning-her-big-move-u...,Alice Ardelean remains close to her Romanian r...
43,news_ante-delija-making-waves.txt,Making an immediate impact in the UFC is a cha...
67,news_bigger-picture-ufc-321-aspinall-vs-gane.txt,The UFC’s annual October pay-per-view event in...
110,news_chris-padilla-blocking-out-the-noise-ufc-...,"For Chris Padilla, it doesn’t matter where he ..."
111,news_christian-leroy-duncan-settled-and-starti...,Here’s a very simple truth that doesn’t get ac...
154,news_david-onama-excited-but-also-expected-veg...,David Onama hadn’t been to sign posters for th...
163,news_donte-johnson-clocking-in-ufc-vegas-110.txt,Donte Johnson claimed his place on the UFC ros...
205,news_fight-by-fight-preview-ufc-321-aspinall-v...,The UFC makes its second trip to Abu Dhabi thi...
208,news_fight-by-fight-preview-ufc-fight-night-ga...,The action returns to UFC APEX this Saturday f...
223,news_fight-fight-preview-ufc-fight-night-bonfi...,"Halloween just passed, which means chances are..."
241,news_fighters-on-the-rise-ufc-fight-night-bonf...,Now that we’ve entered the penultimate month o...
257,news_fighters-rise-ufc-fight-night-garcia-vs-o...,Fatima Kline. Jean Silva. David Martinez. Aiem...
280,news_gabriel-bonfim-leveled-up-legend-ufc-vega...,It’s often said that fighters learn more from ...
359,news_joseph-morales-all-way-back-ufc-vegas-111...,Joseph Morales didn’t really celebrate his vic...
371,news_junyong-park-hungry-for-more-ufc-321.txt,Upon sitting down to speak with JunYong Park e...
387,news_ketlen-vieira-ready-claim-title-ufc-vegas...,"Ketlen Vieira has been in the UFC since 2016, ..."
460,news_malcolm-wellmaker-built-ground-bantamweig...,"Earlier this year, bantamweight Malcolm Wellma..."
495,news_matt-schnell-honest-excited-and-dangerous...,Matt Schnell is an interviewer’s dream; you as...
533,news_monthly-report-october-2025-ufc-jourdain-...,The UFC is in that non-stop part of the fall s...
552,news_norma-dumont-done-waiting-around-ufc-figh...,"Last September, Norma Dumont waltzed into the ..."
570,news_phil-rowe-tired-of-fighting-himself-ufc-v...,Phil Rowe sat at the table stationed in the me...
615,news_randy-brown-something-bigger-ufc-fight-ni...,Randy Brown has been waiting for this moment f...
650,news_scorecard-ufc-fight-night-garcia-vs-onama...,The Octagon returned home on Saturday night as...
659,news_seriously-do-not-blink-when-tom-aspinall-...,Few titles in combat sports carry the same pom...
676,news_steve-garcia-real-recognizes-real-ufc-fig...,Steve Garcia’s career is currently bookended b...
684,news_tecia-pennington-crossroad-ufc-fight-nigh...,Tecia Pennington heads into her fight with Den...
700,news_the-tao-of-allan-nascimento-ufc-vegas-110...,If you were to write out a list of the most sk...
701,news_themba-gorimbo-welcome-to-the-mamba-show-...,Themba Gorimbo is keeping things short and swe...
713,news_ufc-321-aspinall-vs-gane-event-tonight-ma...,The UFC 321 pay-per-view main card at Etihad A...
714,news_ufc-321-aspinall-vs-gane-event-tonight-pr...,The UFC returned to Etihad Arena in Abu Dhabi ...
715,news_ufc-fight-night-garcia-vs-onama-main-card...,Following an entertaining preliminary card sla...
716,news_ufc-fight-night-garcia-vs-onama-prelim-re...,The action returned to UFC APEX on Saturday fo...
726,news_uros-medic-back-track-ufc-fight-night-bon...,"At the start of 2025, Uroš Medić set himself t..."
734,news_waldo-cortes-acosta-be-more-waldo-ufc-veg...,Waldo Cortes Acosta goes by the fighting monik...
753,news_yadier-del-valle-no-fear-ufc-vegas-110.txt,The present and forthcoming generation of tale...

In [9]:
# This takes a long time, so have patience
df_to_separate["doc"] = list(nlp.pipe(df_to_separate["text"]))

In [10]:
def get_people(doc: Doc):
    return [ent for ent in doc.ents if ent.label_ == "PERSON"]

In [11]:
df_to_separate["people"] = df_to_separate["doc"].apply(get_people)

In [45]:
all_people: list[Span] = list(chain.from_iterable(df_to_separate["people"]))
all_names = set(p.text for p in all_people)
full_names = set(name for name in all_names 
                 if 
                 len(name.split()) >= 2 
                 and len(name.split()) <= 3
                 and re.search("^[a-zA-Z\u00C0-\u017F\s’]+$", name) is not None)

full_names

{'Addison Barger’s',
 'Adrian Yanez',
 'Adrian Yanez’ UFC',
 'Aiemann Zahabi',
 'Aleksandar Rakic',
 'Aleksandar Rakić',
 'Alex Pereira',
 'Alexa Grasso',
 'Alexander Volkov',
 'Alexandre Pantoja',
 'Alice Ardelean',
 'Allan Nascimento',
 'Amanda Lemos',
 'Amanda Nunes',
 'Amanda Ribas',
 'Anderson Silva',
 'Andre Lima',
 'Andre Muniz',
 'Andreas Gustafsson',
 'Andrei Arlovski',
 'Andrey Pulyaev',
 'Ange Loosa',
 'Angela Hill',
 'Ante Delija',
 'Ariane Carnelossi',
 'Arman Tsarukyan',
 'Aspen Ladd',
 'Asu Almabayev',
 'Ateba Gautier',
 'Austin Vanderford',
 'Azamat Murzakanov',
 'Azat Maksum',
 'Bantamweights Miles Johns',
 'Battering Aldana',
 'Belal Muhammad',
 'Benoît Saint Denis',
 'Bia Mesquita',
 'Billy Elekana',
 'Brazilian Ketlen Vieira',
 'Brendon Marotte',
 'Bruna Brasil',
 'Brunno Ferreira',
 'Bryan Battle',
 'Bueno Silva',
 'Calvin Kattar',
 'Cameron Saaiman',
 'Cameron Smotherman',
 'Carla Esparza',
 'Carlos Hernandez',
 'Carlos Leal',
 'Carlos Prates',
 'Carlos Ulberg',
 'Carlston Harris',
 'Chael Sonnen',
 'ChangHo Lee',
 'Charles Oliveira',
 'Charles Radtke',
 'Chase Hooper',
 'Cheyanne Vlismas',
 'Chris Barnett',
 'Chris Duncan',
 'Chris Gutierrez',
 'Chris Padilla',
 'Christian Leroy Duncan',
 'Christian Rodriguez',
 'Chuck Buffalo',
 'Ciryl Gane',
 'Clayton Carpenter',
 'Cody Durden',
 'Cody Garbrandt',
 'Cody Haddon',
 'Conejo Ruiz',
 'Connor Matthews',
 'Conor McGregor',
 'Cortes Acosta',
 'Cory Sandhagen',
 'Craig Jones',
 'Cristian Quinonez',
 'Curtis Blaydes',
 'Dan Hooker',
 'Dana White',
 'Dana White’s',
 'Dana Whtie’s',
 'Daniel Cormier',
 'Daniel Frunza',
 'Daniel Marcos',
 'Daniel Santos',
 'Darion Abbey',
 'Davey Grant',
 'David Martinez',
 'David Onama',
 'David Onama\nLocation',
 'Deiveson Figueiredo',
 'Della Maddalena',
 'Della Maddalena’s',
 'Denise Gomes',
 'Derrick Lewis',
 'Donte Johnson',
 'Dustin Poirier',
 'Edmen Shahbazyan',
 'Edson Barboza',
 'Eduardo Chapolin',
 'Elise Reed',
 'Eric Shelton',
 'Erin Blanchfield',
 'Eryk Anders',
 'Esteban Ribovics',
 'Fatima Kline',
 'Felice Herrig',
 'Felicia Spencer',
 'Felipe Lima',
 'Fernie Garcia',
 'Finishing Wells',
 'Francis Marshall',
 'Francisco Grasso',
 'Gabriel Benitez',
 'Gabriel Bonfim',
 'Gabriel Sayeg',
 'Garrett Armfield',
 'Germaine de Randamie',
 'Giga Chikadze',
 'Gilbert Burns',
 'Gilbert Urbina',
 'Gordon Ryan',
 'Gregory Rodrigues',
 'Guilherme Uriel',
 'Hamdy Abdelwahab',
 'Herb Dean',
 'Holly Holm',
 'Hyder Amil',
 'Ian Machado',
 'Ian Machado Garry',
 'Ibo Aslan',
 'Ihor Potieria',
 'Ikram Aliskerov',
 'Ilia Topuria',
 'Imanol Rodriguez',
 'Irene Aldana',
 'Isaac Dulgarian',
 'Islam Makhachev',
 'Ismael Bonfim',
 'Ismail Naurdiev',
 'Jack Della Maddalena',
 'Jackson McVey',
 'Jacqueline Cavalcanti',
 'Jafel Filho',
 'Jai Herbert',
 'Jailton Almeida',
 'Jairzinho Rozenstruik',
 'Jake Hadley',
 'Jake Matthews',
 'Jamall Emmers',
 'Jaqueline Amorim',
 'Jared Gordon',
 'Jasmine Jasudavicius',
 'Jason Herzog',
 'Jason Witt',
 'Javid Basharat',
 'Jean Matsumoto',
 'Jean Silva',
 'JeongYeong Lee',
 'Jeremiah Wells',
 'Jessica Andrade',
 'Jimmy Flick',
 'Jiri Prochazka',
 'Jiří Procházka',
 'Joanna Jedrzejczyk',
 'Jon Anik',
 'Jon Jones',
 'Jonathan Martinez',
 'Jorge Masvidal',
 'Jose Aldo',
 'Jose Miguel Delgado',
 'Joseph Morales',
 'Josh Emmett',
 'Josh Hokit',
 'Joshua Van',
 'Julianna Pena',
 'JunYong Park',
 'Kaan Ofli',
 'Karol Rosa',
 'Kayla Harrison',
 'Kennedy Nzechukwu',
 'Ketlen Vieira',
 'Kevin Christian',
 'Khamzat Chimaev',
 'Khaos Williams',
 'Kris Moutinho',
 'Kru Alin',
 'Kru Bob Perez',
 'Kyle Nelson',
 'Kyoji Horiguchi',
 'Leon Edwards',
 'Leroy Duncan',
 'Loopy Godinez',
 'Louie Sutherland',
 'Luana Pinheiro',
 'Ludovit Klein',
 'Machado Garry',
 'Mackenzie Dern',
 'Macy Chiasson',
 'Magomed Ankalaev',
 'Malcolm Wellmaker',
 'Manel Kape',
 'Manon Fiorot',
 'Marc Goddard',
 'Marc Montoya',
 'Marcin Tybura',
 'Marco Tulio',
 'Marina Rodriguez',
 'Mario Bautista',
 'Marlon Vera',
 'Mateusz Gamrot',
 'Mateusz Rebecki',
 'Matt Schnell',
 'Matthew Semelsberger',
 'Matthieu Duclos',
 'Mauricio Ruffy',
 'Max Gimenis square',
 'Max Griffin',
 'Max Holloway',
 'Maycee Barber',
 'Mayra Bueno Silva',
 'Melissa Croden',
 'Melissa Martinez',
 'Merab Dvalishvili',
 'Michael Chiesa',
 'Michael Morales',
 'Michal Oleksiejczuk',
 'Miesha Tate',
 'Mighty Mouse',
 'Mike Malott',
 'Mike Roach',
 'Mitch Raposo',
 'Mitch Raposo square',
 'Mohammed Usman',
 'Montel Jackson',
 'Nate Landwehr',
 'Nathaniel Wood',
 'Nazim Sadkyhov',
 'Nazim Sadykhov',
 'Neil Magny',
 'Nick Diaz',
 'Nick Klein',
 'Nicky Rod',
 'Nicolas Dalby',
 'Niko Price',
 'Nikolay Veretennikov',
 'Norma Dumont',
 'Oban Elliott',
 'Paige VanZant',
 'Payton Talbott',
 'Pearl Gonzalez',
 'Pete Rodriguez',
 'Petr Yan',
 'Phil Rowe',
 'Piera Rodriguez',
 'Punahele Soriano',
 'Puro Osso',
 'Quillan Salkilld',
 'Rafael Estevam',
 'Rafael Fiziev',
 'Ramiz Brahimaj',
 'Randy Brown',
 'Randy Brown\n',
 'Raoni Barcelos',
 'Raquel Pennington',
 'Rayanne dos Santos',
 'Rhys McKee',
 'Ricardo Ramos',
 'Rich Mitchell',
 'Ricky Simon',
 'Robert Valentin',
 'Robert Whittaker',
 'Roberto Romero',
 'Roberto Sanchez',
 'Rose Namajunas',
 'Ryan Loder',
 'Ryan Spann',
 'Saul Soliz',
 'Sayif Saud',
 'Sean O’Malley',
 'Sedriques Dumas',
 'Seokhyeon Ko',
 'Sergei Pavlovich',
 'Serghei Spivac',
 'Serhiy Sidey',
 'Shauna Bannon',
 'Shavkat Rakhmonov',
 'Simone Biles',
 'Slovakian Ludovit Klein',
 'Song Kenan',
 'Stephen Thompson',
 'Steve Garcia',
 'Stipe Miocic',
 'Tabatha Ricci',
 'Tagir Ulanbekov',
 'Tainara Lisboa',
 'Talita Alencar',
 'Tatiana Suarez',
 'Tecia Pennington',
 'Terry Etim',
 'Thomas Gerbasi',
 'Thomas Petersen',
 'Tim Elliott',
 'Timmy Cuamba',
 'Tom Aspinall',
 'Torrez Finney',
 'Tracy Cortez',
 'Tresean Gore',
 'Tre’Stone Vines',
 'Umar Nurmagomedov',
 'Uroš Medić',
 'Valentina Shevchenko',
 'Valter Walker',
 'VeChain UFC',
 'Vicente Luque',
 'Victor Henry',
 'Virna Jandiroba',
 'Vitor Petrino',
 'Viviane Araujo',
 'Waldo Cortes Acosta',
 'William Gomis',
 'Xiao Long',
 'Yadier del Valle',
 'Yan Xiaonan',
 'Yanal Ashmouz',
 'Yazmin Jauregui',
 'Yorgan De Castro',
 'Yousri Belgaroui',
 'Youssef Zalal',
 'Zach Reese',
 'Zhang Weili',
 'bantamweights Ricky Simon',
 'de Randamie',
 'jiu jitsu',
 'tokui waza'}

In [14]:
def is_woman_tag(tag: Tag):
    text = tag.get_text().strip().lower()
    return "woman" in text or "women" in text

def find_gender_on_ufc(name: str):
    name_query = "-".join(name.split()).replace('’', ' ')
    url = f"https://www.ufc.com/athlete/{name_query}"

    try:
        response = get_request(url)
        soup = BeautifulSoup(response.text, "html.parser")

        tags: list[Tag] = soup.find_all("p", "hero-profile__tag")
        if not tags:
            return None

        is_woman = any([is_woman_tag(tag) for tag in tags])
        if is_woman:
            return "woman"
        else:
            return "man"
    except Exception as e:
        print("Error getting gender of", name)
        print(e)

In [ ]:
# Set this to False if you want to fetch the genders from the UFC website
use_saved_gender_map = False
genders_map_file = "./genders_map.csv"

if use_saved_gender_map and os.path.exists(genders_map_file):
    name_gender_pairs_df = pd.read_csv(genders_map_file)
    genders_map: dict[str, str] = dict(zip(name_gender_pairs_df["name"], name_gender_pairs_df["gender"]))
else:
    def get_name_gender_pair_on_ufc(name: str):
        return (name, find_gender_on_ufc(name))

    with ThreadPoolExecutor() as executor:
        name_gender_pairs = [
            (n, g)
            for n, g in executor.map(get_name_gender_pair_on_ufc, full_names)
            if g is not None
        ]

    genders_map = dict(name_gender_pairs)

    for name, gender in name_gender_pairs:
        for name_component in name.split():
            genders_map[name_component] = gender

    pd.DataFrame(data={
        "name": genders_map.keys(),
        "gender": genders_map.values(),
    })\
        .set_index("name")\
        .to_csv(f"./genders_map_{datetime.now().strftime('%d-%m-%y_%H-%M-%S')}.csv")

genders_map

{'Azamat Murzakanov': 'man',
 'Magomed Ankalaev': 'man',
 'Norma Dumont': 'woman',
 'Jared Gordon': 'man',
 'Michael Morales': 'man',
 'Khamzat Chimaev': 'man',
 'Edson Barboza': 'man',
 'Austin Vanderford': 'man',
 'Serghei Spivac': 'man',
 'Rhys McKee': 'man',
 'Azat Maksum': 'man',
 'Michael Chiesa': 'man',
 'Jacqueline Cavalcanti': 'woman',
 'Randy Brown': 'man',
 'Steve Garcia': 'man',
 'Zhang Weili': 'woman',
 'Hyder Amil': 'man',
 'Mitch Raposo': 'man',
 'Roberto Romero': 'man',
 'Melissa Martinez': 'woman',
 'Yadier del Valle': 'man',
 'Karol Rosa': 'woman',
 'Garrett Armfield': 'man',
 'Aleksandar Rakic': 'man',
 'Conor McGregor': 'man',
 'Stephen Thompson': 'man',
 'Deiveson Figueiredo': 'man',
 'Kyoji Horiguchi': 'man',
 'Billy Elekana': 'man',
 'Felice Herrig': 'woman',
 'Mateusz Gamrot': 'man',
 'Josh Hokit': 'man',
 'Pete Rodriguez': 'man',
 'Francis Marshall': 'man',
 'Khaos Williams': 'man',
 'Ryan Spann': 'man',
 'Daniel Marcos': 'man',
 'Bruna Brasil': 'woman',
 'Rafael Fiziev': 'man',
 'Montel Jackson': 'man',
 'Chris Padilla': 'man',
 'Gabriel Benitez': 'man',
 'Joanna Jedrzejczyk': 'woman',
 'Torrez Finney': 'man',
 'Tresean Gore': 'man',
 'Yorgan De Castro': 'man',
 'Talita Alencar': 'woman',
 'Aspen Ladd': 'woman',
 'Tainara Lisboa': 'woman',
 'Song Kenan': 'man',
 'Serhiy Sidey': 'man',
 'Zach Reese': 'man',
 'Manon Fiorot': 'woman',
 'Quillan Salkilld': 'man',
 'Shauna Bannon': 'woman',
 'Carlos Leal': 'man',
 'Jiri Prochazka': 'man',
 'Esteban Ribovics': 'man',
 'Neil Magny': 'man',
 'Brunno Ferreira': 'man',
 'Irene Aldana': 'woman',
 'Ikram Aliskerov': 'man',
 'Mohammed Usman': 'man',
 'Yousri Belgaroui': 'man',
 'Andrei Arlovski': 'man',
 'Viviane Araujo': 'woman',
 'Nazim Sadykhov': 'man',
 'Robert Whittaker': 'man',
 'Tabatha Ricci': 'woman',
 'Christian Leroy Duncan': 'man',
 'Chris Gutierrez': 'man',
 'Jon Jones': 'man',
 'Ariane Carnelossi': 'woman',
 'Ilia Topuria': 'man',
 'Joshua Van': 'man',
 'Tatiana Suarez': 'woman',
 'Merab Dvalishvili': 'man',
 'Nate Landwehr': 'man',
 'Vicente Luque': 'man',
 'Gilbert Burns': 'man',
 'Christian Rodriguez': 'man',
 'Nikolay Veretennikov': 'man',
 'Donte Johnson': 'man',
 'Jafel Filho': 'man',
 'Kennedy Nzechukwu': 'man',
 'Mauricio Ruffy': 'man',
 'Valentina Shevchenko': 'woman',
 'Fatima Kline': 'woman',
 'Curtis Blaydes': 'man',
 'Ramiz Brahimaj': 'man',
 'William Gomis': 'man',
 'Erin Blanchfield': 'woman',
 'Jonathan Martinez': 'man',
 'Yan Xiaonan': 'woman',
 'Sergei Pavlovich': 'man',
 'Derrick Lewis': 'man',
 'Josh Emmett': 'man',
 'Manel Kape': 'man',
 'Victor Henry': 'man',
 'Gabriel Bonfim': 'man',
 'Andre Muniz': 'man',
 'Michal Oleksiejczuk': 'man',
 'Mackenzie Dern': 'woman',
 'Nick Klein': 'man',
 'Piera Rodriguez': 'woman',
 'Holly Holm': 'woman',
 'Jean Matsumoto': 'man',
 'Isaac Dulgarian': 'man',
 'Aiemann Zahabi': 'man',
 'Payton Talbott': 'man',
 'Chris Barnett': 'man',
 'Shavkat Rakhmonov': 'man',
 'Jorge Masvidal': 'man',
 'Andre Lima': 'man',
 'Edmen Shahbazyan': 'man',
 'Connor Matthews': 'man',
 'David Martinez': 'man',
 'Dustin Poirier': 'man',
 'Belal Muhammad': 'man',
 'Jairzinho Rozenstruik': 'man',
 'Max Holloway': 'man',
 'Eryk Anders': 'man',
 'Ricardo Ramos': 'man',
 'Paige VanZant': 'woman',
 'Matt Schnell': 'man',
 'Maycee Barber': 'woman',
 'Cody Garbrandt': 'man',
 'Yanal Ashmouz': 'man',
 'Chris Duncan': 'man',
 'Sedriques Dumas': 'man',
 'Tecia Pennington': 'woman',
 'Tim Elliott': 'man',
 'Miesha Tate': 'woman',
 'Islam Makhachev': 'man',
 'David Onama': 'man',
 'Craig Jones': 'man',
 'Jasmine Jasudavicius': 'woman',
 'Ricky Simon': 'man',
 'Davey Grant': 'man',
 'Cameron Saaiman': 'man',
 'Xiao Long': 'man',
 'Cody Durden': 'man',
 'Angela Hill': 'woman',
 'Cheyanne Vlismas': 'woman',
 'Ketlen Vieira': 'woman',
 'Melissa Croden': 'woman',
 'Eric Shelton': 'man',
 'Loopy Godinez': 'woman',
 'Anderson Silva': 'man',
 'Kyle Nelson': 'man',
 'Mike Malott': 'man',
 'Ange Loosa': 'man',
 'Nick Diaz': 'man',
 'Charles Oliveira': 'man',
 'Jailton Almeida': 'man',
 'Cory Sandhagen': 'man',
 'Niko Price': 'man',
 'Raquel Pennington': 'woman',
 'Jai Herbert': 'man',
 'Terry Etim': 'man',
 'Carlos Ulberg': 'man',
 'Alex Pereira': 'man',
 'Cody Haddon': 'man',
 'Denise Gomes': 'woman',
 'Ryan Loder': 'man',
 'Yazmin Jauregui': 'woman',
 'Ibo Aslan': 'man',
 'Seokhyeon Ko': 'man',
 'Jaqueline Amorim': 'woman',
 'Calvin Kattar': 'man',
 'Andreas Gustafsson': 'man',
 'Jason Witt': 'man',
 'Malcolm Wellmaker': 'man',
 'Jackson McVey': 'man',
 'Virna Jandiroba': 'woman',
 'Jake Matthews': 'man',
 'Raoni Barcelos': 'man',
 'Dan Hooker': 'man',
 'Daniel Cormier': 'man',
 'Joseph Morales': 'man',
 'Thomas Petersen': 'man',
 'Leon Edwards': 'man',
 'Mateusz Rebecki': 'man',
 'Phil Rowe': 'man',
 'Marco Tulio': 'man',
 'Cristian Quinonez': 'man',
 'Chase Hooper': 'man',
 'Mario Bautista': 'man',
 'Alexandre Pantoja': 'man',
 'Jimmy Flick': 'man',
 'Mayra Bueno Silva': 'woman',
 'Elise Reed': 'woman',
 'Jamall Emmers': 'man',
 'JeongYeong Lee': 'man',
 'Tagir Ulanbekov': 'man',
 'Nathaniel Wood': 'man',
 'Ante Delija': 'man',
 'Daniel Frunza': 'man',
 'Alexander Volkov': 'man',
 'Ludovit Klein': 'man',
 'Umar Nurmagomedov': 'man',
 'Jake Hadley': 'man',
 'Andrey Pulyaev': 'man',
 'Macy Chiasson': 'woman',
 'Fernie Garcia': 'man',
 'Cameron Smotherman': 'man',
 'JunYong Park': 'man',
 'Marcin Tybura': 'man',
 'Carlston Harris': 'man',
 'Roberto Sanchez': 'man',
 'Rayanne dos Santos': 'woman',
 'Kaan Ofli': 'man',
 'Allan Nascimento': 'man',
 'Max Griffin': 'man',
 'Gregory Rodrigues': 'man',
 'Jeremiah Wells': 'man',
 'Javid Basharat': 'man',
 'Gilbert Urbina': 'man',
 'Jessica Andrade': 'woman',
 'Ciryl Gane': 'man',
 'Imanol Rodriguez': 'man',
 'Adrian Yanez': 'man',
 'Hamdy Abdelwahab': 'man',
 'Carla Esparza': 'woman',
 'Kris Moutinho': 'man',
 'Waldo Cortes Acosta': 'man',
 'Jean Silva': 'man',
 'Rafael Estevam': 'man',
 'Marina Rodriguez': 'woman',
 'Tracy Cortez': 'woman',
 'Luana Pinheiro': 'woman',
 'Petr Yan': 'man',
 'Oban Elliott': 'man',
 'Kevin Christian': 'man',
 'Tom Aspinall': 'man',
 'Vitor Petrino': 'man',
 'Charles Radtke': 'man',
 'Giga Chikadze': 'man',
 'Ateba Gautier': 'man',
 'Nicolas Dalby': 'man',
 'Arman Tsarukyan': 'man',
 'Ismail Naurdiev': 'man',
 'Germaine de Randamie': 'woman',
 'Ihor Potieria': 'man',
 'Amanda Ribas': 'woman',
 'Clayton Carpenter': 'man',
 'Alexa Grasso': 'woman',
 'Randy Brown\n': 'man',
 'Stipe Miocic': 'man',
 'Kayla Harrison': 'woman',
 'Ismael Bonfim': 'man',
 'Felipe Lima': 'man',
 'Felicia Spencer': 'woman',
 'Carlos Hernandez': 'man',
 'Amanda Nunes': 'woman',
 'Amanda Lemos': 'woman',
 'Daniel Santos': 'man',
 'Valter Walker': 'man',
 'Julianna Pena': 'woman',
 'Youssef Zalal': 'man',
 'Punahele Soriano': 'man',
 'Rose Namajunas': 'woman',
 'Marlon Vera': 'man',
 'Jack Della Maddalena': 'man',
 'Jose Aldo': 'man',
 'Bryan Battle': 'man',
 'Carlos Prates': 'man',
 'Alice Ardelean': 'woman',
 'Brendon Marotte': 'man',
 'Louie Sutherland': 'man',
 'Matthew Semelsberger': 'man',
 'Pearl Gonzalez': 'woman',
 'Azamat': 'man',
 'Murzakanov': 'man',
 'Magomed': 'man',
 'Ankalaev': 'man',
 'Norma': 'woman',
 'Dumont': 'woman',
 'Jared': 'man',
 'Gordon': 'man',
 'Michael': 'man',
 'Morales': 'man',
 'Khamzat': 'man',
 'Chimaev': 'man',
 'Edson': 'man',
 'Barboza': 'man',
 'Austin': 'man',
 'Vanderford': 'man',
 'Serghei': 'man',
 'Spivac': 'man',
 'Rhys': 'man',
 'McKee': 'man',
 'Azat': 'man',
 'Maksum': 'man',
 'Chiesa': 'man',
 'Jacqueline': 'woman',
 'Cavalcanti': 'woman',
 'Randy': 'man',
 'Brown': 'man',
 'Steve': 'man',
 'Garcia': 'man',
 'Zhang': 'woman',
 'Weili': 'woman',
 'Hyder': 'man',
 'Amil': 'man',
 'Mitch': 'man',
 'Raposo': 'man',
 'Roberto': 'man',
 'Romero': 'man',
 'Melissa': 'woman',
 'Martinez': 'man',
 'Yadier': 'man',
 'del': 'man',
 'Valle': 'man',
 'Karol': 'woman',
 'Rosa': 'woman',
 'Garrett': 'man',
 'Armfield': 'man',
 'Aleksandar': 'man',
 'Rakic': 'man',
 'Conor': 'man',
 'McGregor': 'man',
 'Stephen': 'man',
 'Thompson': 'man',
 'Deiveson': 'man',
 'Figueiredo': 'man',
 'Kyoji': 'man',
 'Horiguchi': 'man',
 'Billy': 'man',
 'Elekana': 'man',
 'Felice': 'woman',
 'Herrig': 'woman',
 'Mateusz': 'man',
 'Gamrot': 'man',
 'Josh': 'man',
 'Hokit': 'man',
 'Pete': 'man',
 'Rodriguez': 'woman',
 'Francis': 'man',
 'Marshall': 'man',
 'Khaos': 'man',
 'Williams': 'man',
 'Ryan': 'man',
 'Spann': 'man',
 'Daniel': 'man',
 'Marcos': 'man',
 'Bruna': 'woman',
 'Brasil': 'woman',
 'Rafael': 'man',
 'Fiziev': 'man',
 'Montel': 'man',
 'Jackson': 'man',
 'Chris': 'man',
 'Padilla': 'man',
 'Gabriel': 'man',
 'Benitez': 'man',
 'Joanna': 'woman',
 'Jedrzejczyk': 'woman',
 'Torrez': 'man',
 'Finney': 'man',
 'Tresean': 'man',
 'Gore': 'man',
 'Yorgan': 'man',
 'De': 'man',
 'Castro': 'man',
 'Talita': 'woman',
 'Alencar': 'woman',
 'Aspen': 'woman',
 'Ladd': 'woman',
 'Tainara': 'woman',
 'Lisboa': 'woman',
 'Song': 'man',
 'Kenan': 'man',
 'Serhiy': 'man',
 'Sidey': 'man',
 'Zach': 'man',
 'Reese': 'man',
 'Manon': 'woman',
 'Fiorot': 'woman',
 'Quillan': 'man',
 'Salkilld': 'man',
 'Shauna': 'woman',
 'Bannon': 'woman',
 'Carlos': 'man',
 'Leal': 'man',
 'Jiri': 'man',
 'Prochazka': 'man',
 'Esteban': 'man',
 'Ribovics': 'man',
 'Neil': 'man',
 'Magny': 'man',
 'Brunno': 'man',
 'Ferreira': 'man',
 'Irene': 'woman',
 'Aldana': 'woman',
 'Ikram': 'man',
 'Aliskerov': 'man',
 'Mohammed': 'man',
 'Usman': 'man',
 'Yousri': 'man',
 'Belgaroui': 'man',
 'Andrei': 'man',
 'Arlovski': 'man',
 'Viviane': 'woman',
 'Araujo': 'woman',
 'Nazim': 'man',
 'Sadykhov': 'man',
 'Robert': 'man',
 'Whittaker': 'man',
 'Tabatha': 'woman',
 'Ricci': 'woman',
 'Christian': 'man',
 'Leroy': 'man',
 'Duncan': 'man',
 'Gutierrez': 'man',
 'Jon': 'man',
 'Jones': 'man',
 'Ariane': 'woman',
 'Carnelossi': 'woman',
 'Ilia': 'man',
 'Topuria': 'man',
 'Joshua': 'man',
 'Van': 'man',
 'Tatiana': 'woman',
 'Suarez': 'woman',
 'Merab': 'man',
 'Dvalishvili': 'man',
 'Nate': 'man',
 'Landwehr': 'man',
 'Vicente': 'man',
 'Luque': 'man',
 'Gilbert': 'man',
 'Burns': 'man',
 'Nikolay': 'man',
 'Veretennikov': 'man',
 'Donte': 'man',
 'Johnson': 'man',
 'Jafel': 'man',
 'Filho': 'man',
 'Kennedy': 'man',
 'Nzechukwu': 'man',
 'Mauricio': 'man',
 'Ruffy': 'man',
 'Valentina': 'woman',
 'Shevchenko': 'woman',
 'Fatima': 'woman',
 'Kline': 'woman',
 'Curtis': 'man',
 'Blaydes': 'man',
 'Ramiz': 'man',
 'Brahimaj': 'man',
 'William': 'man',
 'Gomis': 'man',
 'Erin': 'woman',
 'Blanchfield': 'woman',
 'Jonathan': 'man',
 'Yan': 'man',
 'Xiaonan': 'woman',
 'Sergei': 'man',
 'Pavlovich': 'man',
 'Derrick': 'man',
 'Lewis': 'man',
 'Emmett': 'man',
 'Manel': 'man',
 'Kape': 'man',
 'Victor': 'man',
 'Henry': 'man',
 'Bonfim': 'man',
 'Andre': 'man',
 'Muniz': 'man',
 'Michal': 'man',
 'Oleksiejczuk': 'man',
 'Mackenzie': 'woman',
 'Dern': 'woman',
 'Nick': 'man',
 'Klein': 'man',
 'Piera': 'woman',
 'Holly': 'woman',
 'Holm': 'woman',
 'Jean': 'man',
 'Matsumoto': 'man',
 'Isaac': 'man',
 'Dulgarian': 'man',
 'Aiemann': 'man',
 'Zahabi': 'man',
 'Payton': 'man',
 'Talbott': 'man',
 'Barnett': 'man',
 'Shavkat': 'man',
 'Rakhmonov': 'man',
 'Jorge': 'man',
 'Masvidal': 'man',
 'Lima': 'man',
 'Edmen': 'man',
 'Shahbazyan': 'man',
 'Connor': 'man',
 'Matthews': 'man',
 'David': 'man',
 'Dustin': 'man',
 'Poirier': 'man',
 'Belal': 'man',
 'Muhammad': 'man',
 'Jairzinho': 'man',
 'Rozenstruik': 'man',
 'Max': 'man',
 'Holloway': 'man',
 'Eryk': 'man',
 'Anders': 'man',
 'Ricardo': 'man',
 'Ramos': 'man',
 'Paige': 'woman',
 'VanZant': 'woman',
 'Matt': 'man',
 'Schnell': 'man',
 'Maycee': 'woman',
 'Barber': 'woman',
 'Cody': 'man',
 'Garbrandt': 'man',
 'Yanal': 'man',
 'Ashmouz': 'man',
 'Sedriques': 'man',
 'Dumas': 'man',
 'Tecia': 'woman',
 'Pennington': 'woman',
 'Tim': 'man',
 'Elliott': 'man',
 'Miesha': 'woman',
 'Tate': 'woman',
 'Islam': 'man',
 'Makhachev': 'man',
 'Onama': 'man',
 'Craig': 'man',
 'Jasmine': 'woman',
 'Jasudavicius': 'woman',
 'Ricky': 'man',
 'Simon': 'man',
 'Davey': 'man',
 'Grant': 'man',
 'Cameron': 'man',
 'Saaiman': 'man',
 'Xiao': 'man',
 'Long': 'man',
 'Durden': 'man',
 'Angela': 'woman',
 'Hill': 'woman',
 'Cheyanne': 'woman',
 'Vlismas': 'woman',
 'Ketlen': 'woman',
 'Vieira': 'woman',
 'Croden': 'woman',
 'Eric': 'man',
 'Shelton': 'man',
 'Loopy': 'woman',
 'Godinez': 'woman',
 'Anderson': 'man',
 'Silva': 'man',
 'Kyle': 'man',
 'Nelson': 'man',
 'Mike': 'man',
 'Malott': 'man',
 'Ange': 'man',
 'Loosa': 'man',
 'Diaz': 'man',
 'Charles': 'man',
 'Oliveira': 'man',
 'Jailton': 'man',
 'Almeida': 'man',
 'Cory': 'man',
 'Sandhagen': 'man',
 'Niko': 'man',
 'Price': 'man',
 'Raquel': 'woman',
 'Jai': 'man',
 'Herbert': 'man',
 'Terry': 'man',
 'Etim': 'man',
 'Ulberg': 'man',
 'Alex': 'man',
 'Pereira': 'man',
 'Haddon': 'man',
 'Denise': 'woman',
 'Gomes': 'woman',
 'Loder': 'man',
 'Yazmin': 'woman',
 'Jauregui': 'woman',
 'Ibo': 'man',
 'Aslan': 'man',
 'Seokhyeon': 'man',
 'Ko': 'man',
 'Jaqueline': 'woman',
 'Amorim': 'woman',
 'Calvin': 'man',
 'Kattar': 'man',
 'Andreas': 'man',
 'Gustafsson': 'man',
 'Jason': 'man',
 'Witt': 'man',
 'Malcolm': 'man',
 'Wellmaker': 'man',
 'McVey': 'man',
 'Virna': 'woman',
 'Jandiroba': 'woman',
 'Jake': 'man',
 'Raoni': 'man',
 'Barcelos': 'man',
 'Dan': 'man',
 'Hooker': 'man',
 'Cormier': 'man',
 'Joseph': 'man',
 'Thomas': 'man',
 'Petersen': 'man',
 'Leon': 'man',
 'Edwards': 'man',
 'Rebecki': 'man',
 'Phil': 'man',
 'Rowe': 'man',
 'Marco': 'man',
 'Tulio': 'man',
 'Cristian': 'man',
 'Quinonez': 'man',
 'Chase': 'man',
 'Hooper': 'man',
 'Mario': 'man',
 'Bautista': 'man',
 'Alexandre': 'man',
 'Pantoja': 'man',
 'Jimmy': 'man',
 'Flick': 'man',
 'Mayra': 'woman',
 'Bueno': 'woman',
 'Elise': 'woman',
 'Reed': 'woman',
 'Jamall': 'man',
 'Emmers': 'man',
 'JeongYeong': 'man',
 'Lee': 'man',
 'Tagir': 'man',
 'Ulanbekov': 'man',
 'Nathaniel': 'man',
 'Wood': 'man',
 'Ante': 'man',
 'Delija': 'man',
 'Frunza': 'man',
 'Alexander': 'man',
 'Volkov': 'man',
 'Ludovit': 'man',
 'Umar': 'man',
 'Nurmagomedov': 'man',
 'Hadley': 'man',
 'Andrey': 'man',
 'Pulyaev': 'man',
 'Macy': 'woman',
 'Chiasson': 'woman',
 'Fernie': 'man',
 'Smotherman': 'man',
 'JunYong': 'man',
 'Park': 'man',
 'Marcin': 'man',
 'Tybura': 'man',
 'Carlston': 'man',
 'Harris': 'man',
 'Sanchez': 'man',
 'Rayanne': 'woman',
 'dos': 'woman',
 'Santos': 'man',
 'Kaan': 'man',
 'Ofli': 'man',
 'Allan': 'man',
 'Nascimento': 'man',
 'Griffin': 'man',
 'Gregory': 'man',
 'Rodrigues': 'man',
 'Jeremiah': 'man',
 'Wells': 'man',
 'Javid': 'man',
 'Basharat': 'man',
 'Urbina': 'man',
 'Jessica': 'woman',
 'Andrade': 'woman',
 'Ciryl': 'man',
 'Gane': 'man',
 'Imanol': 'man',
 'Adrian': 'man',
 'Yanez': 'man',
 'Hamdy': 'man',
 'Abdelwahab': 'man',
 'Carla': 'woman',
 'Esparza': 'woman',
 'Kris': 'man',
 'Moutinho': 'man',
 'Waldo': 'man',
 'Cortes': 'man',
 'Acosta': 'man',
 'Estevam': 'man',
 'Marina': 'woman',
 'Tracy': 'woman',
 'Cortez': 'woman',
 'Luana': 'woman',
 'Pinheiro': 'woman',
 'Petr': 'man',
 'Oban': 'man',
 'Kevin': 'man',
 'Tom': 'man',
 'Aspinall': 'man',
 'Vitor': 'man',
 'Petrino': 'man',
 'Radtke': 'man',
 'Giga': 'man',
 'Chikadze': 'man',
 'Ateba': 'man',
 'Gautier': 'man',
 'Nicolas': 'man',
 'Dalby': 'man',
 'Arman': 'man',
 'Tsarukyan': 'man',
 'Ismail': 'man',
 'Naurdiev': 'man',
 'Germaine': 'woman',
 'de': 'woman',
 'Randamie': 'woman',
 'Ihor': 'man',
 'Potieria': 'man',
 'Amanda': 'woman',
 'Ribas': 'woman',
 'Clayton': 'man',
 'Carpenter': 'man',
 'Alexa': 'woman',
 'Grasso': 'woman',
 'Stipe': 'man',
 'Miocic': 'man',
 'Kayla': 'woman',
 'Harrison': 'woman',
 'Ismael': 'man',
 'Felipe': 'man',
 'Felicia': 'woman',
 'Spencer': 'woman',
 'Hernandez': 'man',
 'Nunes': 'woman',
 'Lemos': 'woman',
 'Valter': 'man',
 'Walker': 'man',
 'Julianna': 'woman',
 'Pena': 'woman',
 'Youssef': 'man',
 'Zalal': 'man',
 'Punahele': 'man',
 'Soriano': 'man',
 'Rose': 'woman',
 'Namajunas': 'woman',
 'Marlon': 'man',
 'Vera': 'man',
 'Jack': 'man',
 'Della': 'man',
 'Maddalena': 'man',
 'Jose': 'man',
 'Aldo': 'man',
 'Bryan': 'man',
 'Battle': 'man',
 'Prates': 'man',
 'Alice': 'woman',
 'Ardelean': 'woman',
 'Brendon': 'man',
 'Marotte': 'man',
 'Louie': 'man',
 'Sutherland': 'man',
 'Matthew': 'man',
 'Semelsberger': 'man',
 'Pearl': 'woman',
 'Gonzalez': 'woman'}

In [16]:
def get_coreference_genders(row: pd.Series):
    doc: Doc = row["doc"]

    chains: ChainHolder = doc._.coref_chains
    
    def loop():
        for chain in chains:
            main_item_mention = chain[chain.most_specific_mention_index]
            main_item = doc[main_item_mention.root_index]
            
            if main_item.text in genders_map:
                for mention in chain:
                    token = doc[mention.root_index]
                    yield (token, genders_map[main_item.text])
    
    return list(loop())

In [17]:
df_to_separate["coreference_genders"] = df_to_separate.apply(get_coreference_genders, axis="columns")

In [18]:
def get_people_with_gender(row: pd.Series, gender: str):
    doc: Doc = row["doc"]
    people: list[Span] = row["people"]
    coreference_genders: list[tuple[Token, str]] = row["coreference_genders"]

    people_with_gender = [p for p in people if genders_map.get(p.text) == gender]
    coreferences_with_gender = [p for p, g in coreference_genders if g == gender]
    coreferences_with_gender = [Span(doc, p.i, p.i + 1) for p in coreferences_with_gender]
    
    return set(people_with_gender + coreferences_with_gender)

In [19]:
df_to_separate["men"] = df_to_separate.apply(get_people_with_gender, args=("man",), axis="columns")
df_to_separate["women"] = df_to_separate.apply(get_people_with_gender, args=("woman",), axis="columns")

In [20]:
def get_paragraph_boundaries(doc: Doc):
    line_breaks = [token for token in doc if token.text == "\n"]
    line_break_indexes = [lb.i for lb in line_breaks]
    paragraph_boundaries = list(zip([0] + line_break_indexes, line_break_indexes + [len(doc)]))
    return paragraph_boundaries

In [21]:
df_to_separate["paragraph_boundaries"] = df_to_separate["doc"].apply(get_paragraph_boundaries)

In [22]:
def count_genders_in_paragraphs(row: pd.Series, gender: str):
    people_with_gender: set[Span] = row[gender]
    paragraph_boundaries: list[tuple[int, int]] = row["paragraph_boundaries"]

    def count_gender_in_paragraph(boundary: tuple[int, int]):
        start, end = boundary
        count = 0

        for person in people_with_gender:
            if person.end >= end:
                continue
            elif person.start < start:
                continue
            
            count += 1

        return count

    return [count_gender_in_paragraph(boundary) for boundary in paragraph_boundaries]

In [23]:
df_to_separate["men_per_paragraph"] = df_to_separate.apply(count_genders_in_paragraphs, args=("men",), axis="columns")
df_to_separate["women_per_paragraph"] = df_to_separate.apply(count_genders_in_paragraphs, args=("women",), axis="columns")

In [24]:
def assign_gender_to_paragraphs(row: pd.Series):
    men_per_paragraph: list[int] = row["men_per_paragraph"]
    women_per_paragraph: list[int] = row["women_per_paragraph"]

    def choose_gender(m: int, f: int):
        if m == 0 and f == 0:
            return None
        elif m > f:
            return "man"
        elif f > m:
            return "woman"
        else: 
            return "equal"

    return [choose_gender(m, f) for m, f in zip(men_per_paragraph, women_per_paragraph)]

In [25]:
df_to_separate["paragraph_genders"] = df_to_separate.apply(assign_gender_to_paragraphs, axis="columns")

In [26]:
def get_paragraphs_with_gender(row: pd.Series, gender: str):
    doc: Doc = row["doc"]
    paragraph_boundaries: list[tuple[int, int]] = row["paragraph_boundaries"]
    paragraph_genders: list[str | None] = row["paragraph_genders"]

    paragraphs_indexes_with_gender = [i for i, g in enumerate(paragraph_genders) if g == gender]
    paragraphs_boundaries_with_gender = [paragraph_boundaries[i] for i in paragraphs_indexes_with_gender]
    paragraphs_with_gender = [doc[start:end] for start, end in paragraphs_boundaries_with_gender]

    return paragraphs_with_gender

In [27]:
df_to_separate["man_paragraphs"] = df_to_separate.apply(get_paragraphs_with_gender, args=("man",), axis="columns")
df_to_separate["woman_paragraphs"] = df_to_separate.apply(get_paragraphs_with_gender, args=("woman",), axis="columns")
df_to_separate["equal_paragraphs"] = df_to_separate.apply(get_paragraphs_with_gender, args=("equal",), axis="columns")
df_to_separate["genderless_paragraphs"] = df_to_separate.apply(get_paragraphs_with_gender, args=(None,), axis="columns")
df_to_separate

,file,text,doc,people,coreference_genders,men,women,paragraph_boundaries,men_per_paragraph,women_per_paragraph,paragraph_genders,man_paragraphs,woman_paragraphs,equal_paragraphs,genderless_paragraphs
0,news_10-get-ready-for-a-november-to-remember-i...,"November is stacked. Normally, I would look to...","(November, is, stacked, ., Normally, ,, I, wou...","[(Ketlen, Vieira), (Norma, Dumont), (Vieira), ...","[(Vieira, woman), (Vieira, woman), (her, woman...","{(his), (Nikolay, Veretennikov), (Makhachev), ...","{(Namajunas), (Kayla, Harrison), (Namajunas), ...","[(0, 67), (67, 103), (103, 112), (112, 153), (...","[0, 0, 0, 0, 0, 0, 0, 5, 8, 10, 0, 3, 6, 10, 0...","[0, 0, 0, 4, 11, 9, 3, 0, 0, 0, 0, 0, 0, 0, 0,...","[None, None, None, woman, woman, woman, woman,...","[(\n, Steve, Garcia, and, David, Onama, clash,...","[(\n, You, know, it, ’s, a, loaded, month, whe...",[],"[(November, is, stacked, ., Normally, ,, I, wo..."
14,news_adrian-yanez-reloaded-ufc-vegas-111.txt,The first two years of Adrian Yanez’ UFC caree...,"(The, first, two, years, of, Adrian, Yanez, ’,...","[(Adrian, Yanez, ’, UFC), (Dana, White, ’s), (...","[(Yanez, man), (Yanez, man), (it, man), (Marco...","{(he), (Yanez), (Yanez), (Daniel, Marcos), (Qu...",{},"[(0, 79), (79, 128), (128, 170), (170, 250), (...","[0, 0, 0, 2, 3, 2, 0, 8, 3, 1, 1, 2, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, None, None, man, man, man, None, man, m...","[(\n, “, I, never, thought, something, like, t...",[],[],"[(The, first, two, years, of, Adrian, Yanez, ’..."
30,news_alice-ardelean-is-planning-her-big-move-u...,Alice Ardelean remains close to her Romanian r...,"(Alice, Ardelean, remains, close, to, her, Rom...","[(Alice, Ardelean), (Ardelean), (Ardelean), (G...","[(Ardelean, woman), (her, woman), (herself, wo...",{(Garcia)},"{(Melissa, Martinez), (she), (Ardelean), (Arde...","[(0, 25), (25, 67), (67, 175), (175, 210), (21...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[4, 5, 3, 3, 6, 7, 2, 4, 1, 6, 1, 0, 6, 5, 3, ...","[woman, woman, woman, woman, woman, woman, wom...",[],"[(Alice, Ardelean, remains, close, to, her, Ro...",[],"[(\n, “, I, had, an, even, tougher, fight, cam..."
43,news_ante-delija-making-waves.txt,Making an immediate impact in the UFC is a cha...,"(Making, an, immediate, impact, in, the, UFC, ...","[(Ante, Delija), (Marcin, Tybura), (Waldo, Cor...","[(Delija, man), (Delija, man), (Tybura, man), ...","{(his), (Aspinall), (Delija), (Delija), (his),...",{},"[(0, 67), (67, 133), (133, 207), (207, 245), (...","[0, 4, 5, 1, 0, 5, 2, 1, 2, 1, 0, 0, 6, 5, 6, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, man, man, man, None, man, man, man, man...","[(\n, But, things, are, a, little, different, ...",[],[],"[(Making, an, immediate, impact, in, the, UFC,..."
67,news_bigger-picture-ufc-321-aspinall-vs-gane.txt,The UFC’s annual October pay-per-view event in...,"(The, UFC, ’s, annual, October, pay, -, per, -...","[(Tom, Aspinall), (Ciryl, Gane), (Jon, Anik), ...","[(Aspinall, man), (himself, man), (he, man), (...","{(Rakic), (he), (Alex, Pereira), (himself), (M...","{(Mackenzie, Dern), (she), (she), (Dern), (Der...","[(0, 59), (59, 67), (67, 135), (135, 255), (25...","[0, 0, 2, 2, 0, 4, 0, 5, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 7, 0, 0, 3, 3, ...","[None, None, man, man, None, man, None, man, N...","[(\n, The, way, Saturday, ’s, highly, anticipa...","[(\n, Mackenzie, Dern, became, the, sixth, wom...",[],"[(The, UFC, ’s, annual, October, pay, -, per, ..."
110,news_chris-padilla-blocking-out-the-noise-ufc-...,"For Chris Padilla, it doesn’t matter where he ...","(For, Chris, Padilla, ,, it, does, n’t, matter...","[(Chris, Padilla), (Padilla), (Jai, Herbert), ...","[(Padilla, man), (he, man), (He, man), (Padill...","{(his), (Padilla), (He), (Padilla), (Chris, Pa...",{},"[(0, 47), (47, 123), (123, 221), (221, 258), (...","[6, 6, 9, 5, 7, 6, 4, 8, 1, 3, 3, 3]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[man, man, man, man, man, man, man, man, man, ...","[(For, Chris, Padilla, ,, it, does, n’t, matte...",[],[],[]
111,news_christian-leroy-duncan-settled-and-starti...,Here’s a very simple truth that doesn’t get ac...,"(Here, ’s, a, very, simple, truth, that, does,...","[(Christian, Leroy, Duncan), (Duncan), (Marco,...","[(Duncan, man), (Duncan, man), (he, man), (he,...","{(Duncan), (his), (Eryk, Anders), (he), (his),...",{},"[(0, 37), (37, 121), (121, 196), (196, 262), (...","[0, 0, 2, 3, 0, 2, 4, 3, 0, 6, 0, 7, 2, 5, 4, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, None, man, man, None, man, man, man, No...","[(\n, Christian, Leroy, Duncan, is, a, prime, ...",[],[],"[(Here, ’s, a, very, simple, truth, that, does..."
154,news_david-onama-excited-but-also-expected-veg...,David Onama hadn’t been to sign posters for th...,"(David, Onama, had, n’t, been, to, sign, poste...","[(David, Onama), (Steve, Garcia), (Jean, Silva...","[(Onama, man), (he, man), (he, man), (him, man...","{(He), (Garcia), (him), (he), (Gabriel, Benite...",{},"[(0, 48), (48, 142), (142, 223), (223, 285), (...","[5, 7, 1, 0, 3, 2, 0, 1, 0, 0, 3, 9, 7, 4, 10,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[man, man, man, None, man, man, None, man, Non...","[(David, Onama, had, n’t, been, to, sign, post...",[],[],"[(\n, “, I, know, the, feelings, I, ’m, gon, n..."
163,news_donte-johnson-clocking-in-ufc-vegas-110.txt,Donte Johnson claimed his place on the UFC ros...,"(Donte, Johnson, claimed, his, place, on, the,...","[(Donte, Johnson), (Darion, Abbey), (Dana, Whi...","[(Johnson, man), (his, man), (Johnson, man), (...","{(his), (He), (his), (Johnson), (he), (his), (...",{},"[(0, 42), (42, 150), (150, 175), (175, 271), (...","[3, 5, 4, 3, 1, 14, 2, 2, 2, 2, 0, 5, 7, 4, 0,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[man, man, man, man, man, man, man, man, man, ...","[(Donte, Johnson, claimed, his, place, on, the...",[],[],"[(\n, “, We, ’re, prepared, for, it, ,, and, w..."
205,news_fight-by-fight-preview-ufc-321-aspinall-v...,The UFC makes its second trip to Abu Dhabi thi...,"(The, UFC, makes, its, second, trip, to, Abu, ...","[(Tom, Aspinall), (Ciryl, Gane), (Virna, Jandi...","[(Aspinall, man), (his, man), (Jandiroba, woma...","{(his), (Raposo), (Gane), (their), (their), (A...","{(Jandiroba), (Dern), (Dern), (Dern), (Jandiro...","[(0, 46), (46, 154), (154, 172), (172, 190), (...","[0, 4, 0, 2, 3, 4, 4, 6, 8, 9, 0, 0, 0, 0, 3, ...","[0, 4, 0, 2, 0, 0, 0, 0, 0, 0, 3, 7, 6, 7, 0, ...","[None, equal, None, equal, man, man, man, man,...","[(\n, Other, Main, Card, Matches:•, Umar, Nurm...","[(\n, Streaking, Brazilian, Virna, Jandiroba, ...","[(\n, In, the, main, event, ,, undisputed, UFC...","[(The, UFC, makes, its, second, trip, to, Abu,..."
208,news_fight-by-fight-preview-ufc-fight-night-ga...,The action returns to UFC APEX this Saturday f...,"(The, action, returns, to, UFC, APEX, this, Sa...","[(Dana, White, ’s), (Steve, Garcia), (David, O...","[(Garcia, man), (Garcia, man), (Garcia, man), ...","{(Dumas), (his), (Dumas), (Garcia), (his), (hi...","{(her), (Dumont), (Vieira), (Ardelean), (Vieir...","[(0, 67), (67, 77), (77, 86), (86, 96), (96, 1...","[0, 0, 2, 0, 0, 0, 0, 3, 6, 4, 3, 4, 5, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, None, man, None, None, None, None, man,...","[(\n, Main, Event, :, Steve, Garcia, vs, David...","[(\n, Ketlen, Vieira, and, Norma, Dumont, shar...",[],"[(The, action, returns, to, UFC, APEX, this, S..."
223,news_fight-fight-preview-ufc-fight-night-bonfi...,"Halloween just passed, which means chances are...","(Halloween, just, passed, ,, which, means, cha...","[(Gabriel, Bonfim), (Randy, Brown, \n), (Randy...","[(Bonfim, man), (Bonfim, man), (Brown, man), (...","{(He), (Amil), (his), (his), (Yanez), (man), (...","{(her), (Pennington), (Gomes), (Bruna, Brasil)...","[(0, 62), (62, 117), (117, 124), (124, 133), (...","[0, 0, 0, 1, 0, 0, 0, 0, 3, 8, 5, 0, 3, 4, 4, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, None, None, man, None, None, None, None...","[(\n, Main, Event, :, Gabriel, Bonfim, vs, Ran...","[(\n, Mayra, Bueno, Silva, and, Jacqueline, Ca...",[],"[(Halloween, just, passed, ,, which, means, ch..."
241,news_fighters-on-the-rise-ufc-fight-night-bonf...,Now that we’ve entered the penultimate month o...,"(Now, that, we, ’ve, entered, the, penultimate...","[(Morales), (Roberto, Sanchez), (Eric, Shelton...","[(Morales, man), (his, man), (him, man), (him,...","{(Morales), (Shelton), (Schnell), (Roberto, Sa...","{(Cavalcanti), (her), (she), (Melissa, Croden)...","[(0, 53), (53, 163), (163, 180), (180, 247), (...","[0, 0, 0, 7, 7, 8, 9, 12, 3, 6, 2, 1, 4, 5, 0,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, ...","[None, None, None, man, man, man, man, man, ma...","[(\n, Morales, debuted, in, the, UFC, in, Augu...","[(\n, Last, week, ,, Norma, Dumont, was, featu...","[(\n, This, week, ,, it, ’s, Cavalcanti, ’s, t...","[(Now, that, we, ’ve, entered, the, penultimat..."
257,news_fighters-rise-ufc-fight-night-garcia-vs-o...,Fatima Kline. Jean Silva. David Martinez. Aiem...,"(Fatima, Kline, ., Jean, Silva, ., David, Mart...","[(Fatima, Kline), (Jean, Silva), (David, Marti...","[(Delija, man), (It, man), (Pavlovich, man), (...","{(Jean, Silva), (Waldo, Cortes, Acosta), (Nasc...","{(Aldana), (her), (Dumont), (Harrison), (Harri...","[(0, 21), (21, 103), (103, 119), (119, 206), (...","[5, 0, 0, 1, 0, 3, 10, 1, 4, 12, 8, 0, 0, 0, 0...","[1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 7, 14, 9,...","[man, None, None, man, woman, man, man, man, m...","[(Fatima, Kline, ., Jean, Silva, ., David, Mar...","[(\n, A, big, part, of, what, makes, the, Croa...",[],"[(\n, Those, are, just, some, of, the, ascenda..."
280,news_gabriel-bonfim-leveled-up-legend-ufc-vega...,It’s often said that fighters learn more from ...,"(It, ’s, often, said, that, fighters, learn, m...","[(Gabriel, Bonfim), (Nicolas, Dalby), (Stephen...","[(Bonfim, man), (his, man), (he, man), (Bonfim...","{(his), (Ismael), (him), (Gabriel, Bonfim), (m...",{},"[(0, 31), (31, 72), (72, 154), (154, 194), (19...","[4, 2, 2, 3, 0, 1, 5, 6, 1, 0, 7, 7, 1, 0, 11,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[man, man, man, man, None, man, man, man, man,...","[(It, ’s, often, said, that, fighters, learn, ...",[],[],"[(\n, The, reason, for, that, assessment, was,..."
359,news_joseph-morales-all-way-back-ufc-vegas-111...,Joseph Morales didn’t really celebrate his vic...,"(Joseph, Morales, did, n’t, really, celebrate,...","[(Joseph, Morales), (Eduardo, Chapolin), (Iman...","[(Morales, man), (his, man), (him, man), (his,...","{(Schnell), (Morales), (Deiveson, Figueiredo),...",{},"[(0, 54), (54, 123), (123, 208), (208, 238), (...","[6, 0, 6, 2, 5, 5, 3, 0, 2, 4, 4, 0, 0, 1, 2, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[man, None, man, man, man, man, man, None, man...","[(Joseph, Morales, did, n’t, really, celebrate...",[],[],"[(\n, Entering, as, a, significant, underdog, ..."
371,news_junyong-park-hungry-for-more-ufc-321.txt,Upon sitting down to speak with JunYong Park e...,"(Upon, sitting, down, to, speak, with, JunYong...","[(JunYong, Park), (Ikram, Aliskerov), (Mike, R...","[(Park, man), (Park, man), (Park, man), (Park,...","{(Aliskerov), (Park), (Ikram, Aliskerov), (he)...",{},"[(0, 46), (46, 89), (89, 131), (131, 252), (25...","[3, 0, 1, 4, 2, 0, 0, 0, 0, 2, 6, 7, 3, 1, 9, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[man, None, man, man, man, None, None, None, N...","[(Upon, sitting, down, to, speak, with, JunYon...",[],[],"[(\n, As, we, readied, to, begin, ,, I, asked,..."
387,news_ketlen-vieira-ready-claim-title-ufc-vegas...,"Ketlen Vieira has been in the UFC since 2016, ...","(Ketlen, Vieira, has, been, in, the, UFC, sinc...","[(Ketlen, Vieira), (Vieira), (Norma, Dumont), ...","[(Vieira, woman), (she, woman), (women, woman)...","{(she), (she), (Garcia), (she), (Garcia), (she)}","{(Raquel, Pennington), (Vieira), (she), (Dumon...","[(0, 66), (66, 115), (115, 174), (174, 225), (...","[0, 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[4, 3, 0, 1, 0, 0, 3, 1, 0, 7, 5, 3, 2, 8, 8, ...","[woman, woman, man, man, man, None, woman, wom...","[(\n, "", I, know, it, 's, not, formalized, yet...","[(Ketlen, Vieira, has, been, in, the, UFC, sin...",[],"[(\n, "", I, think, everything, happens, in, Go..."
460,news_malcolm-wellmaker-built-ground-bantamweig...,"Earlier this year, bantamweight Malcolm Wellma...","(Earlier, this, year, ,, bantamweight, Malcolm...","[(Malcolm, Wellmaker), (Wellmaker), (Cameron, ...","[(Wellmaker, man), (his, man), (Wellmaker, man...","{(Wellmaker), (his), (Wellmaker), (his), (Well...","{(Pearl, Gonzalez)}","[(0, 23), (23, 75), (75, 168), (168, 199), (19...","[3, 2, 10, 0, 0, 0, 1, 1, 2, 0, 1, 0, 6, 2, 0,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","[man, man, man, None, None, None, man, man, ma...","[(Earlier, this, year, ,, bantamweight, Malcol...",[],[],"[(\n, Two, fights, ,, two, knockouts, ,, and, ..."
495,news_matt-schnell-honest-excited-and-dangerous...,Matt Schnell is an interviewer’s dream; you as...,"(Matt, Schnell, is, an, interviewer, ’s, dream...","[(Matt, Schnell), (Cody, Durden), (Jimmy, Flic...","[(Durden, man), (his, man), (he, man), (he, ma...","{(Schnell), (Morales), (Morales), (he), (Josep...",{},"[(0, 56), (56, 132), (132, 206), (206, 307), (...","[1, 7, 5, 0, 1, 1, 0, 4, 0, 0, 2, 5, 0, 5, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[man, man, man, None, man, man, None, man, Non...","[(Matt, Schnell, is, an, interviewer, ’s, drea...",[],[],"[(\n, “, Part, of, it, was, that, ,, and, anot..."
533,news_monthly-report-october-2025-ufc-jourdain-...,The UFC is in that non-stop part of the fall s...,"(The, UFC, is, in, that, non, -, stop, part, o...","[(Bookended), (Kyle, Nelson), (Mike, Malott), ...","[(Henry, man), (Henry, man), (Grant, man), (Gr...","{(Marlon, Vera), (Rafael, Fiziev), (Gamrot), (...","{(Melissa, Croden)}","[(0, 35), (35, 75), (75, 161), (161, 248), (24...","[0, 0, 2, 4, 3, 3, 0, 1, 4, 10, 7, 7, 4, 9, 0,...","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...","[None, None, man, man, man, man, None, equal, ...","[(\n, Before, we, get, to, the, winners, ,, a,...",[],"[(\n, Honorable, Mentions, :, Bia, Mesquita, ,...","[(The, UFC, is, in, that, non, -, stop, part, ..."
552,news_norma-dumont-done-waiting-around-ufc-figh...,"Last September, Norma Dumont waltzed into the ...","(Last, September, ,, Norma, Dumont, waltzed, i...","[(Norma, Dumont), (Irene, Aldana), (Dumont), (...","[(Dumont, woman), (Dumont, woman), (Dumont, wo...","{(Charles, Oliveira), (Charles), (Daniel, Sant...","{(Aldana), (Julianna, Pena), (Germaine, de, Ra...","[(0, 36), (36, 91), (91, 155), (155, 212), (21...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 0, 0, 0, ...","[4, 4, 2, 1, 1, 0, 2, 11, 3, 5, 4, 2, 0, 5, 2,...","[woman, woman, woman, woman, woman, None, woma...","[(\n, “, It, ’s, a, very, powerful, energy, .,...","[(Last, September, ,, Norma, Dumont, waltzed, ...","[(\n, The, team, has, been, hyper, -, active, ...","[(\n, “, You, feel, like, you, ’re, more, read..."
570,news_phil-rowe-tired-of-fighting-himself-ufc-v...,Phil Rowe sat at the table stationed in the me...,"(Phil, Rowe, sat, at, the, table, stationed, i...","[(Phil, Rowe), (Ange, Loosa), (Loosa), (Dana, ...","[(Rowe, man), (he, man), (Loosa, man), (him, m...","{(his), (Ryan), (he), (his), (Loosa), (Loosa),...",{},"[(0, 77), (77, 181), (181, 244), (244, 392), (...","[8, 14, 9, 3, 0, 1, 3, 3, 8, 1, 4, 0, 2, 7, 8,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[man, man, man, man, None, man, man, man, man,...","[(Phil, Rowe, sat, at, the, table, stationed, ...",[],[],"[(\n, “, I, ’m, just, trying, to, be, better, ..."
615,news_randy-brown-something-bigger-ufc-fight-ni...,Randy Brown has been waiting for this moment f...,"(Randy, Brown, has, been, waiting, for, this, ...","[(Randy, Brown), (Brown), (Nicolas, Dalby), (B...","[(Brown, man), (his, man), (him, man), (Brown,...","{(his), (he), (Brown), (Jack, Della, Maddalena...",{},"[(0, 30), (30, 146), (146, 245), (245, 340), (...","[4, 14, 7, 2, 3, 5, 6, 1, 0, 7, 4, 2, 2, 1, 2,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[man, man, man, man, man, man, man, man, None,...","[(Randy, Brown, has, been, waiting, for, this,...",[],[],"[(\n, “, We, ’re, gon, na, go, out, there, and..."
650,news_scorecard-ufc-fight-night-garcia-vs-onama...,The Octagon returned home on Saturday night as...,"(The, Octagon, returned, home, on, Saturday, n...","[(Garcia), (Steve, Garcia), (David, Onama), (G...","[(Garcia, man), (him, man), (his, man), (Garci...","{(Max, Griffin), (Carlston, Harris), (him), (h...","{(Dumont), (she), (herself), (Ketlen, Vieira),...","[(0, 22), (22, 59), (59, 122), (122, 163), (16...","[0, 2, 7, 4, 8, 3, 1, 6, 2, 0, 0, 3, 6, 0, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, man, man, man, man, man, man, man, man,...","[(\n, Now, that, the, dust, has, settled, in, ...","[(\n, Saturday, night, brought, a, double, cel...",[],"[(The, Octagon, returned, home, on, Saturday, ..."
659,news_seriously-do-not-blink-when-tom-aspinall-...,Few titles in combat sports carry the same pom...,"(Few, titles, in, combat, sports, carry, the, ...","[(Tom, Aspinall), (Ciryl, Gane), (Aspinall), (...","[(Aspinall, man), (Aspinall, man), (Gane, man)...","{(His), (his), (he), (their), (Gane), (Gane), ...",{},"[(0, 76), (76, 142), (142, 243), (243, 356), (...","[0, 5, 4, 9, 12, 20, 10, 8, 4, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[None, man, man, man, man, man, man, man, man,...","[(\n, Such, is, the, case, for, current, champ...",[],[],"[(Few, titles, in, combat, sports, carry, the,..."
676,news_steve-garcia-real-recognizes-real-ufc-fig...,Steve Garcia’s career is currently bookended b...,"(Steve, Garcia, ’s, career, is, currently, boo...","[(Steve, Garcia), (David, Onama), (Garcia), (G...","[(Garcia, man), (he, man), (his, man), (he, ma...","{(his), (Garcia), (Garcia), (his), (Steve, Gar...",{},"[(0, 97), (97, 146), (146, 153), (153, 246), (...","[7, 3, 0, 0, 1, 4, 1, 4, 0, 0, 10, 4, 2, 4, 0,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[man, man, None, None, man, man, man, man, Non...","[(Steve, Garcia, ’s, career, is, currently, bo...",[],[],"[(\n, No, ,, you, do, n’t, .), (\n, Most, figh..."
684,news_tecia-pennington-crossroad-ufc-fight-nigh...,Tecia Pennington heads into her fight with Den...,"(Tecia, Pennington, heads, into, her, fight, w...","[(Tecia, Pennington), (Denise, Gomes), (Raquel...","[(Pennington, woman), (her, woman), (her, woma...",{},"{(she), (Pennington), (Esparza), (Esparza), (h...","[(0, 27), (27, 105), (105, 181), (181, 235), (...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[6, 4, 2, 0, 5, 3, 0, 0, 12, 6, 3, 0, 0, 0, 0,...","[woman, woman, woman, None, woman, woman, None...",[],"[(Tecia, Pennington, heads, into, her, fight, ...",[],"[(\n, “, It, ’s, just, motivating, being, a, m..."
700,news_the-tao-of-allan-nascimento-ufc-vegas-110...,If you were to write out a list of the most sk...,"(If, you, were, to, write, out, a, list, of, t...","[(Allan, Nascimento), (Puro, Osso), (Cody, Dur...","[(Nascimento, man), (individuals, man), (Nasci...","{(Nascimento), (He), (Cody, Durden), (his), (h...","{(Norma, Dumont), (Dumont), (Dumont), (Dumont)}","[(0, 58), (58, 116), (116, 226), (226, 269), (...","[2, 2, 2, 1, 4, 1, 4, 4, 0, 4, 10, 0, 5, 1, 2,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, ...","[man, man, man, man, man, man, man, man, None,...","[(If, you, were, to, write, out, a, list, of, ...",[],[],"[(\n, “, But, it, ’s, step, -, by, -, step, ;,..."

In [28]:
def save_separate_paragraphs(row: pd.Series):
    original_file: str = row["file"]
    new_folder = original_file.replace(".txt", "")

    os.makedirs(f"./articles/{new_folder}", exist_ok=True)

    man_paragraphs: list[Span] = row["man_paragraphs"]
    man_text = "\n".join([p.text for p in man_paragraphs])

    with open(f"./articles/{new_folder}/man.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(man_text)

    woman_paragraphs: list[Span] = row["woman_paragraphs"]
    woman_text = "\n".join([p.text for p in woman_paragraphs])

    with open(f"./articles/{new_folder}/woman.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(woman_text)

    equal_paragraphs: list[Span] = row["equal_paragraphs"]
    equal_text = "\n".join([p.text for p in equal_paragraphs])

    with open(f"./articles/{new_folder}/equal.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(equal_text)

    genderless_paragraphs: list[Span] = row["genderless_paragraphs"]
    genderless_text = "\n".join([p.text for p in genderless_paragraphs])

    with open(f"./articles/{new_folder}/genderless.txt", "w", encoding="utf8", newline="\n") as file:
        file.write(genderless_text)

In [29]:
df_to_separate.apply(save_separate_paragraphs, axis="columns")

0      None
14     None
30     None
43     None
67     None
110    None
111    None
154    None
163    None
205    None
208    None
223    None
241    None
257    None
280    None
359    None
371    None
387    None
460    None
495    None
533    None
552    None
570    None
615    None
650    None
659    None
676    None
684    None
700    None
701    None
713    None
714    None
715    None
716    None
726    None
734    None
753    None
dtype: object