In [10]:
import os
import numpy as np
import pandas as pd
from shutil import copyfile

In [2]:
stats_df = pd.read_csv("./articles_genders_stats.csv")
stats_df

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs
0,news_10-get-ready-for-a-november-to-remember-i...,24,11,0,9,3000,44
1,news_10-june-schedule-jam-packed-goodness.txt,30,8,0,10,2761,48
2,news_10-massive-fights-schedule-may.txt,22,16,0,9,2885,47
3,news_10-memorable-moments-down-under.txt,27,4,0,15,2769,46
4,news_10-middleweights-biggest-championship-mom...,57,0,0,10,3273,67
...,...,...,...,...,...,...,...
876,news_zhang-mingyang-embracing-spotlight-ufc-sh...,9,0,1,3,617,13
877,news_zhang-mingyang-journey-main-event-light-h...,8,0,0,0,728,8
878,news_zhang-weili-big-challenge-apple-vechain-u...,0,19,0,5,882,24
879,news_zhang-weili-builds-her-case-goat-status.txt,0,0,0,1,0,1
880,news_zhang-weili-built-different-ufc-312.txt,0,21,0,3,1341,24

In [3]:
stats_df["prop_man_paragraphs"] = stats_df["num_man_paragraphs"] / stats_df["num_paragraphs"]
stats_df["prop_woman_paragraphs"] = stats_df["num_woman_paragraphs"] / stats_df["num_paragraphs"]
stats_df["prop_equal_paragraphs"] = stats_df["num_equal_paragraphs"] / stats_df["num_paragraphs"]
stats_df["prop_genderless_paragraphs"] = stats_df["num_genderless_paragraphs"] / stats_df["num_paragraphs"]

stats_df

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,prop_genderless_paragraphs
0,news_10-get-ready-for-a-november-to-remember-i...,24,11,0,9,3000,44,0.545455,0.250000,0.000000,0.204545
1,news_10-june-schedule-jam-packed-goodness.txt,30,8,0,10,2761,48,0.625000,0.166667,0.000000,0.208333
2,news_10-massive-fights-schedule-may.txt,22,16,0,9,2885,47,0.468085,0.340426,0.000000,0.191489
3,news_10-memorable-moments-down-under.txt,27,4,0,15,2769,46,0.586957,0.086957,0.000000,0.326087
4,news_10-middleweights-biggest-championship-mom...,57,0,0,10,3273,67,0.850746,0.000000,0.000000,0.149254
...,...,...,...,...,...,...,...,...,...,...,...
876,news_zhang-mingyang-embracing-spotlight-ufc-sh...,9,0,1,3,617,13,0.692308,0.000000,0.076923,0.230769
877,news_zhang-mingyang-journey-main-event-light-h...,8,0,0,0,728,8,1.000000,0.000000,0.000000,0.000000
878,news_zhang-weili-big-challenge-apple-vechain-u...,0,19,0,5,882,24,0.000000,0.791667,0.000000,0.208333
879,news_zhang-weili-builds-her-case-goat-status.txt,0,0,0,1,0,1,0.000000,0.000000,0.000000,1.000000
880,news_zhang-weili-built-different-ufc-312.txt,0,21,0,3,1341,24,0.000000,0.875000,0.000000,0.125000

We want to sample 5% of the corpus. 2.5% of the articles will be mostly about woman, while the other 2.5% will have an equal balance of paragraphs.

In [4]:
half_sample_corpus_size = int(stats_df.shape[0] * 0.025)
half_sample_corpus_size

22

In [5]:
PROP_WOMAN_PARAGRAPHS_THRESHOLD = 0.9

In [6]:
mostly_woman_df = stats_df[stats_df["prop_woman_paragraphs"] >= PROP_WOMAN_PARAGRAPHS_THRESHOLD]\
                    .sort_values("prop_woman_paragraphs", ascending=False)

# Get the most "average" articles
mostly_woman_average_tokens = mostly_woman_df["num_tokens"].median()
mostly_woman_df_sorted = mostly_woman_df.sort_values(
    by="num_tokens", 
    key=lambda num_tokens: abs(num_tokens - mostly_woman_average_tokens)
)

mostly_woman_to_save = mostly_woman_df_sorted.head(half_sample_corpus_size)
mostly_woman_to_save

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,prop_genderless_paragraphs
26,news_alexa-grasso-embracing-every-opportunity-...,0,14,0,1,822,15,0.0,0.933333,0.0,0.066667
556,news_matchup-to-watch-vieira-chiasson-ufc-vega...,0,9,0,1,821,10,0.0,0.900000,0.0,0.100000
529,news_manon-fiorot-journey-to-the-title-shot-uf...,0,12,0,1,808,13,0.0,0.923077,0.0,0.076923
42,news_amanda-ribas-confident-and-competitive-uf...,0,13,0,1,839,14,0.0,0.928571,0.0,0.071429
518,news_main-event-spotlight-ufc-fight-night-blan...,0,13,0,0,849,13,0.0,1.000000,0.0,0.000000
309,news_flyweights-in-the-spotlight-in-montreal-u...,0,10,0,0,794,10,0.0,1.000000,0.0,0.000000
350,news_iasmin-lucindo-letting-flow-ufc-313.txt,0,13,0,1,853,14,0.0,0.928571,0.0,0.071429
40,news_amanda-lemos-eyes-prize-noche-ufc.txt,0,21,0,2,789,23,0.0,0.913043,0.0,0.086957
472,news_loopy-godinez-homecoming-ufc-mexico.txt,0,11,0,1,784,12,0.0,0.916667,0.0,0.083333
866,news_womens-flyweight-division-2026-preview.txt,0,13,0,1,875,14,0.0,0.928571,0.0,0.071429
193,news_dues-paid-jasmine-jasudavicius-set-sights...,0,12,0,1,769,13,0.0,0.923077,0.0,0.076923
836,news_vanessa-demopoulos-all-about-impact-ufc-v...,0,9,0,1,881,10,0.0,0.900000,0.0,0.100000
829,news_under-the-radar-ailin-perez-bantamweight-...,0,12,0,0,745,12,0.0,1.000000,0.0,0.000000
184,news_dione-barbosa-putting-pieces-together-ufc...,0,13,0,0,741,13,0.0,1.000000,0.0,0.000000
417,news_julianna-pena-and-legacy-two-time-womens-...,0,13,0,0,736,13,0.0,1.000000,0.0,0.000000
429,news_kayla-harrisons-quest-greatness-ufc-316.txt,0,10,0,0,731,10,0.0,1.000000,0.0,0.000000
805,news_tracy-cortez-wants-to-make-up-for-lost-ti...,0,11,0,1,725,12,0.0,0.916667,0.0,0.083333
97,news_bruna-brasil-bring-house-down-ufc-312.txt,0,13,0,1,725,14,0.0,0.928571,0.0,0.071429
530,news_manon-fiorot-sees-everything-coming-toget...,0,12,0,0,708,12,0.0,1.000000,0.0,0.000000
365,news_jacqueline-cavalcanti-ready-anywhere-anyt...,0,11,0,1,699,12,0.0,0.916667,0.0,0.083333
209,news_erin-blanchfield-wants-to-make-the-most-o...,0,12,0,0,950,12,0.0,1.000000,0.0,0.000000
844,news_wang-cong-is-here-to-perform-ufc-312.txt,0,11,0,1,664,12,0.0,0.916667,0.0,0.083333

In [7]:
stats_df["entropy"] = -(
    stats_df["prop_man_paragraphs"] * np.log(stats_df["prop_man_paragraphs"] + 1e-12)
    + stats_df["prop_woman_paragraphs"] * np.log(stats_df["prop_woman_paragraphs"] + 1e-12)
    + stats_df["prop_equal_paragraphs"] * np.log(stats_df["prop_equal_paragraphs"] + 1e-12)
    + stats_df["prop_genderless_paragraphs"] * np.log(stats_df["prop_genderless_paragraphs"] + 1e-12)
)

# Max entropy for 4 categories is log(4)
stats_df["entropy_norm"] = stats_df["entropy"] / np.log(4)

stats_df["variance"] = \
                    (stats_df["prop_man_paragraphs"] - 0.25) ** 2 \
                    + (stats_df["prop_woman_paragraphs"] - 0.25) ** 2 \
                    + (stats_df["prop_equal_paragraphs"] - 0.25) ** 2 \
                    + (stats_df["prop_genderless_paragraphs"] - 0.25) ** 2

# Max possible variance for 4 categories is 0.75
stats_df["variance_norm"] = stats_df["variance"] / 0.75

# Balance out the number of tokens to try to make them as equal as possible
stats_df["tokens_balance"] = abs(stats_df["num_tokens"].median() - stats_df["num_tokens"]) / stats_df["num_tokens"].max()

stats_df["balance"] = stats_df["entropy_norm"] \
                    + (1 - stats_df["variance_norm"]) \
                    + stats_df["tokens_balance"] * 0.2 # Don't weight the token balance as much

balanced_to_save = stats_df.sort_values("balance", ascending=False).head(half_sample_corpus_size)
balanced_to_save

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,prop_genderless_paragraphs,entropy,entropy_norm,variance,variance_norm,tokens_balance,balance
604,news_monthly-report-may-2025.txt,20,9,2,10,2559,41,0.487805,0.219512,0.048780,0.243902,1.174503,0.847225,0.098007,0.130676,0.176406,1.751830
653,news_prelim-live-results-fight-recaps-highligh...,7,2,1,5,884,15,0.466667,0.133333,0.066667,0.333333,1.171060,0.844741,0.101111,0.134815,0.028362,1.715599
670,news_prelim-results-highlights-winner-intervie...,5,4,1,1,513,11,0.454545,0.363636,0.090909,0.090909,1.162226,0.838369,0.105372,0.140496,0.073716,1.712616
671,news_prelim-results-highlights-winner-intervie...,11,6,1,4,955,22,0.500000,0.272727,0.045455,0.181818,1.151380,0.830545,0.109504,0.146006,0.019682,1.688476
754,news_significant-stats-ufc-312-du-plessis-vs-s...,3,3,0,4,769,10,0.300000,0.300000,0.000000,0.400000,1.088900,0.785475,0.090000,0.120000,0.042421,1.673959
769,news_submissions-2025-ufccom-awards.txt,13,3,2,6,1579,24,0.541667,0.125000,0.083333,0.250000,1.145678,0.826432,0.128472,0.171296,0.056601,1.666456
682,news_prelim-results-ufc-fight-night-royval-vs-...,3,2,0,2,416,7,0.428571,0.285714,0.000000,0.285714,1.078992,0.778328,0.096939,0.129252,0.085575,1.666192
810,news_ufc-315-best-bets-draftkings-sportsbook.txt,6,4,0,4,669,14,0.428571,0.285714,0.000000,0.285714,1.078992,0.778328,0.096939,0.129252,0.054645,1.660006
603,news_monthly-report-march-2025.txt,14,10,0,8,1859,32,0.437500,0.312500,0.000000,0.250000,1.071730,0.773090,0.101562,0.135417,0.090831,1.655839
601,news_monthly-report-january-2025.txt,12,10,0,7,1540,29,0.413793,0.344828,0.000000,0.241379,1.075361,0.775709,0.098395,0.131193,0.051834,1.654883
354,news_islam-makhachev-and-zhang-weili-chasing-n...,3,4,0,2,573,9,0.333333,0.444444,0.000000,0.222222,1.060857,0.765247,0.108025,0.144033,0.066381,1.634490
2,news_10-massive-fights-schedule-may.txt,22,16,0,9,2885,47,0.468085,0.340426,0.000000,0.191489,1.038672,0.749243,0.121661,0.162215,0.216259,1.630280
293,news_fighters-rise-ufc-fight-night-lewis-vs-te...,10,5,0,7,1499,22,0.454545,0.227273,0.000000,0.318182,1.059478,0.764252,0.109504,0.146006,0.046822,1.627611
488,news_main-card-results-highlights-winner-inter...,10,4,1,3,1117,18,0.555556,0.222222,0.055556,0.166667,1.119990,0.807902,0.138889,0.185185,0.000122,1.622742
291,news_fighters-rise-ufc-fight-night-cannonier-v...,6,10,0,5,1654,21,0.285714,0.476190,0.000000,0.238095,1.052923,0.759523,0.115079,0.153439,0.065770,1.619238
757,news_significant-stats-ufc-315-muhammad-vs-del...,3,6,0,6,1161,15,0.200000,0.400000,0.000000,0.400000,1.054920,0.760964,0.110000,0.146667,0.005501,1.615398
77,news_bigger-picture-ufc-321-aspinall-vs-gane.txt,15,6,0,13,2321,34,0.441176,0.176471,0.000000,0.382353,1.034724,0.746395,0.121972,0.162630,0.147311,1.613228
286,news_fighters-rise-ufc-313-pereira-vs-ankalaev...,11,7,0,5,1544,23,0.478261,0.304348,0.000000,0.217391,1.046563,0.754936,0.118620,0.158160,0.052323,1.607240
266,news_fighters-on-rise-nyc-vechain-ufc-322.txt,10,5,0,5,1386,20,0.500000,0.250000,0.000000,0.250000,1.039721,0.750000,0.125000,0.166667,0.033007,1.589935
666,news_prelim-results-highlights-winner-intervie...,5,3,0,2,318,10,0.500000,0.300000,0.000000,0.200000,1.029653,0.742738,0.130000,0.173333,0.097555,1.588915
72,news_bigger-picture-ufc-315-muhammad-vs-della-...,12,6,0,17,2036,35,0.342857,0.171429,0.000000,0.485714,1.020089,0.735839,0.132857,0.177143,0.112469,1.581190
790,news_the-bigger-picture-ufc-312.txt,21,10,0,9,2203,40,0.525000,0.250000,0.000000,0.225000,1.020483,0.736123,0.138750,0.185000,0.132885,1.577700

In [8]:
files_to_save = set(mostly_woman_to_save["file"].to_list() + balanced_to_save["file"].to_list())
len(files_to_save)

44

In [11]:
os.makedirs("./sample_corpus", exist_ok=True)

In [13]:
for file in files_to_save:
    copyfile(f"./articles/{file}", f"./sample_corpus/{file}")