In [1]:
import os
import numpy as np
import pandas as pd
from shutil import copyfile
from helpers import get_page_name

In [2]:
stats_df = pd.read_csv("./articles_genders_stats.csv")
stats_df = stats_df[stats_df["num_tokens"] > 0]
stats_df

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs
0,news_10-get-ready-for-a-november-to-remember-i...,24,11,0,9,3000,44
1,news_10-june-schedule-jam-packed-goodness.txt,30,8,0,10,2761,48
2,news_10-massive-fights-schedule-may.txt,22,16,0,9,2885,47
3,news_10-memorable-moments-down-under.txt,27,4,0,15,2769,46
4,news_10-middleweights-biggest-championship-mom...,57,0,0,10,3273,67
...,...,...,...,...,...,...,...
875,news_zhang-mingyang-all-gas-no-brakes-ufc-kans...,11,0,0,2,750,13
876,news_zhang-mingyang-embracing-spotlight-ufc-sh...,9,0,1,3,617,13
877,news_zhang-mingyang-journey-main-event-light-h...,8,0,0,0,728,8
878,news_zhang-weili-big-challenge-apple-vechain-u...,0,19,0,5,882,24
880,news_zhang-weili-built-different-ufc-312.txt,0,21,0,3,1341,24

In [3]:
stats_df["prop_man_paragraphs"] = stats_df["num_man_paragraphs"] / stats_df["num_paragraphs"]
stats_df["prop_woman_paragraphs"] = stats_df["num_woman_paragraphs"] / stats_df["num_paragraphs"]
stats_df["prop_equal_paragraphs"] = stats_df["num_equal_paragraphs"] / stats_df["num_paragraphs"]
stats_df["prop_genderless_paragraphs"] = stats_df["num_genderless_paragraphs"] / stats_df["num_paragraphs"]

stats_df

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,prop_genderless_paragraphs
0,news_10-get-ready-for-a-november-to-remember-i...,24,11,0,9,3000,44,0.545455,0.250000,0.000000,0.204545
1,news_10-june-schedule-jam-packed-goodness.txt,30,8,0,10,2761,48,0.625000,0.166667,0.000000,0.208333
2,news_10-massive-fights-schedule-may.txt,22,16,0,9,2885,47,0.468085,0.340426,0.000000,0.191489
3,news_10-memorable-moments-down-under.txt,27,4,0,15,2769,46,0.586957,0.086957,0.000000,0.326087
4,news_10-middleweights-biggest-championship-mom...,57,0,0,10,3273,67,0.850746,0.000000,0.000000,0.149254
...,...,...,...,...,...,...,...,...,...,...,...
875,news_zhang-mingyang-all-gas-no-brakes-ufc-kans...,11,0,0,2,750,13,0.846154,0.000000,0.000000,0.153846
876,news_zhang-mingyang-embracing-spotlight-ufc-sh...,9,0,1,3,617,13,0.692308,0.000000,0.076923,0.230769
877,news_zhang-mingyang-journey-main-event-light-h...,8,0,0,0,728,8,1.000000,0.000000,0.000000,0.000000
878,news_zhang-weili-big-challenge-apple-vechain-u...,0,19,0,5,882,24,0.000000,0.791667,0.000000,0.208333
880,news_zhang-weili-built-different-ufc-312.txt,0,21,0,3,1341,24,0.000000,0.875000,0.000000,0.125000

In [4]:
metadata_files = [file for file in os.listdir("./") if "only_metadata" in file]

metadata_df = pd.concat([pd.read_csv(file) for file in metadata_files]).drop_duplicates(subset="link")
metadata_df["file"] = metadata_df["link"].apply(lambda link: f"{get_page_name(link)}.txt")
metadata_df

,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media,file
0,/news/10-new-era-begins-style,Fight Preview,3 hours ago,THE 10 | A NEW ERA BEGINS IN STYLE,THE 10 | A NEW ERA BEGINS IN STYLE,"UFC Opens Paramount Partnership, 2026 With Con...",2026-01-01 15:23:21-06:00,2026-01-01 15:48:43-06:00,E. Spencer Kyte,NaN,news_10-new-era-begins-style.txt
1,/news/womens-bantamweight-division-2026-preview,Athletes,4 hours ago,The Women’s Bantamweight Division | 2026 Preview,The Women’s Bantamweight Division | 2026 Preview,NaN,2026-01-01 14:30:35-06:00,2026-01-01 14:56:27-06:00,Zac Pacleb,NaN,news_womens-bantamweight-division-2026-preview...
2,/news/when-a-game-plan-works-to-perfection-mas...,Athletes,1 day ago,When A Game Plan Works To Perfection,When A Game Plan Works To Perfection,Looking Back At Some Of The Most Flawlessly Ex...,2025-12-31 09:00:00-06:00,2025-12-31 09:05:49-06:00,NaN,NaN,news_when-a-game-plan-works-to-perfection-masv...
3,/news/womens-flyweight-division-2026-preview,Athletes,1 day ago,The Women’s Flyweight Division | 2026 Preview,The Women’s Flyweight Division | 2026 Preview,Valentina Shevchenko Remains The Division’s Be...,2025-12-31 09:00:00-06:00,2025-12-31 07:55:00-06:00,Zac Paceb,ZacPacleb,news_womens-flyweight-division-2026-preview.txt
4,/news/five-fighters-whove-thrived-moving-up-a-...,Fight Coverage,1 day ago,Five Fighters Who’ve Thrived Moving Up A Weight…,Five Fighters Who’ve Thrived Moving Up A Weigh...,Highlighting Five Fighters Who Achieved Huge S...,2025-12-30 19:45:00-06:00,2025-12-30 19:51:24-06:00,Kevin Schuster,NaN,news_five-fighters-whove-thrived-moving-up-a-w...
...,...,...,...,...,...,...,...,...,...,...,...
724,/news/umar-nurmagomedov-is-ready-to-go-into-de...,Athletes,8 months ago,Umar Nurmagomedov Is Ready To Go Into Deep Waters,Umar Nurmagomedov Is Ready To Go Into Deep Waters,Undefeated Russian Challenger Is Prepared To M...,2025-01-13 12:36:33-06:00,2025-01-17 13:36:55-06:00,Simon Head,simonheadsport,news_umar-nurmagomedov-is-ready-to-go-into-dee...
725,/news/grant-dawson-very-good-year-ufc-311,Athletes,8 months ago,Grant Dawson's Very Good Year,Grant Dawson's Very Good Year,Lightweight Looks To Ride 2024's Winning Momen...,2025-01-13 11:54:29-06:00,2025-01-13 09:55:07-06:00,Thomas Gerbasi,thomasgerbasi,news_grant-dawson-very-good-year-ufc-311.txt
726,/news/islam-makhachev-wants-to-eliminate-all-d...,Athletes,8 months ago,Islam Makhachev Wants To Eliminate All Doubt,Islam Makhachev Wants To Eliminate All Doubt,Undisputed UFC Lightweight Champion Wants To L...,2025-01-13 10:52:00-06:00,2025-01-17 13:45:40-06:00,Simon Head,simonheadsport,news_islam-makhachev-wants-to-eliminate-all-do...
727,/news/prelim-results-highlights-winner-intervi...,Results,8 months ago,Prelim Results | UFC Fight Night: Dern vs Ribas 2,Prelim Results | UFC Fight Night: Dern vs Ribas 2,"See The Fight Results, Watch Post-Fight Interv...",2025-01-11 21:08:00-06:00,2025-01-13 12:27:19-06:00,E. Spencer Kyte,spencerkyte,news_prelim-results-highlights-winner-intervie...
728,/news/main-card-results-highlights-winner-inte...,Results,8 months ago,Main Card Results | UFC Fight Night: Dern vs R...,Main Card Results | UFC Fight Night: Dern vs R...,"See The Fight Results, Watch Post-Fight Interv...",2025-01-11 21:08:00-06:00,2025-01-13 12:27:51-06:00,E. Spencer Kyte,spencerkyte,news_main-card-results-highlights-winner-inter...

In [5]:
stats_with_metadata_df = stats_df.merge(metadata_df, on="file")
stats_with_metadata_df

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media
0,news_10-get-ready-for-a-november-to-remember-i...,24,11,0,9,3000,44,0.545455,0.250000,0.000000,...,/news/10-get-ready-for-a-november-to-remember-...,Athletes,1 month ago,The 10 | Get Ready For A November To Remember ...,The 10 | Get Ready For A November To Remember ...,Coming Month Offers Heaps Of High-Level Matchu...,2025-10-29 11:54:58-05:00,2025-10-29 16:03:43-05:00,E. Spencer Kyte,spencerkyte
1,news_10-june-schedule-jam-packed-goodness.txt,30,8,0,10,2761,48,0.625000,0.166667,0.000000,...,/news/10-june-schedule-jam-packed-goodness,Fight Coverage,3 months ago,The 10 | June Schedule Jam-Packed With Goodness,The 10 | June Schedule Jam-Packed With Goodness,"Four Events, Dozens Of Fights, And Non-Stop Ac...",2025-06-04 12:29:37-05:00,2025-06-04 12:55:00-05:00,E. Spencer Kyte,spencerkyte
2,news_10-massive-fights-schedule-may.txt,22,16,0,9,2885,47,0.468085,0.340426,0.000000,...,/news/10-massive-fights-schedule-may,Fight Coverage,4 months ago,THE 10 | MASSIVE FIGHTS ON THE SCHEDULE IN MAY,THE 10 | MASSIVE FIGHTS ON THE SCHEDULE IN MAY,Outlining Several Of The Critical Matchups Set...,2025-05-01 16:40:05-05:00,2025-05-01 16:40:15-05:00,E. Spencer Kyte,NaN
3,news_10-memorable-moments-down-under.txt,27,4,0,15,2769,46,0.586957,0.086957,0.000000,...,/news/10-memorable-moments-down-under,Fight Coverage,7 months ago,The 10 | Memorable Moments Down Under,The 10 | Memorable Moments Down Under,Looking Back On The Coolest Moments In The Oct...,2025-01-21 11:39:00-06:00,2025-01-21 11:40:12-06:00,E. Spencer Kyte,spencerkyte
4,news_10-middleweights-biggest-championship-mom...,57,0,0,10,3273,67,0.850746,0.000000,0.000000,...,/news/10-middleweights-biggest-championship-mo...,Fight Coverage,7 months ago,The 10 | Middleweight’s Biggest Championship M...,The 10 | Middleweight’s Biggest Championship M...,Tracking The Top Performances In Middleweight ...,2025-01-22 13:02:06-06:00,2025-01-22 13:58:25-06:00,E. Spencer Kyte,spencerkyte
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,news_zhang-mingyang-all-gas-no-brakes-ufc-kans...,11,0,0,2,750,13,0.846154,0.000000,0.000000,...,/news/zhang-mingyang-all-gas-no-brakes-ufc-kan...,Athletes,4 months ago,"Zhang Mingyang | All Gas, No Brakes","Zhang Mingyang | All Gas, No Brakes","With 18 First-Round Finishes, Zhang Mingyang C...",2025-04-24 16:45:00-05:00,2025-04-24 16:46:15-05:00,Kevin Schuster,KevinESchuster
874,news_zhang-mingyang-embracing-spotlight-ufc-sh...,9,0,1,3,617,13,0.692308,0.000000,0.076923,...,/news/zhang-mingyang-embracing-spotlight-ufc-s...,Athletes,3 weeks ago,Zhang Mingyang Is Embracing The Spotlight,Zhang Mingyang Is Embracing The Spotlight,"Undefeated In The UFC So Far, China's Zhang Mi...",2025-08-21 11:39:50-05:00,2025-08-21 11:56:05-05:00,Zac Pacleb,NaN
875,news_zhang-mingyang-journey-main-event-light-h...,8,0,0,0,728,8,1.000000,0.000000,0.000000,...,/news/zhang-mingyang-journey-main-event-light-...,Athletes,3 weeks ago,Zhang Mingyang | Journey To Main Event,Zhang Mingyang | Journey To Main Event,"Three Fights Into His UFC Career, China’s Zhan...",2025-08-19 17:17:58-05:00,2025-08-19 17:36:52-05:00,Maddyn Johnstone,NaN
876,news_zhang-weili-big-challenge-apple-vechain-u...,0,19,0,5,882,24,0.000000,0.791667,0.000000,...,/news/zhang-weili-big-challenge-apple-vechain-...,Athletes,1 month ago,Zhang Weili's Big Challenge In The Big Apple,Zhang Weili's Big Challenge In The Big Apple,"Zhang Weili Ruled The World At 115-lbs, But No...",2025-11-12 12:45:22-06:00,2025-11-12 14:03:16-06:00,Simon Head,simonheadsport
877,news_zhang-weili-built-different-ufc-312.txt,0,21,0,3,1341,24,0.000000,0.875000,0.000000,...,/news/zhang-weili-built-different-ufc-312,Athletes,7 months ago,Zhang Weili | Built Different,Zhang Weili | Built Different,UFC Strawweight Champion’s Constant Focus On I...,2025-02-05 11:50:00-06:00,2025-02-06 16:36:01-06:00,E. Spencer Kyte,SpencerKyte

We want to sample 5% of the corpus. 2.5% will have an equal balance of gendered paragraphs, while the other 2.5% will be split into mostly-man paragraphs, mostly-woman paragraphs, mostly-equal paragraphs, and mostly-genderless paragraphs.

In [6]:
HALF_SAMPLE_CORPUS_SIZE = int(stats_with_metadata_df.shape[0] * 0.025)
HALF_SAMPLE_CORPUS_SIZE

21

In [7]:
EIGHTH_SAMPLE_CORPUS_SIZE = int(stats_with_metadata_df.shape[0] * 0.00625)
EIGHTH_SAMPLE_CORPUS_SIZE

5

In [8]:
# Get articles that are around average length so that
# sample corpus is mostly even and representative.
average_num_tokens = stats_with_metadata_df["num_tokens"].median()
std_num_tokens = stats_with_metadata_df["num_tokens"].std()

# Total one standard deviation around the middle
average_num_tokens_df = stats_with_metadata_df[
    (stats_with_metadata_df["num_tokens"] >= average_num_tokens - std_num_tokens / 2)
    & (stats_with_metadata_df["num_tokens"] <= average_num_tokens + std_num_tokens / 2)
]
average_num_tokens_df

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media
12,news_a-different-derrick-lewis-ufc-324.txt,17,0,0,4,1108,21,0.809524,0.000000,0.0,...,/news/a-different-derrick-lewis-ufc-324,Athletes,2 days ago,A Different Derrick Lewis,A Different Derrick Lewis,"Tenured Heavyweight Eyes Activity, Winning Str...",2025-12-30 13:36:31-06:00,2025-12-30 13:46:34-06:00,E. Spencer Kyte,spencerkyte
13,news_a-new-kai-asakura-is-ready-to-establish-h...,17,0,0,0,890,17,1.000000,0.000000,0.0,...,/news/a-new-kai-asakura-is-ready-to-establish-...,Athletes,1 month ago,A ‘New’ Kai Asakura Is Ready To Establish Himself,A ‘New’ Kai Asakura Is Ready To Establish Himself,After Fighting For The Title In His Octagon De...,2025-08-15 11:53:41-05:00,2025-08-15 12:53:31-05:00,Zac Pacleb,ZacPacleb
14,news_a-wild-couple-of-weeks-for-kyle-prepolec-...,22,0,0,3,1357,25,0.880000,0.000000,0.0,...,/news/a-wild-couple-of-weeks-for-kyle-prepolec...,Athletes,4 months ago,A Wild Couple Of Weeks For Kyle Prepolec,A Wild Couple Of Weeks For Kyle Prepolec,Canadian Veteran Discusses Short-Notice Return...,2025-05-07 19:23:56-05:00,2025-05-07 19:35:55-05:00,E. Spencer Kyte,spencerkyte
21,news_alex-morono-pride-and-perspective-ufc-313...,16,0,0,4,1418,20,0.800000,0.000000,0.0,...,/news/alex-morono-pride-and-perspective-ufc-313,Athletes,6 months ago,Alex Morono | Pride and Perspective,Alex Morono | Pride and Perspective,Welterweight Veteran Shares Outlook Ahead Of E...,2025-03-05 17:30:00-06:00,2025-03-05 17:29:40-06:00,E. Spencer Kyte,NaN
22,news_alex-pereira-and-the-ascension-to-superst...,14,0,0,0,1272,14,1.000000,0.000000,0.0,...,/news/alex-pereira-and-the-ascension-to-supers...,Athletes,6 months ago,Alex Pereira And The Ascension To Superstardom,Alex Pereira And The Ascension To Superstardom,A Look Back At “Poatan” And His Banner 2024 Be...,2025-03-05 17:12:45-06:00,2025-03-05 17:24:44-06:00,Zac Pacleb,ZacPacleb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,news_zachary-reese-all-gas-no-brakes-noche-ufc...,11,0,0,1,1050,12,0.916667,0.000000,0.0,...,/news/zachary-reese-all-gas-no-brakes-noche-ufc,Athletes,5 days ago,"Zachary Reese | All Gas, No Brakes","Zachary Reese | All Gas, No Brakes",Texas-Native Zachary Reese Is Feeling More And...,2025-09-10 16:44:39-05:00,2025-09-10 15:49:07-05:00,Thomas Gerbasi,tgerbasi
871,news_zachary-reese-ready-bounce-back-ufc-vegas...,13,0,0,3,1047,16,0.812500,0.000000,0.0,...,/news/zachary-reese-ready-bounce-back-ufc-vega...,Athletes,3 months ago,Zachary Reese | Ready To Bounce Back,Zachary Reese | Ready To Bounce Back,Middleweights Zachary Reese Looks To Return To...,2025-05-29 16:47:37-05:00,2025-05-30 09:51:44-05:00,Thomas Gerbasi,NaN
872,news_zachary-reese-seeks-a-flawless-victory-uf...,16,0,0,1,1174,17,0.941176,0.000000,0.0,...,/news/zachary-reese-seeks-a-flawless-victory-u...,Athletes,7 months ago,Zachary Reese Seeks A 'Flawless Victory',Zachary Reese Seeks A 'Flawless Victory',"After Picking Up Two Wins In 2024, Zachary Ree...",2025-01-16 19:37:59-06:00,2025-01-17 14:06:47-06:00,Thomas Gerbasi,tgerbasi
876,news_zhang-weili-big-challenge-apple-vechain-u...,0,19,0,5,882,24,0.000000,0.791667,0.0,...,/news/zhang-weili-big-challenge-apple-vechain-...,Athletes,1 month ago,Zhang Weili's Big Challenge In The Big Apple,Zhang Weili's Big Challenge In The Big Apple,"Zhang Weili Ruled The World At 115-lbs, But No...",2025-11-12 12:45:22-06:00,2025-11-12 14:03:16-06:00,Simon Head,simonheadsport
877,news_zhang-weili-built-different-ufc-312.txt,0,21,0,3,1341,24,0.000000,0.875000,0.0,...,/news/zhang-weili-built-different-ufc-312,Athletes,7 months ago,Zhang Weili | Built Different,Zhang Weili | Built Different,UFC Strawweight Champion’s Constant Focus On I...,2025-02-05 11:50:00-06:00,2025-02-06 16:36:01-06:00,E. Spencer Kyte,SpencerKyte

In [9]:
mostly_man_sorted = average_num_tokens_df\
                        .sort_values("prop_man_paragraphs", ascending=False)

mostly_man_to_save = mostly_man_sorted.head(EIGHTH_SAMPLE_CORPUS_SIZE)
mostly_man_to_save

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media
779,news_terrance-mckinney-wants-to-put-it-all-tog...,15,0,0,0,826,15,1.0,0.0,0.0,...,/news/terrance-mckinney-wants-to-put-it-all-to...,Athletes,7 months ago,Terrance McKinney Wants To Put It All Together,Terrance McKinney Wants To Put It All Together,"Fighting For The First Time In Eight Months, T...",2025-01-31 11:36:35-06:00,2025-01-31 14:07:54-06:00,Maddyn Johnstone,NaN
716,news_rob-font-is-ready-for-anything-and-everyt...,16,0,0,0,1293,16,1.0,0.0,0.0,...,/news/rob-font-is-ready-for-anything-and-every...,Athletes,6 months ago,Rob Font Is Ready For Anything And Everything,Rob Font Is Ready For Anything And Everything,"Despite A Late Opponent Change, Rob Font Is Ke...",2025-02-20 11:18:00-06:00,2025-02-20 11:17:36-06:00,Zac Pacleb,ZacPacleb
695,news_randy-brown-bringing-the-show-ufc-kansas-...,12,0,0,0,886,12,1.0,0.0,0.0,...,/news/randy-brown-bringing-the-show-ufc-kansas...,Athletes,4 months ago,Randy Brown | Bringing The Show,Randy Brown | Bringing The Show,Welterweight Aims To Put On An Exciting Perfor...,2025-04-25 15:10:24-05:00,2025-04-25 15:38:12-05:00,Maddyn Johnstone,NaN
641,news_patricio-pitbull-ready-to-find-a-rhythm-u...,19,0,0,0,1225,19,1.0,0.0,0.0,...,/news/patricio-pitbull-ready-to-find-a-rhythm-...,Athletes,1 week ago,Patricio Pitbull | Ready To Find A Rhythm,Patricio Pitbull | Ready To Find A Rhythm,Brazilian Veteran Makes Third Appearance In Fi...,2025-09-04 02:57:53-05:00,2025-09-04 11:54:24-05:00,E. Spencer Kyte,spencerkyte
611,news_nassourdine-imavov-sees-all-his-risks-pay...,15,0,0,0,966,15,1.0,0.0,0.0,...,/news/nassourdine-imavov-sees-all-his-risks-pa...,Athletes,7 months ago,Nassourdine Imavov Sees All His Risks Paying Off,Nassourdine Imavov Sees All His Risks Paying Off,"After Picking Up Three Wins In 2024, Nassourdi...",2025-01-29 16:30:00-06:00,2025-01-29 16:28:25-06:00,Zac Pacleb,ZacPacleb

In [10]:
mostly_woman_sorted = average_num_tokens_df\
                        .sort_values("prop_woman_paragraphs", ascending=False)

mostly_woman_to_save = mostly_woman_sorted.head(EIGHTH_SAMPLE_CORPUS_SIZE)
mostly_woman_to_save

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media
517,news_main-event-spotlight-ufc-fight-night-blan...,0,13,0,0,849,13,0.0,1.0,0.0,...,/news/main-event-spotlight-ufc-fight-night-bla...,Fight Coverage,3 months ago,Main Event Spotlight | UFC Fight Night: Blanch...,Main Event Spotlight | UFC Fight Night: Blanch...,Take A Closer Look At The Two Women Involved I...,2025-05-28 10:13:11-05:00,2025-05-28 13:16:54-05:00,Kevin Schuster,KevinESchuster
477,news_macy-chiasson-feels-everything-coming-tog...,0,18,0,0,1401,18,0.0,1.0,0.0,...,/news/macy-chiasson-feels-everything-coming-to...,Athletes,3 months ago,Macy Chiasson Feels Everything Coming Together,Macy Chiasson Feels Everything Coming Together,"In The Biggest Fight Of Her Career, Macy Chias...",2025-05-30 09:50:18-05:00,2025-05-30 10:00:00-05:00,Zac Pacleb,ZacPacleb
209,news_erin-blanchfield-wants-to-make-the-most-o...,0,12,0,0,950,12,0.0,1.0,0.0,...,/news/erin-blanchfield-wants-to-make-the-most-...,Athletes,1 month ago,Erin Blanchfield Wants To Make The Most Of Her…,Erin Blanchfield Wants To Make The Most Of Her...,"Ahead Of A Rematch With Tracy Cortez, Flyweigh...",2025-11-12 16:45:00-06:00,2025-11-12 16:45:15-06:00,Zac Pacleb,ZacPacleb
371,news_jamey-lyn-horth-seeks-redemption-ufc-atla...,0,13,0,0,1280,13,0.0,1.0,0.0,...,/news/jamey-lyn-horth-seeks-redemption-ufc-atl...,Athletes,3 months ago,Jamey-Lyn Horth Seeks Redemption,Jamey-Lyn Horth Seeks Redemption,NaN,2025-06-11 18:07:20-05:00,2025-06-13 11:01:16-05:00,Thomas Gerbasi,tgerbasi
551,news_matchup-spotlight-namajunas-vs-maverick-u...,0,14,0,0,1029,14,0.0,1.0,0.0,...,/news/matchup-spotlight-namajunas-vs-maverick-...,Fight Coverage,3 months ago,Matchup Spotlight | Namajunas vs Maverick,Matchup Spotlight | Namajunas vs Maverick,Breaking Down A Fiery Co-Main Event Between Ra...,2025-06-10 12:51:29-05:00,2025-06-11 17:47:46-05:00,Andrew Thompson,AndyLThompson

Note that there are not any articles with a high proportion of equal paragraphs.

Most of the paragraphs seem to be focused on one person, which makes them strongly gendered.

In [11]:
mostly_equal_sorted = average_num_tokens_df\
                        .sort_values("prop_equal_paragraphs", ascending=False)

mostly_equal_to_save = mostly_equal_sorted.head(EIGHTH_SAMPLE_CORPUS_SIZE)
mostly_equal_to_save

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media
657,news_prelim-results-highlights-winner-intervie...,10,1,3,3,918,17,0.588235,0.058824,0.176471,...,/news/prelim-results-highlights-winner-intervi...,Results,4 months ago,Prelim Results | UFC 315: Muhammad vs Della Ma...,Prelim Results | UFC 315: Muhammad vs Della Ma...,"See The Fight Results, Watch Post-Fight Interv...",2025-05-10 20:52:00-05:00,2025-05-11 00:42:32-05:00,E. Spencer Kyte,SpencerKyte
773,news_tatiana-suarezs-moment-finally-arrives-uf...,0,12,2,4,1257,18,0.000000,0.666667,0.111111,...,/news/tatiana-suarezs-moment-finally-arrives-u...,Athletes,7 months ago,Tatiana Suarez's Moment Finally Arrives,Tatiana Suarez's Moment Finally Arrives,It Always Felt Like The Strawweight Star Would...,2025-02-02 11:43:48-06:00,2025-03-03 15:38:22-06:00,Steve Latrell,NaN
540,news_marion-santos-learning-every-fight-ufc-ve...,9,2,1,0,947,12,0.750000,0.166667,0.083333,...,/news/marion-santos-learning-every-fight-ufc-v...,Athletes,4 months ago,Marion Santos | Learning With Every Fight,Marion Santos | Learning With Every Fight,Brazil's Mairon Santos Enters His Third UFC Fi...,2025-05-16 12:16:06-05:00,2025-05-16 12:28:00-05:00,Thomas Gerbasi,NaN
651,news_prelim-live-results-fight-recaps-highligh...,7,2,1,5,884,15,0.466667,0.133333,0.066667,...,/news/prelim-live-results-fight-recaps-highlig...,Results,1 week ago,Prelim Results | UFC Paris,Prelim Results | UFC Paris,"See The Fight Results, Watch Post-Fight Interv...",2025-09-05 14:32:00-05:00,2025-09-06 14:46:41-05:00,E. Spencer Kyte,spencerkyte
673,news_prelim-results-highlights-winner-intervie...,10,2,1,2,1011,15,0.666667,0.133333,0.066667,...,/news/prelim-results-highlights-winner-intervi...,Results,5 months ago,Prelim Results | UFC Mexico,Prelim Results | UFC Mexico,"See The Fight Results, Watch Post-Fight Interv...",2025-03-29 18:30:00-05:00,2025-03-29 21:14:20-05:00,E. Spencer Kyte,SpencerKyte

In [12]:
mostly_genderless_sorted = average_num_tokens_df\
                            .sort_values("prop_genderless_paragraphs", ascending=False)

mostly_genderless_to_save = mostly_genderless_sorted.head(EIGHTH_SAMPLE_CORPUS_SIZE)
mostly_genderless_to_save

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media
338,news_homefield-advantage-imavov-bsd-sy-gomis-s...,5,0,0,21,821,26,0.192308,0.000000,0.0,...,/news/homefield-advantage-imavov-bsd-sy-gomis-...,Athletes,1 week ago,Homefield Advantage | UFC Paris,Homefield Advantage | UFC Paris,Highlighting The Athletes Of UFC Fight Night: ...,2025-09-03 17:51:17-05:00,2025-09-04 02:39:08-05:00,Steve Latrell,NaN
710,news_representing-mexico-noche-ufc-lopes-vs-si...,5,1,0,21,863,27,0.185185,0.037037,0.0,...,/news/representing-mexico-noche-ufc-lopes-vs-s...,Athletes,5 days ago,Representing Mexico | Noche UFC,Representing Mexico | Noche UFC,Highlighting The Five Athletes Who Will Proudl...,2025-09-10 11:27:51-05:00,2025-09-10 11:47:59-05:00,Simon Head,simonheadsport
321,news_get-know-patchy-mix.txt,7,0,0,18,943,25,0.280000,0.000000,0.0,...,/news/get-know-patchy-mix,Athletes,3 months ago,Get To Know Patchy Mix,Get To Know Patchy Mix,Ahead Of His UFC Debut At UFC 316: Dvalishvili...,2025-06-03 15:01:30-05:00,2025-06-03 15:04:14-05:00,Zac Pacleb,NaN
341,news_homefield-advantage-ufc-mexico-moreno-tor...,17,3,0,17,979,37,0.459459,0.081081,0.0,...,/news/homefield-advantage-ufc-mexico-moreno-to...,Athletes,5 months ago,Homefield Advantage | UFC Mexico,Homefield Advantage | UFC Mexico,Six Athletes Have A Chance To Win One In Their...,2025-03-24 11:00:00-05:00,2025-03-24 12:31:48-05:00,Steve Latrell,NaN
756,news_significant-stats-ufc-316-dvalishvili-vs-...,9,4,0,11,1279,24,0.375000,0.166667,0.0,...,/news/significant-stats-ufc-316-dvalishvili-vs...,Athletes,3 months ago,Significant Stats | UFC 316: Dvalishvili vs O’...,Significant Stats | UFC 316: Dvalishvili vs O’...,Get A Closer Look At The Metrics Behind Some O...,2025-06-04 17:53:04-05:00,2025-06-05 12:00:47-05:00,Zac Pacleb,NaN

In [13]:
no_athletes_pages_df = average_num_tokens_df[average_num_tokens_df["type"] != "Athletes"].copy()
no_athletes_pages_df

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media
69,news_best-of-kaseya-center-ufc-314.txt,17,0,0,3,1085,20,0.850000,0.000000,0.000000,...,/news/best-of-kaseya-center-ufc-314,Fight Coverage,5 months ago,Best Of Kaseya Center,Best Of Kaseya Center,"Before UFC 314, Let’s Take A Look At The Three...",2025-04-08 15:15:00-05:00,2025-04-08 17:23:59-05:00,Andrew Thompson,AndyLThompson
82,news_bmf-title-lineage.txt,10,0,0,3,820,13,0.769231,0.000000,0.000000,...,/news/bmf-title-lineage,Fight Coverage,2 months ago,BMF Title Lineage,BMF Title Lineage,"Ahead Of The Fourth BMF Title Fight, Take A Lo...",2025-07-15 09:25:33-05:00,2025-07-15 10:10:53-05:00,Zac Pacleb,ZacPacleb
118,news_chicago-prelim-results-du-plessis-chimaev...,12,2,1,4,1069,19,0.631579,0.105263,0.052632,...,/news/chicago-prelim-results-du-plessis-chimae...,Results,4 weeks ago,Prelim Results | UFC 319: Du Plessis vs Chimaev,Prelim Results | UFC 319: Du Plessis vs Chimaev,"See The Fight Results, Watch Post-Fight Interv...",2025-08-16 20:26:00-05:00,2025-08-17 02:06:38-05:00,E. Spencer Kyte,SpencerKyte
130,news_co-main-event-spotlight-rafael-fiziev-vs-...,13,0,0,3,1070,16,0.812500,0.000000,0.000000,...,/news/co-main-event-spotlight-rafael-fiziev-vs...,Fight Coverage,2 months ago,Co-Main Event Spotlight | Rafael Fiziev vs Ign...,Co-Main Event Spotlight | Rafael Fiziev vs Ign...,Dynamic Lightweight Strikers Collide In The Co...,2025-06-17 11:33:32-05:00,2025-06-17 11:34:26-05:00,Zac Pacleb,NaN
131,news_co-main-event-spotlight-ufc-london-blacho...,12,0,0,0,843,12,1.000000,0.000000,0.000000,...,/news/co-main-event-spotlight-ufc-london-blach...,Fight Coverage,5 months ago,Co-Main Event Spotlight | UFC London,Co-Main Event Spotlight | UFC London,Get A Closer Look At The Light Heavyweight Cla...,2025-03-18 10:57:37-05:00,2025-03-18 13:02:03-05:00,Zac Pacleb,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,news_week-3-results-scorecards-dana-whites-con...,15,0,0,6,1027,21,0.714286,0.000000,0.000000,...,/news/week-3-results-scorecards-dana-whites-co...,Results,2 weeks ago,Week 3 Results + Scorecards | Dana White's Con...,Week 3 Results + Scorecards | Dana White's Con...,"Live Results, Fight Recaps, Contract Winner In...",2025-08-26 20:50:38-05:00,2025-08-26 22:06:36-05:00,E. Spencer Kyte,SpencerKyte
846,news_week-4-results-scorecards-fight-recaps-in...,14,0,0,5,1005,19,0.736842,0.000000,0.000000,...,/news/week-4-results-scorecards-fight-recaps-i...,Results,1 week ago,Week 4 Results + Scorecards | Dana White's Con...,Week 4 Results + Scorecards | Dana White's Con...,"Live Results, Fight Recaps, Contract Winner In...",2025-09-02 22:00:00-05:00,2025-09-02 22:04:52-05:00,E. Spencer Kyte,SpencerKyte
847,news_week-5-results-scorecards-fight-recaps-co...,13,2,1,4,1048,20,0.650000,0.100000,0.050000,...,/news/week-5-results-scorecards-fight-recaps-c...,Results,6 days ago,Week 5 Results + Scorecards | Dana White's Con...,Week 5 Results + Scorecards | Dana White's Con...,"Live Results, Fight Recaps, Contract Winner In...",2025-09-09 20:43:00-05:00,2025-09-09 21:49:39-05:00,E. Spencer Kyte,SpencerKyte
855,news_where-we-stand-lightweight-division.txt,14,0,0,7,1022,21,0.666667,0.000000,0.000000,...,/news/where-we-stand-lightweight-division,Fight Coverage,2 months ago,Where We Stand: Lightweight Division | July 2025,Where We Stand: Lightweight Division | July 2025,Ilia Topuria Put Himself In Rare Company As He...,2025-07-01 16:05:00-05:00,2025-07-01 17:52:23-05:00,Zac Pacleb on Twitter,ZacPacleb
857,news_where-we-stand-ufc-featherweight-division...,16,0,0,8,1112,24,0.666667,0.000000,0.000000,...,/news/where-we-stand-ufc-featherweight-division,Fight Coverage,5 months ago,Where We Stand: Featherweight Division | April...,Where We Stand: Featherweight Division | April...,Australia’s Alexander Volkanovski Got His Belt...,2025-04-16 11:00:00-05:00,2025-04-16 15:35:19-05:00,Zac Pacleb,ZacPacleb

In [14]:
no_athletes_pages_df["entropy"] = -(
    no_athletes_pages_df["prop_man_paragraphs"] * np.log(no_athletes_pages_df["prop_man_paragraphs"] + 1e-12)
    + no_athletes_pages_df["prop_woman_paragraphs"] * np.log(no_athletes_pages_df["prop_woman_paragraphs"] + 1e-12)
    + no_athletes_pages_df["prop_equal_paragraphs"] * np.log(no_athletes_pages_df["prop_equal_paragraphs"] + 1e-12)
    + no_athletes_pages_df["prop_genderless_paragraphs"] * np.log(no_athletes_pages_df["prop_genderless_paragraphs"] + 1e-12)
)

# Max entropy for 4 categories is log(4)
no_athletes_pages_df["entropy_norm"] = no_athletes_pages_df["entropy"] / np.log(4)

no_athletes_pages_df["variance"] = \
                    (no_athletes_pages_df["prop_man_paragraphs"] - 0.25) ** 2 \
                    + (no_athletes_pages_df["prop_woman_paragraphs"] - 0.25) ** 2 \
                    + (no_athletes_pages_df["prop_equal_paragraphs"] - 0.25) ** 2 \
                    + (no_athletes_pages_df["prop_genderless_paragraphs"] - 0.25) ** 2

# Max possible variance for 4 categories is 0.75
no_athletes_pages_df["variance_norm"] = no_athletes_pages_df["variance"] / 0.75

# Balance out the number of tokens to try to make them as equal as possible
no_athletes_pages_df["tokens_balance"] = \
    abs(no_athletes_pages_df["num_tokens"].median() - no_athletes_pages_df["num_tokens"]) \
    / no_athletes_pages_df["num_tokens"].max()

no_athletes_pages_df["balance"] = no_athletes_pages_df["entropy_norm"] \
                    + (1 - no_athletes_pages_df["variance_norm"]) \
                    + no_athletes_pages_df["tokens_balance"] * 0.2 # Don't weight the token balance as much

balanced_sorted = no_athletes_pages_df.sort_values("balance", ascending=False)

balanced_to_save = balanced_sorted.head(HALF_SAMPLE_CORPUS_SIZE)
balanced_to_save

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,published_time,modified_time,author,social_media,entropy,entropy_norm,variance,variance_norm,tokens_balance,balance
651,news_prelim-live-results-fight-recaps-highligh...,7,2,1,5,884,15,0.466667,0.133333,0.066667,...,2025-09-05 14:32:00-05:00,2025-09-06 14:46:41-05:00,E. Spencer Kyte,spencerkyte,1.171060,0.844741,0.101111,0.134815,0.098805,1.729687
669,news_prelim-results-highlights-winner-intervie...,11,6,1,4,955,22,0.500000,0.272727,0.045455,...,2025-06-21 14:12:00-05:00,2025-06-23 11:02:03-05:00,Thomas Gerbasi,TGerbasi,1.151380,0.830545,0.109504,0.146006,0.048875,1.694314
487,news_main-card-results-highlights-winner-inter...,10,4,1,3,1117,18,0.555556,0.222222,0.055556,...,2025-05-10 23:39:00-05:00,2025-05-11 01:09:38-05:00,E. Spencer Kyte,SpencerKyte,1.119990,0.807902,0.138889,0.185185,0.065049,1.635727
755,news_significant-stats-ufc-315-muhammad-vs-del...,3,6,0,6,1161,15,0.200000,0.400000,0.000000,...,2025-05-07 13:10:01-05:00,2025-05-07 13:12:55-05:00,Zac Paclebs,NaN,1.054920,0.760964,0.110000,0.146667,0.095992,1.633496
657,news_prelim-results-highlights-winner-intervie...,10,1,3,3,918,17,0.588235,0.058824,0.176471,...,2025-05-10 20:52:00-05:00,2025-05-11 00:42:32-05:00,E. Spencer Kyte,SpencerKyte,1.091006,0.786994,0.161765,0.215686,0.074895,1.586287
663,news_prelim-results-highlights-winner-intervie...,8,7,0,2,1116,17,0.470588,0.411765,0.000000,...,2025-05-17 19:03:00-05:00,2025-05-29 17:02:33-05:00,E. Spencer Kyte,SpencerKyte,0.971849,0.701041,0.154844,0.206459,0.064346,1.507451
659,news_prelim-results-highlights-winner-intervie...,8,3,0,3,869,14,0.571429,0.214286,0.000000,...,2025-06-27 21:28:00-05:00,2025-06-29 01:02:23-05:00,E. Spencer Kyte,SpencerKyte,0.979971,0.706900,0.168367,0.224490,0.109353,1.504281
815,news_ufc-fight-night-garcia-vs-onama-prelim-re...,8,6,0,2,1059,16,0.500000,0.375000,0.000000,...,2025-11-01 18:22:00-05:00,2025-11-01 20:51:04-05:00,E. Spencer Kyte,SpencerKyte,0.974315,0.702820,0.156250,0.208333,0.024262,1.499339
674,news_prelim-results-highlights-winner-intervie...,5,8,0,2,991,15,0.333333,0.533333,0.000000,...,2025-05-03 21:03:00-05:00,2025-05-04 00:58:31-05:00,E. Spencer Kyte,SpencerKyte,0.970116,0.699791,0.163333,0.217778,0.023558,1.486725
672,news_prelim-results-highlights-winner-intervie...,12,4,0,4,1237,20,0.600000,0.200000,0.000000,...,2025-04-26 20:00:00-05:00,2025-04-26 23:35:27-05:00,E. Spencer Kyte,SpencerKyte,0.950271,0.685475,0.190000,0.253333,0.149437,1.462029
118,news_chicago-prelim-results-du-plessis-chimaev...,12,2,1,4,1069,19,0.631579,0.105263,0.052632,...,2025-08-16 20:26:00-05:00,2025-08-17 02:06:38-05:00,E. Spencer Kyte,SpencerKyte,1.010210,0.728712,0.207064,0.276085,0.031294,1.458886
671,news_prelim-results-highlights-winner-intervie...,10,4,0,3,1008,17,0.588235,0.235294,0.000000,...,2025-07-12 20:21:00-05:00,2025-07-12 23:33:03-05:00,E. Spencer Kyte,SpencerKyte,0.958692,0.691550,0.182526,0.243368,0.011603,1.450503
656,news_prelim-results-highlights-winner-intervie...,12,5,0,3,1243,20,0.600000,0.250000,0.000000,...,2025-04-12 20:59:00-05:00,2025-04-16 11:59:49-05:00,E. Spencer Kyte,SpencerKyte,0.937637,0.676362,0.195000,0.260000,0.153657,1.447093
485,news_main-card-results-highlights-winner-inter...,11,1,1,5,1063,18,0.611111,0.055556,0.055556,...,2025-03-08 23:00:00-06:00,2025-03-09 01:21:29-06:00,E. Spencer Kyte,spencerkyte,0.977925,0.705424,0.206790,0.275720,0.027075,1.435119
670,news_prelim-results-highlights-winner-intervie...,8,3,0,2,810,13,0.615385,0.230769,0.000000,...,2025-03-01 18:47:00-06:00,2025-03-01 21:12:25-06:00,E. Spencer Kyte,SpencerKyte,0.925129,0.667340,0.205621,0.274162,0.150844,1.423347
666,news_prelim-results-highlights-winner-intervie...,11,4,0,3,1139,18,0.611111,0.222222,0.000000,...,2025-01-11 21:08:00-06:00,2025-01-13 12:27:19-06:00,E. Spencer Kyte,spencerkyte,0.933824,0.673612,0.200617,0.267490,0.080520,1.422226
847,news_week-5-results-scorecards-fight-recaps-co...,13,2,1,4,1048,20,0.650000,0.100000,0.050000,...,2025-09-09 20:43:00-05:00,2025-09-09 21:49:39-05:00,E. Spencer Kyte,SpencerKyte,0.981942,0.708321,0.225000,0.300000,0.016526,1.411626
497,news_main-card-results-highlights-winner-inter...,11,3,0,4,993,18,0.611111,0.166667,0.000000,...,2025-01-11 21:08:00-06:00,2025-01-13 12:27:51-06:00,E. Spencer Kyte,spencerkyte,0.933824,0.673612,0.200617,0.267490,0.022152,1.410552
673,news_prelim-results-highlights-winner-intervie...,10,2,1,2,1011,15,0.666667,0.133333,0.066667,...,2025-03-29 18:30:00-05:00,2025-03-29 21:14:20-05:00,E. Spencer Kyte,SpencerKyte,0.988154,0.712803,0.234444,0.312593,0.009494,1.402109
607,news_most-shocking-knockouts-in-ufc-history-co...,7,1,0,4,913,12,0.583333,0.083333,0.000000,...,2025-12-22 09:45:00-06:00,2025-12-22 09:50:59-06:00,Kevin Schuster,NaN,0.887694,0.640336,0.208333,0.277778,0.078411,1.378240
493,news_main-card-results-highlights-winner-inter...,9,3,0,2,801,14,0.642857,0.214286,0.000000,...,2025-05-31 22:25:00-05:00,2025-05-31 23:45:59-05:00,E. Spencer Kyte,SpencerKyte,0.892118,0.643527,0.229592,0.306122,0.157173,1.368839

In [15]:
os.makedirs("./sample_corpus", exist_ok=True)
os.makedirs("./sample_corpus/mostly_man", exist_ok=True)
os.makedirs("./sample_corpus/mostly_woman", exist_ok=True)
os.makedirs("./sample_corpus/mostly_equal", exist_ok=True)
os.makedirs("./sample_corpus/mostly_genderless", exist_ok=True)
os.makedirs("./sample_corpus/balanced", exist_ok=True)

In [16]:
for file in mostly_man_to_save["file"]:
    copyfile(f"./articles/{file}", f"./sample_corpus/mostly_man/{file}")

for file in mostly_woman_to_save["file"]:
    copyfile(f"./articles/{file}", f"./sample_corpus/mostly_woman/{file}")

for file in mostly_equal_to_save["file"]:
    copyfile(f"./articles/{file}", f"./sample_corpus/mostly_equal/{file}")

for file in mostly_genderless_to_save["file"]:
    copyfile(f"./articles/{file}", f"./sample_corpus/mostly_genderless/{file}")

for file in balanced_to_save["file"]:
    copyfile(f"./articles/{file}", f"./sample_corpus/balanced/{file}")

In [17]:
all_files = (
    mostly_man_to_save["file"].to_list() \
    + mostly_woman_to_save["file"].to_list() \
    + mostly_equal_to_save["file"].to_list() \
    + mostly_genderless_to_save["file"].to_list() \
    + balanced_to_save["file"].to_list() \
)

Now create backup corpus

In [18]:
mostly_man_to_save_backup = mostly_man_sorted.iloc[EIGHTH_SAMPLE_CORPUS_SIZE : EIGHTH_SAMPLE_CORPUS_SIZE * 2]
mostly_man_to_save_backup

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media
609,news_nassourdine-imavov-hoping-capitalize-big-...,12,0,0,0,944,12,1.0,0.0,0.0,...,/news/nassourdine-imavov-hoping-capitalize-big...,Athletes,7 months ago,Nassourdine Imavov Hoping To Capitalize On Big...,Nassourdine Imavov Hoping To Capitalize On Big...,Middleweight Contender Nassourdine Imavov Boun...,2025-01-28 15:16:44-06:00,2025-01-28 15:25:04-06:00,Zac Pacleb,ZacPacleb
542,news_marquel-mederos-ready-to-perform-ufc-mexi...,11,0,0,0,1021,11,1.0,0.0,0.0,...,/news/marquel-mederos-ready-to-perform-ufc-mexico,Athletes,5 months ago,MarQuel Mederos | Ready To Perform,MarQuel Mederos | Ready To Perform,Lightweight MarQuel Mederos Looks To Silence T...,2025-03-28 16:35:44-05:00,2025-03-28 16:35:31-05:00,Thomas Gerbasi,NaN
460,news_leon-edwards-career-highlights.txt,29,0,0,0,942,29,1.0,0.0,0.0,...,/news/leon-edwards-career-highlights,Athletes,5 months ago,Leon Edwards Career Highlights,Leon Edwards Career Highlights,Learn More About Leon “Rocky” Edwards’ Career ...,2025-03-17 13:23:21-05:00,2025-03-17 13:03:58-05:00,Zac Pacleb,NaN
420,news_justin-gaethje-ready-to-go-again-ufc-313-...,12,0,0,0,1081,12,1.0,0.0,0.0,...,/news/justin-gaethje-ready-to-go-again-ufc-313...,Athletes,6 months ago,Justin Gaethje | Ready To Go Again,Justin Gaethje | Ready To Go Again,"With Title Aspirations Top Of Mind, Justin Gae...",2025-03-06 13:53:28-06:00,2025-03-06 15:23:17-06:00,Zac Pacleb,ZacPacleb
419,news_junyong-park-hungry-for-more-ufc-321.txt,22,0,0,0,1360,22,1.0,0.0,0.0,...,/news/junyong-park-hungry-for-more-ufc-321,Athletes,1 week ago,Junyong Park | Hungry For More,Junyong Park | Hungry For More,Playful South Korean Middleweight Ready To Com...,2025-10-24 18:37:16-05:00,2025-10-24 18:18:15-05:00,E. Spencer Kyte,NaN

In [19]:
mostly_woman_to_save_backup = mostly_woman_sorted.iloc[EIGHTH_SAMPLE_CORPUS_SIZE : EIGHTH_SAMPLE_CORPUS_SIZE * 2]
mostly_woman_to_save_backup

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media
589,news_miranda-maverick-cleared-for-take-off-ufc...,0,19,0,0,1137,19,0.0,1.000000,0.0,...,/news/miranda-maverick-cleared-for-take-off-uf...,Athletes,3 months ago,Miranda Maverick | Cleared For Take-Off,Miranda Maverick | Cleared For Take-Off,Number 11 Ranked Women’s Flyweight Miranda Mav...,2025-06-12 15:00:00-05:00,2025-06-12 15:37:25-05:00,Andrew Thompson,AndyLThompson
725,news_rose-namajunas-is-still-improving-every-d...,0,15,0,0,1129,15,0.0,1.000000,0.0,...,/news/rose-namajunas-is-still-improving-every-...,Athletes,3 months ago,Rose Namajunas Is Still Improving Every Day,Rose Namajunas Is Still Improving Every Day,Former Strawweight Champion Rose Namajunas Hop...,2025-06-12 15:05:00-05:00,2025-06-12 15:40:01-05:00,Zac Pacleb,NaN
772,news_tatiana-suarez-its-long-way-top-ufc-312.txt,0,24,0,0,1056,24,0.0,1.000000,0.0,...,/news/tatiana-suarez-its-long-way-top-ufc-312,Athletes,7 months ago,Tatiana Suarez | It’s A Long Way To The Top…,Tatiana Suarez | It’s A Long Way To The Top…,The Longtime Strawweight Contender Has Had To ...,2025-01-22 13:27:00-06:00,2025-01-22 13:08:07-06:00,Simon Head,simonheadsport
472,news_loopy-godinez-i-feel-i-have-improved-ufc-...,0,17,0,1,983,18,0.0,0.944444,0.0,...,/news/loopy-godinez-i-feel-i-have-improved-ufc...,Athletes,1 month ago,Loopy Godinez | 'I Feel Like I Have Improved',Loopy Godinez | 'I Feel Like I Have Improved',Strawweight Loopy Godinez Believes She Has Onl...,2025-08-15 11:35:00-05:00,2025-08-15 11:36:16-05:00,Thomas Gerbasi,Tgerbasi
35,news_alice-ardelean-is-planning-her-big-move-u...,0,17,0,1,1100,18,0.0,0.944444,0.0,...,/news/alice-ardelean-is-planning-her-big-move-...,Athletes,1 month ago,Alice Ardelean Is Planning Her Big Move,Alice Ardelean Is Planning Her Big Move,With Ambitions Of Progressing Up The Strawweig...,2025-10-30 12:47:34-05:00,2025-10-30 12:53:39-05:00,Simon Head,simonheadsport

In [20]:
mostly_equal_to_save_backup = mostly_equal_sorted.iloc[EIGHTH_SAMPLE_CORPUS_SIZE : EIGHTH_SAMPLE_CORPUS_SIZE * 2]
mostly_equal_to_save_backup

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media
485,news_main-card-results-highlights-winner-inter...,11,1,1,5,1063,18,0.611111,0.055556,0.055556,...,/news/main-card-results-highlights-winner-inte...,Results,6 months ago,Main Card Results | UFC 313: Pereira vs Ankalaev,Main Card Results | UFC 313: Pereira vs Ankalaev,"See The Fight Results, Watch Post-Fight Interv...",2025-03-08 23:00:00-06:00,2025-03-09 01:21:29-06:00,E. Spencer Kyte,spencerkyte
487,news_main-card-results-highlights-winner-inter...,10,4,1,3,1117,18,0.555556,0.222222,0.055556,...,/news/main-card-results-highlights-winner-inte...,Results,4 months ago,Main Card Results | UFC 315: Muhammad vs Della…,Main Card Results | UFC 315: Muhammad vs Della...,"See The Fight Results, Watch Post-Fight Interv...",2025-05-10 23:39:00-05:00,2025-05-11 01:09:38-05:00,E. Spencer Kyte,SpencerKyte
557,news_mateus-camilo-hunger-dream-ufc-vegas-106.txt,16,1,1,0,1010,18,0.888889,0.055556,0.055556,...,/news/mateus-camilo-hunger-dream-ufc-vegas-106,Athletes,4 months ago,Mateus Camilo | Hunger For A Dream,Mateus Camilo | Hunger For A Dream,Brazilian Lightweight Looking To Make The Most...,2025-05-15 09:57:07-05:00,2025-05-15 10:21:41-05:00,Thomas Gerbasi,thomasgerbasi
118,news_chicago-prelim-results-du-plessis-chimaev...,12,2,1,4,1069,19,0.631579,0.105263,0.052632,...,/news/chicago-prelim-results-du-plessis-chimae...,Results,4 weeks ago,Prelim Results | UFC 319: Du Plessis vs Chimaev,Prelim Results | UFC 319: Du Plessis vs Chimaev,"See The Fight Results, Watch Post-Fight Interv...",2025-08-16 20:26:00-05:00,2025-08-17 02:06:38-05:00,E. Spencer Kyte,SpencerKyte
68,news_benoit-saint-denis-the-god-of-war-has-ret...,13,1,1,4,911,19,0.684211,0.052632,0.052632,...,/news/benoit-saint-denis-the-god-of-war-has-re...,Athletes,4 months ago,Benoît Saint Denis | The God Of War Has Returned,Benoît Saint Denis | The God Of War Has Returned,Lightweight Benoit Saint Denis Looks To Bounce...,2025-05-09 14:02:35-05:00,2025-05-09 14:10:54-05:00,Andrew Thompson,AndyLThompson

In [21]:
mostly_genderless_to_save_backup = mostly_genderless_sorted.iloc[EIGHTH_SAMPLE_CORPUS_SIZE : EIGHTH_SAMPLE_CORPUS_SIZE * 2]
mostly_genderless_to_save_backup

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,link,type,time_ago,headline,title,description,published_time,modified_time,author,social_media
55,news_asu-almabayev-is-ready-for-his-big-opport...,13,0,0,10,1050,23,0.565217,0.0,0.0,...,/news/asu-almabayev-is-ready-for-his-big-oppor...,Athletes,6 months ago,Asu Almabayev Is Ready For His Big Opportunity,Asu Almabayev Is Ready For His Big Opportunity,Kazakhstan's Rising Flyweight Contender Plans ...,2025-02-27 21:24:00-06:00,2025-02-27 21:23:56-06:00,Simon Head,simonheadsport
755,news_significant-stats-ufc-315-muhammad-vs-del...,3,6,0,6,1161,15,0.200000,0.4,0.0,...,/news/significant-stats-ufc-315-muhammad-vs-de...,Fight Coverage,4 months ago,Significant Stats | UFC 315: Muhammad vs Della…,Significant Stats | UFC 315: Muhammad vs Della...,Preview The Key Matchups Of The Top Three Figh...,2025-05-07 13:10:01-05:00,2025-05-07 13:12:55-05:00,Zac Paclebs,NaN
758,news_significant-stats-ufc-318-holloway-vs-poi...,12,0,0,8,1367,20,0.600000,0.0,0.0,...,/news/significant-stats-ufc-318-holloway-vs-po...,Athletes,1 month ago,Significant Stats | UFC 318: Holloway vs Poiri...,Significant Stats | UFC 318: Holloway vs Poiri...,Get A Closer Look At The Metrics Behind Some O...,2025-07-16 15:23:50-05:00,2025-07-16 16:09:23-05:00,NaN,NaN
583,news_michael-venom-page-this-one-is-for-the-fa...,15,0,0,10,1024,25,0.600000,0.0,0.0,...,/news/michael-venom-page-this-one-is-for-the-f...,Athletes,7 months ago,Michael 'Venom' Page | This One's For The Fans,Michael 'Venom' Page | This One's For The Fans,"The One And Only ""MVP"" Has Made His Name From ...",2025-01-31 13:21:03-06:00,2025-01-31 15:05:59-06:00,Simon Head,simonheadsport
753,news_significant-stats-ufc-313-pereira-vs-anka...,9,0,0,6,1247,15,0.600000,0.0,0.0,...,/news/significant-stats-ufc-313-pereira-vs-ank...,Fight Coverage,6 months ago,Significant Stats | UFC 313: Pereira vs Ankalaev,Significant Stats | UFC 313: Pereira vs Ankalaev,Preview The Key Matchups Of The Top Three Figh...,2025-03-05 17:15:00-06:00,2025-03-05 17:21:26-06:00,Zac Pacleb,ZacPacleb

In [22]:
balanced_to_save_backup = balanced_sorted.iloc[HALF_SAMPLE_CORPUS_SIZE : HALF_SAMPLE_CORPUS_SIZE * 2]
balanced_to_save_backup

,file,num_man_paragraphs,num_woman_paragraphs,num_equal_paragraphs,num_genderless_paragraphs,num_tokens,num_paragraphs,prop_man_paragraphs,prop_woman_paragraphs,prop_equal_paragraphs,...,published_time,modified_time,author,social_media,entropy,entropy_norm,variance,variance_norm,tokens_balance,balance
452,news_last-time-in-chicago.txt,11,4,0,2,1303,17,0.647059,0.235294,0.0,...,2025-08-12 16:33:17-05:00,2025-08-12 16:42:22-05:00,Zac Pacleb,ZacPacleb,0.873900,0.630386,0.237889,0.317186,0.195851,1.352370
661,news_prelim-results-highlights-winner-intervie...,9,2,0,3,957,14,0.642857,0.142857,0.0,...,2025-02-01 10:55:00-06:00,2025-02-01 14:11:53-06:00,E. Spencer Kyte,spencerkyte,0.892118,0.643527,0.229592,0.306122,0.047468,1.346898
654,news_prelim-results-highlights-winner-intervie...,12,2,0,5,1112,19,0.631579,0.105263,0.0,...,2025-02-08 16:45:00-06:00,2025-02-10 14:15:57-06:00,E. Spencer Kyte,SpencerKyte,0.878525,0.633722,0.229224,0.305633,0.061533,1.340396
809,news_ufc-321-aspinall-vs-gane-event-tonight-ma...,8,2,0,2,841,12,0.666667,0.166667,0.0,...,2025-10-25 17:03:00-05:00,2025-10-27 10:53:20-05:00,E. Spencer Kyte,SpencerKyte,0.867563,0.625815,0.250000,0.333333,0.129044,1.318290
484,news_main-card-results-highlights-winner-inter...,9,2,0,2,876,13,0.692308,0.153846,0.0,...,2025-02-08 23:30:00-06:00,2025-02-10 14:16:06-06:00,E. Spencer Kyte,SpencerKyte,0.830518,0.599092,0.276627,0.368836,0.104430,1.251142
676,news_prelim-results-highlights-winner-intervie...,11,2,0,3,917,16,0.687500,0.125000,0.0,...,2025-06-14 21:05:00-05:00,2025-06-15 00:38:54-05:00,E. Spencer Kyte,SpencerKyte,0.831403,0.599730,0.273438,0.364583,0.075598,1.250266
653,news_prelim-results-highlights-winner-intervie...,13,2,0,4,1149,19,0.684211,0.105263,0.0,...,2025-01-18 22:45:00-06:00,2025-01-19 02:15:18-06:00,E. Spencer Kyte,spencerkyte,0.824659,0.594866,0.273546,0.364728,0.087553,1.247649
735,news_scorecard-ufc-fight-night-garcia-vs-onama...,16,4,0,3,1046,23,0.695652,0.173913,0.0,...,2025-11-02 15:16:21-06:00,2025-11-02 15:35:02-06:00,Simon Head,simonheadsport,0.822345,0.593196,0.281191,0.374921,0.015120,1.221299
507,news_main-card-results-highlights-winner-inter...,12,1,0,5,1135,18,0.666667,0.055556,0.0,...,2025-06-13 01:18:00-05:00,2025-06-15 01:20:01-05:00,E. Spencer Kyte,SpencerKyte,0.786701,0.567485,0.274691,0.366255,0.077707,1.216771
498,news_main-card-results-highlights-winner-inter...,14,2,0,4,1167,20,0.700000,0.100000,0.0,...,2025-03-22 17:51:00-05:00,2025-03-22 19:21:13-05:00,E. Spencer Kyte,SpencerKyte,0.801819,0.578390,0.290000,0.386667,0.100211,1.211765
810,news_ufc-321-aspinall-vs-gane-event-tonight-pr...,13,2,0,3,1136,18,0.722222,0.111111,0.0,...,2025-10-25 13:15:00-05:00,2025-10-25 16:38:30-05:00,E. Spencer Kyte,SpencerKyte,0.777790,0.561057,0.311728,0.415638,0.078411,1.161101
753,news_significant-stats-ufc-313-pereira-vs-anka...,9,0,0,6,1247,15,0.600000,0.000000,0.0,...,2025-03-05 17:15:00-06:00,2025-03-05 17:21:26-06:00,Zac Pacleb,ZacPacleb,0.673012,0.485475,0.270000,0.360000,0.156470,1.156769
660,news_prelim-results-highlights-winner-intervie...,14,2,0,3,1182,19,0.736842,0.105263,0.0,...,2025-07-19 21:43:00-05:00,2025-07-19 21:43:27-05:00,E. Spencer Kyte,SpencerKyte,0.753442,0.543494,0.328947,0.438596,0.110759,1.127049
658,news_prelim-results-highlights-winner-intervie...,15,2,0,3,1235,20,0.750000,0.100000,0.0,...,2025-06-07 21:10:00-05:00,2025-06-08 00:45:05-05:00,E. Spencer Kyte,SpencerKyte,0.730588,0.527008,0.345000,0.460000,0.148031,1.096614
506,news_main-card-results-highlights-winner-inter...,9,2,0,1,823,12,0.750000,0.166667,0.0,...,2025-08-02 22:47:00-05:00,2025-08-02 22:47:55-05:00,E. Spencer Kyte,SpencerKyte,0.721464,0.520426,0.347222,0.462963,0.141702,1.085803
675,news_prelim-results-highlights-winner-intervie...,12,2,0,2,1069,16,0.750000,0.125000,0.0,...,2025-08-02 21:31:00-05:00,2025-08-09 19:27:17-05:00,E. Spencer Kyte,SpencerKyte,0.735622,0.530639,0.343750,0.458333,0.031294,1.078565
496,news_main-card-results-highlights-winner-inter...,8,0,0,4,857,12,0.666667,0.000000,0.0,...,2025-02-22 23:30:00-06:00,2025-02-24 14:36:13-06:00,E. Spencer Kyte,SpencerKyte,0.636514,0.459148,0.305556,0.407407,0.117792,1.075299
857,news_where-we-stand-ufc-featherweight-division...,16,0,0,8,1112,24,0.666667,0.000000,0.0,...,2025-04-16 11:00:00-05:00,2025-04-16 15:35:19-05:00,Zac Pacleb,ZacPacleb,0.636514,0.459148,0.305556,0.407407,0.061533,1.064047
855,news_where-we-stand-lightweight-division.txt,14,0,0,7,1022,21,0.666667,0.000000,0.0,...,2025-07-01 16:05:00-05:00,2025-07-01 17:52:23-05:00,Zac Pacleb on Twitter,ZacPacleb,0.636514,0.459148,0.305556,0.407407,0.001758,1.052092
679,news_prelim-results-ufc-323-dvalishvili-vs-yan...,17,3,0,2,1329,22,0.772727,0.136364,0.0,...,2025-12-06 19:00:00-06:00,2025-12-06 21:55:58-06:00,E. Spencer Kyte,SpencerKyte,0.688917,0.496949,0.373967,0.498623,0.214135,1.041153
667,news_prelim-results-highlights-winner-intervie...,14,2,0,2,1168,18,0.777778,0.111111,0.0,...,2025-03-22 14:47:00-05:00,2025-03-22 18:32:12-05:00,E. Spencer Kyte,SpencerKyte,0.683739,0.493213,0.379630,0.506173,0.100914,1.007223

In [23]:
os.makedirs("./sample_corpus_backup", exist_ok=True)
os.makedirs("./sample_corpus_backup/mostly_man", exist_ok=True)
os.makedirs("./sample_corpus_backup/mostly_woman", exist_ok=True)
os.makedirs("./sample_corpus_backup/mostly_equal", exist_ok=True)
os.makedirs("./sample_corpus_backup/mostly_genderless", exist_ok=True)
os.makedirs("./sample_corpus_backup/balanced", exist_ok=True)

In [24]:
for file in mostly_man_to_save_backup["file"]:
    copyfile(f"./articles/{file}", f"./sample_corpus_backup/mostly_man/{file}")

for file in mostly_woman_to_save_backup["file"]:
    copyfile(f"./articles/{file}", f"./sample_corpus_backup/mostly_woman/{file}")

for file in mostly_equal_to_save_backup["file"]:
    copyfile(f"./articles/{file}", f"./sample_corpus_backup/mostly_equal/{file}")

for file in mostly_genderless_to_save_backup["file"]:
    copyfile(f"./articles/{file}", f"./sample_corpus_backup/mostly_genderless/{file}")

for file in balanced_to_save_backup["file"]:
    copyfile(f"./articles/{file}", f"./sample_corpus_backup/balanced/{file}")